InformedSolutions/JAQU-CAZ-Fleets-UI

- .rubocop.yml
- app/api_wrappers/accounts_api.rb
- app/controllers/organisations_controller.rb
- app/forms/email_and_password_form.rb
- app/services/create_account.rb
- app/services/encryption/decrypt.rb
- app/services/sqs/base.rb
- app/services/sqs/verification_email.rb
- app/services/verify_account.rb
- app/views/layouts/_navbar.haml
- app/views/organisations/email_sent.html.haml
- app/views/organisations/verification_failed.html.haml
- config/locales/en.yml
- config/routes.rb
- features/organisations.feature
- features/step_definitions/organisations_steps.rb
- features/support/sign_in_helper.rb
- spec/forms/email_and_password_form_spec.rb
- spec/requests/organisations_controller/email_sent_spec.rb
- spec/requests/organisations_controller/email_verification_spec.rb
- spec/requests/organisations_controller/resend_email_spec.rb
- spec/requests/organisations_controller/verification_failed_spec.rb
- spec/services/create_account_spec.rb
- spec/services/encryption/decrypt_spec.rb
- spec/services/encryption/encrypt_spec.rb
- spec/services/sqs/verification_email_spec.rb
- spec/services/verify_account_spec.rb
- spec/support/user_factory.rb
https://eaflood.atlassian.net/browse/CAZ-1557
Added handling link `http://localhost:3000/fleets/organisation-account/email-verification?token=:token`
When the token is valid it redirects to email verified page, if not it redirects to the custom error page.
As emails are not being delivered - use the link from logs from `Sqs::VerificationEmail`.
To check the invalid token, remove some parts of the token. Remember that it can't end with a % sign.
> [CAZ-1557] Handle verification link

- app/views/layouts/_navbar.haml
- features/organisations.feature
- features/sign_in.feature
[JIRA](https://eaflood.atlassian.net/browse/CAZ-1285)
> [CAZ-1285] Hide create account button only on create account and new credentials pages

- .env.example
- Gemfile
- Gemfile.lock
- app/api_wrappers/fleets_api.rb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/session_store.rb
https://eaflood.atlassian.net/browse/CAZ-1834
Added Redis store which is configured via `REDIS_URL` env variable. If the variable is empty, server falls back to the cookie-based store.
> [CAZ-1834] Add redis session store

- app/api_wrappers/accounts_api.rb
- app/controllers/passwords_controller.rb
- features/step_definitions/password_reset_steps.rb
- spec/api_wrappers/accounts_api/initiate_password_reset_spec.rb
- spec/requests/passwords/validate_spec.rb
Relates to this change: https://github.com/InformedSolutions/JAQU-CAZ-Java-Common/pull/106/
> [CAZ-2027] Add reset url to initiate_password_reset

- app/forms/reset_password_form.rb
- features/password_reset.feature
- spec/forms/reset_password_form_spec.rb
[JIRA](https://eaflood.atlassian.net/browse/CAZ-2122)
> [CAZ-2122] User password reset - wrong message for empty email

- app/controllers/payments_controller.rb
- app/helpers/payments_helper.rb
- app/services/make_payment.rb
- app/services/session_manipulation/add_current_payment.rb
- spec/services/make_payment_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZ-2021
We need to store the session of initiated payment but we don't want to reuse it for the next payments. 
Added new key to the session to store initiated payment details.
After the changes, we clear the session for new_payment after payment initiation.
Additionally fixed the bug with sending pounds instead of pence values for charges. 
Fixed unit tests. 
To test sessions:
Process, the first transaction to the payment page. 
And then that try to create a new transaction in a new window. 
N/A
> [CAZ-2021] Store Initiate payment session

- app/javascript/src/payment_matrix/initSearch.js
Wraps the clear search link in a null check to avoid javascript errors being raised on page load when no search has been triggered.
Note this is to resolve pagination triggers not firing (as the JS doesn't get attached).
> Wrap clear search link javascript in null check

- app/javascript/src/payment_matrix/createHiddenInput.js
This previously would raise error on a search being triggered. The regex approach supports vrns with whitespace inside (rather than a simply trim on the string).
> Remove all whitespace from search input value

- config/locales/en.yml
- features/sign_in.feature
- lib/devise/strategies/remote.rb
- spec/requests/sign_in_spec.rb
[CAZ-2294](https://eaflood.atlassian.net/browse/CAZ-2294)
* Removes `Enter your email address` and `Enter your password` information when provided both email and password but one of them is invalid.
* Manually
* Adjusted RSpec and cucumber specs.
> [CAZ-2294] Login Page errors refinement

- app/views/passwords/invalid.html.haml
- features/password_reset.feature
https://eaflood.atlassian.net/browse/CAZ-2297
> [CAZ-2297] Remove back link from Reset Password token expired page

- lib/devise/strategies/remote.rb
https://eaflood.atlassian.net/browse/CAZ-2294
```Just as a quick note on the above - as we’re not showing an error message - the CSS for the email/password fields does not need to be rendered in red.```
> [CAZ-2294] Remove red lines for email/password fields

- app/views/payments/matrix/vrn_input/_errored.html.haml
- app/views/payments/matrix/vrn_input/_normal.html.haml
https://eaflood.atlassian.net/browse/CAZ-2349
* Removed unnecessary `aria-describedby` and `aria-labelledby` attributes from normal and errored VRN search input.
Manually with WAVE.
> [CAZ-2349] Removal of invalid aria attributes

- app/helpers/payments_helper.rb
- app/services/base_payment.rb
- app/views/payments/matrix.html.haml
- app/views/payments/matrix/_no_chargeable_vehicles.html.haml
- app/views/payments/matrix/_table.html.haml
https://eaflood.atlassian.net/browse/CAZ-2348
* As some of the screen readers have problems with reading dates in the previously existing format (e.g. "2020-03-25"), the introduced change makes the format more user friendly (e.g. "25 March 2020"). When the request is being sent to the backend, the dates are transformed to the format which was used earlier so that does not violate the integration. 
* Manually tested if the payment process works the same as it was.
N/A
> [CAZ-2348] Updated checkboxes values to be more user friendly

- app/controllers/dashboard_controller.rb
- app/views/dashboard/_direct_debit.html.haml
- features/debits.feature
- features/fleets.feature
- features/step_definitions/debits_steps.rb
- features/step_definitions/fleets_steps.rb
- features/step_definitions/navigate_pages_steps.rb
- features/step_definitions/payments_steps.rb
- features/step_definitions/sign_in_steps.rb
- features/step_definitions/uploads_step.rb
- features/step_definitions/vehicles_steps.rb
- features/support/mock_debit.rb
- features/vehicles.feature
- spec/fixtures/responses/debits/active_mandates.json
- spec/fixtures/responses/debits/inactive_mandates.json
- spec/fixtures/responses/debits/mandates.json
- spec/requests/dashboard_controller_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2513 - fix card for:
https://eaflood.atlassian.net/browse/CAZ-2511
* `DirectDebitMandates` are now fetched when entering the dashboard page. When a user has any active direct debits the new copy is displayed for him.
**When a user has no mandates:**
----
**When a user has active mandates:**
> [CAZ-2513] DirectDebit mandate text change

- app/controllers/vehicles_controller.rb
- app/views/vehicles/not_found.html.haml
- config/locales/en.yml
- config/routes.rb
- features/step_definitions/helper_steps.rb
- features/step_definitions/vehicles_steps.rb
- features/vehicles.feature
- spec/requests/vehicles/confirm_not_found_spec.rb
Previously you were able to upload unknown vehicles via CSV but not able to manually add them. On checking the business requirement, it was specificied that users should be able to add unknown vehicles via the UI.
Fixes [CAZ-2339](https://eaflood.atlassian.net/browse/CAZ-2339)
- Change unknown vehicle page to mirror IOD (including new confirmation checkbox).
- Add unknown vehicle to account when 'Continue' pressed on this page.
- New `rspec` tests
- New `cucumber` tests
- Manually
> [CAZ-2339] Allow manual addition of unknown vehicles to fleet

- .drone.yml
- app/controllers/dashboard_controller.rb
- app/controllers/payments_controller.rb
- app/views/dashboard/index.html.haml
- features/dashboard.feature
- features/step_definitions/fleets_steps.rb
- features/step_definitions/navigate_pages_steps.rb
- features/support/mock_fleet.rb
- spec/requests/uploads/processing_spec.rb
- spec/support/fleet_factory.rb
Jira card: https://eaflood.atlassian.net/browse/CAZ-2596
We need to hide "Make a payment" on the dashboard if the account has less than 2 vehicles. 
I've tried to register the new account and then added 1 and 2 vehicles. 
An account with one vehicle in the fleet:
> [CAZ-2596] Do not show 'Make a payment' unless the fleet has 2 or more vehicles

- app/controllers/application_controller.rb
The reason why it's happens:
```
class AddCurrentPayment < BaseManipulator
##
#
def call
session[:initiated_payment] = session[:new_payment]
session[:new_payment] = {}
end
end
```
We are clearing `new_payment` session when initiating a payment
> Fix `Back` link on the `Review your payment` page

- app/controllers/credit_cards_controller.rb
Error in `app/services/base_payment.rb`, we're clearing session because of https://eaflood.atlassian.net/browse/CAZ-2021
```
NoMethodError - private method `select' called for nil:NilClass:
app/services/base_payment.rb:27:in `transformed_transactions'
app/services/make_card_payment.rb:32:in `call'
app/services/base_service.rb:13:in `call'
app/controllers/credit_cards_controller.rb:14:in `initiate'
```
> Fix issue with second initiating the payment

- Gemfile
- Gemfile.lock
- app/controllers/payments_controller.rb
- app/controllers/uploads_controller.rb
- app/controllers/vehicles_controller.rb
- app/helpers/payments_helper.rb
- app/models/clean_air_zone.rb
- app/views/payments/review.html.haml
- app/views/vehicles/incorrect_details.html.haml
- app/views/vehicles/local_exemptions.html.haml
- config/locales/en.yml
- config/routes.rb
- features/debits.feature
- features/payments.feature
- features/step_definitions/payments_steps.rb
- features/step_definitions/uploads_step.rb
- features/step_definitions/vehicles_steps.rb
- features/uploads.feature
- features/vehicles.feature
- spec/models/clean_air_zones_spec.rb
- spec/requests/uploads/create_spec.rb
- spec/requests/uploads/processing_spec.rb
- spec/requests/vehicles/confirm_details_spec.rb
- spec/requests/vehicles/confirm_not_found_spec.rb
- spec/requests/vehicles/enter_details_spec.rb
- spec/requests/vehicles/local_exemptions_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2550
Redirect to a page that informs about local exemptions during add new vehicles via CSV or manually.
Manually, new RSpec and cucumber test added, existing fixed to reflect changes in the flow.
> [CAZ-2550] Not exempt declaration

- app/controllers/payments_controller.rb
- app/forms/payment_review_form.rb
- app/views/payments/review.html.haml
- spec/forms/payment_review_form_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2550
Add missing `error-summary-title` to the page
Manually, one new spec added.
> [CAZ-2550] Add missing 'error-summary-title'

- .drone.yml
- app/api_wrappers/compliance_checker_api.rb
- config/initializers/filter_parameter_logging.rb
https://eaflood.atlassian.net/browse/CAZ-2686
Add additional parameters to the `filtered_params`. Investigate logged things.
Manually, by trying each action in the system and watching the logs.
> [CAZ-2686] Remediate plate numbers being logged in service logs

- app/controllers/payments_controller.rb
- app/models/clean_air_zone.rb
- features/payments.feature
- features/step_definitions/fleets_steps.rb
- spec/fixtures/responses/caz_list_active.json
- spec/models/clean_air_zones_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZ-2707
Changed the scope of Clean Air Zones in select during the payment process to allow only to pay for the CAZ which is chargeable. 
Updated the `activeChargeStartDate` of Leeds CAZ
> [CAZ-2707] Do not display CAZ during payment when CAZ is not chargeable

- Gemfile
- Gemfile.lock
- app/helpers/payments_helper.rb
https://eaflood.atlassian.net/browse/CAZ-2576?focusedCommentId=214418
Link to city councils were without `open in new window` addnotation.
Manually
> [CAZ-2576] Make link to city councils an external one

- app/controllers/organisations_controller.rb
- app/services/session_manipulation/set_account_id.rb
- app/views/organisations/fleet_check.html.haml
- features/organisations.feature
- spec/requests/organisations/set_name_spec.rb
- spec/services/session_manipulation/set_account_id_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZ-2662
Updated the account creation process.
Added back button to the first step. 
**Given** the session does not have an account ID or a company name
**When** I submit the company name
**Then** I am shown the “Enter your sign in details” page
**Given** the session has an account ID and a company name
**When** I submit a new company name
**And** the company name is different from the previous name
**Then** I call the account creation endpoint with the new name
**Given** the session has an account ID and a company name
**When** I submit the same company name
**Then** I am shown the “Enter your sign in details” page
> [CAZ-2662] Allow to go back and change Company Name in Account creation

- app/api_wrappers/accounts_api.rb
- app/controllers/organisations_controller.rb
- features/organisations.feature
- features/step_definitions/organisations_steps.rb
- spec/api_wrappers/accounts_api/resend_verification_spec.rb
- spec/requests/organisations/resend_email_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZ-2801
Added support for new (not implemented yet) endpoint to resend verification email.
I commented out the request to don't call not implemented endpoint. 
We will uncomment it when https://eaflood.atlassian.net/browse/CAZ-2803 is ready.
Added Feature and Unit tests.
> [CAZ-2801] Add support for resend email link

- app/services/payment_dates.rb
- features/payments.feature
- spec/services/payment_dates_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2809
> [CAZ-2809] Show D-Day notice if charge start day is today too

- app/controllers/vehicles_controller.rb
- app/views/vehicles/exempt.html.haml
- config/routes.rb
- features/vehicles.feature
- spec/requests/vehicles/confirm_and_add_exempt_vehicle_to_fleet_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2867
* When a vehicle is marked as exempted one, we should not show local exemption page, we should continue the process which means we just need to perform request to add such vehicle.
* Add exempted VRN to fleet
* You should see global exemption page
* After clicking `Continue` vehicle should be added (without showing local exemption page).
N/A
> [CAZ-2867] Omit local exemption page for globally exempted vehicles

- app/forms/add_new_user_form.rb
- app/forms/add_new_user_permissions_form.rb
- app/forms/new_user_base_form.rb
- app/views/users/new.html.haml
https://eaflood.atlassian.net/browse/CAZ-2402?focusedCommentId=224469
Hardcode ordering of the errors in summary to reflect order of the form input
Manually.
> [CAZ-2402] Fix errors ordeing in error summary

- app/services/payment_dates.rb
- spec/services/payment_dates_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2208
Screenshot from 8 July (D-Day as 2 July):
Screenshot from 8 July (D-Day as 1 July):
> [CAZB-2208] Display "Came into operation" copy on D-Day + 6

- app/controllers/sessions_controller.rb
- app/javascript/packs/redirect_to_timeout_notice.js
- config/routes.rb
https://eaflood.atlassian.net/browse/CAZ-2342
* When a user is taken to the `logout_notice_page`, we perform POST request which stores the previous page in the session. Later this value is used to redirect the user back to where he was before the timeout.
* Log in
* Do not perform any action for 14 minutes
* You are redirected to the logout_notice_page.
* Click `Cookies` link on the page footer.
* Click `Back`
* Click `Continue`
* You should be redirected to the page on which you were before the timeout (and not to Cookies page).
N/A
> [CAZ-2342] Update back links behaviour during the timeout process

- .gitignore
- app/controllers/users_management/remove_users_controller.rb
- features/users_management/remove_user.feature
- spec/requests/users_management/remove_users/confirm_remove_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2144?focusedCommentId=228889
> [CAZB-2144] Redirect to the edit user page when was chosen `No`

- app/controllers/dashboard_controller.rb
- app/controllers/payment_history/payment_history_controller.rb
- app/services/back_link_history_service.rb
- features/payment_history.feature
- features/step_definitions/helper_steps.rb
- spec/services/back_link_history_service_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2166
1. Fixed bug when user refreshing page with url params `back=true`, we should not clear steps
2. Back button should redirect to previous url not path with page number in params
> [CAZB-2166] Fix back button on company and user history pages

- app/models/clean_air_zone.rb
- app/views/payments/payments/failure.html.haml
- app/views/vehicles_management/fleets/index.html.haml
- features/step_definitions/vehicles_management/fleets_steps.rb
- features/vehicles_management/fleets.feature
- spec/models/clean_air_zones_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-2580
Added CAZ status with info to Manage my vehicles page.
> [CAZB-2580] Display CAZ charge status on manage vehicle page

- app/controllers/passwords_controller.rb
- features/passwords/password_reset.feature
- features/step_definitions/password_reset_steps.rb
- spec/requests/passwords/create_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3115
Improved error handling to handle different 422 errors
Cucumber, rspec
> [CAZB-3115] Prevent password reuse on Reset Password flow

- app/controllers/payments/payments_controller.rb
- app/views/payments/payments/in_progress.html.haml
- spec/requests/payments/payments/in_progress_spec.rb
- spec/requests/payments/payments/matrix_spec.rb
- spec/support/chargeable_vehicles_factory.rb
https://eaflood.atlassian.net/browse/CAZB-3185
1. CAZ lock will be now released also on `payments_path`
2. Checking if CAZ is locked on `in_progress_payments_path`. If user refreshes the page and the CAZ lock is released, user is redirected to `matrix_payments_path`
3. User is no longer able to bypass CAZ lock by directly entering `/payments/matrix` url
Manually, rspec added
> [CAZB-3185] Payment Lock back link fix

- config/environments/development.rb
- config/environments/production.rb
When testing application on AWS sometimes users are experiencing strange redirects to homepage,
or are being asked to provide valid login details more than once in a row in order to be logged in.
Under closer inspection it has been revealed that there is a mismatch between CSRF token that is
sent by a user, and the one Rails have saved in session.
Potential mismatch may be caused by connectivity errors with Redis server. Since Rails fails silently
unsuccessful calls to `cache_store` we have needed to add explicit error statement to logs.
A rails error logger has been added to unsuccessful cache store operations.
> Add error logging when unable to connect to Redis

- config/environments/production.rb
Due to my mistake in https://github.com/InformedSolutions/JAQU-CAZ-Fleets-UI/pull/604 a Redis is no longer clustered in production resulting higher error rate when things are moved across shards preventing users to log in.
This changes Redis config to be clustered on production
> Change Redis config to be clustered in production

- app/forms/base_form.rb
- spec/forms/users_management/add_user_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3063
returned to regex, as Java Hibernate validator forbids two consecutive dots in email address, f.e. `this..isinvalidbecauseof2dots@test.com`
was done according to 
https://en.wikipedia.org/wiki/Email_address#Local-part
> CAZB-3063 Regex for email changed

- app/controllers/concerns/caz_lock.rb
- app/controllers/payments/payments_controller.rb
- app/views/payments/payments/in_progress.html.haml
- features/step_definitions/payments_steps.rb
- features/support/mock_users.rb
- spec/requests/payments/payments/in_progress_spec.rb
- spec/support/users_management/mocked_responses.rb
Jira issue: https://eaflood.atlassian.net/browse/CAZB-3186
Call api to get email of the user which locks CAZ for payment
Manually, test added and fixed
> [CAZB-3186] Read user email always from API

- app/api_wrappers/accounts_api.rb
- app/controllers/dashboard_controller.rb
- app/controllers/users_management/create_users_controller.rb
- app/controllers/users_management/users_controller.rb
- app/services/users_management/account_users.rb
- app/views/dashboard/index.html.haml
- features/dashboard/user_dashboard.feature
- features/step_definitions/dashboard_steps.rb
- features/step_definitions/debits_steps.rb
- features/step_definitions/payment_history_steps.rb
- features/step_definitions/vehicles_management/fleets_steps.rb
- features/step_definitions/vehicles_management/uploads_step.rb
- features/step_definitions/vehicles_management/vehicles_steps.rb
- features/support/mock_users.rb
- spec/api_wrappers/accounts_api/users_spec.rb
- spec/fixtures/responses/users_management/empty_users.json
- spec/fixtures/responses/users_management/users.json
- spec/requests/dashboard_spec.rb
- spec/requests/users_management/create_users/new_spec.rb
- spec/services/users_management/account_users_spec.rb
- spec/support/users_management/mocked_responses.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-2844
We need to hide the payments history from the dashboard if no payer user was assigned to the user. 
Used new attribute from the `/users/` endpoint 
Tested on two accounts: 
1. New account without any users
2. Account with users but without paying access
3. Account with users who can make payments.
> [CAZB-2844] Hide Company payment history if no payer user for the account

- app/controllers/passwords_controller.rb
- app/forms/update_password_form.rb
- app/forms/users_management/set_up_account_form.rb
- app/services/account_details/update_email.rb
- config/locales/en.yml
- features/account_details/emails.feature
- features/account_details/passwords.feature
- features/passwords/password_reset.feature
- features/passwords/password_update.feature
- features/users_management/account_set_up.feature
- spec/forms/update_password_form_spec.rb
- spec/forms/users_management/set_up_account_form_spec.rb
- spec/requests/account_details/passwords/update_spec.rb
- spec/requests/passwords/create_spec.rb
- spec/requests/passwords/update_spec.rb
- spec/requests/users_management/create_users/confirm_set_up_spec.rb
- spec/services/account_details/update_email_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2637
https://eaflood.atlassian.net/browse/CAZB-2865
> [CAZB-2669, CAZB-2637] Align error message for password complexity

- app/services/vehicles_management/upload_file.rb
- config/locales/en.yml
- features/step_definitions/vehicles_management/uploads_step.rb
- features/vehicles_management/uploads.feature
- spec/services/vehicles_management/upload_file_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3118
If an S3 exception contains string `Lambda timeout exception`, `CsvUploadException` is thrown with more user friendly error
Cucumber, rspec
> [CAZB-3118] Added CSV upload lambda timeout error

- app/controllers/direct_debits/debits_controller.rb
- spec/requests/direct_debits/debits/initiate_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3352
https://github.com/InformedSolutions/JAQU-CAZ-Payments-API/pull/381/files
> [CAZB-3352] Redirect to the failure page on duplicated dd payment

- app/javascript/packs/export_button_notice.js
- app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3163
Link will now be disabled after click for 5 seconds. After this time it will be enabled and `Your export is downloading...` message will be hidden
> [CAZB-3163] Disable CSV export link after click

- app/controllers/vehicles_management/uploads_controller.rb
- features/step_definitions/vehicles_management/uploads_step.rb
- features/vehicles_management/uploads.feature
- spec/requests/vehicles_management/uploads/processing_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3118
Reverted changes made to handle lambda timeout error.
Correct error message content will be set on backend.
> [CAZB-3118] Revert lambda timeout error handling

- app/forms/account_details/edit_user_email_form.rb
- config/locales/en.yml
- features/account_details/emails.feature
- features/step_definitions/account_details/emails_steps.rb
- spec/forms/account_details/edit_user_email_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3387
Added email and confirmation length validation
Manually, rspec, cucumber
> [CAZB-3387] Validate email length in Update Email flow

- app/controllers/account_details/emails_controller.rb
- app/views/account_details/emails/edit_email.html.haml
- config/routes.rb
- spec/requests/account_details/emails/update_email_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3387?focusedCommentId=249596
Previously form parameters were passed as query parameters. When user provided parameters long enough for the whole url to be more that 10240 characters, 414 error was thrown.
Changed `update_email` method from `get` to `post` - parameters are no longer passed through url
> [CAZB-3387] Fix Update Email 414 error

- config/environments/production.rb
Switch cache pragma heading to no-store to prevent stale page content being reloaded on the account management screen.
> [CAZB-3506] Switch cache pragma to no-store

- app/controllers/account_details/emails_controller.rb
- app/views/account_details/emails/edit_email.html.haml
- features/account_details/emails.feature
- features/step_definitions/account_details/emails_steps.rb
https://eaflood.atlassian.net/browse/CAZB-3387
> [CAZB-3387] Add `maxlength` attribute to email and confirmation fields

- config/locales/en.yml
Jira Car: https://eaflood.atlassian.net/browse/CAZB-3620
Updated text.
> [CAZB-3620] Displays 'Become' instead of 'Became' in the session timed out page

- app/views/vehicles_management/uploads/_job_errors.html.haml
Allow html content to job errors to supply links in error messages
> [CAZB-3505] Allow html content to job errors

- app/controllers/users_management/remove_users_controller.rb
- app/services/users_management/email_fetcher.rb
- app/services/users_management/is_direct_debit_creator.rb
- app/views/users_management/remove_users/remove.haml
- features/step_definitions/users_management/remove_user_steps.rb
- features/users_management/remove_user.feature
- spec/fixtures/responses/debits/mandates.json
- spec/requests/users_management/remove_users/remove_spec.rb
- spec/services/users_management/email_fetcher_spec.rb
- spec/services/users_management/is_direct_debit_creator_spec.rb
Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3689
* When removing a user from the Account, an API call is being performed in order to get mandates associated with the account. If a user who is being removed created any mandates, an additional warning is being displayed.
* Create an account owner and a user with direct debit mandates management permission.
* Create a mandate using the secondary user account
* Try to remove a secondary user using an account owner account
* When removing the secondary user, you should see a warning
> [CAZB-3689] Present warning when removing user who created mandates

- app/api_wrappers/debits_api.rb
- app/controllers/dashboard_controller.rb
- app/controllers/direct_debits/debits_controller.rb
- app/models/direct_debits/debit.rb
- app/views/dashboard/_direct_debit.html.haml
- app/views/dashboard/index.html.haml
- features/step_definitions/account_details/emails_steps.rb
- features/step_definitions/account_details/non_primary_user_steps.rb
- features/step_definitions/payment_history_steps.rb
- features/step_definitions/vehicles_management/fleets_steps.rb
- features/step_definitions/vehicles_management/uploads_step.rb
- features/step_definitions/vehicles_management/vehicles_steps.rb
- spec/requests/dashboard_controller_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4178
```
Edmond Chhung  2:49 PM
i found an issue with  https://eaflood.atlassian.net/browse/CAZB-4178
if you disable both CAZ's and the user isnt part of the beta group
the link is still there
```
Check if at leas one DD Caz is enabled.
Fixed loop if there zero active and invactive cazes on set_up page
> [CAZB-4178] Hide DD button if all DD CAZes are disabled

- app/controllers/vehicles_management/vehicles_controller.rb
- app/forms/vrn_form.rb
- features/step_definitions/vehicles_management/vehicles_steps.rb
- features/vehicles_management/vehicles.feature
- spec/forms/vrn_form_spec.rb
Update DVLA number plate regex validation and strip down leading zeros for UK number plates
Jira Cards: 
https://eaflood.atlassian.net/browse/CAZB-4299
https://eaflood.atlassian.net/browse/CAZB-4248
> [CAZB-4299|CAZB-4248] Update DVLA number plate regex validation

- app/views/relevant_portal/what_would_you_like_to_do.html.haml
https://eaflood.atlassian.net/browse/CAZB-4953
To abide by GDS patterns (see https://design-system.service.gov.uk/components/radios/error/index.html), the error summary position is being updated on the "What would you like to do?" triaging page. To support accessibility, the h1 in this instance is being converted to a styled field legend.
Error position updated and switched H1 to a style legend (for accessibility purposes) in the fieldset
Visual checks performed with HTML inspection on the fieldset construction
> [CAZB-4953] Update error positioning
