InformedSolutions/JAQU-CAZ-Fleets-UI

Gemfile, Gemfile.lock, app/forms/login_form.rb, spec/rails_helper.rb, spec/requests/sign_in_spec.rb, spec/support/shared_examples/invalid_login_param.rb, spec/support/string_count_helper.rb
=> [CAZ-1253] Add tests

app/controllers/sign_in_controller.rb
=> Remove sign in controller

app/controllers/passwords_controller.rb, app/views/devise/sessions/new.html.haml, app/views/passwords/new.html.haml, app/views/welcome/index.html.haml, config/locales/en.yml, config/routes.rb
https://eaflood.atlassian.net/browse/CAZ-1253
Added placeholder for a password reset and changed error messages to have `TBA`
=> [CAZ-1253] Add placeholder for password reset

config/locales/en.yml
=> [CAZ-1253] Fix locales

Gemfile, Gemfile.lock, app/controllers/organisations_controller.rb, app/helpers/application_helper.rb, app/services/create_account_service.rb, app/views/organisations/email_sent.html.haml, app/views/organisations/form_input/_errored.html.haml, app/views/organisations/form_input/_normal.html.haml, app/views/organisations/new_email_and_password.html.haml, app/views/organisations/new_name.html.haml, config/environments/test.rb, config/routes.rb, features/organisations.feature, features/step_definitions/organisations_steps.rb, spec/forms/company_name_form_spec.rb, spec/forms/email_and_password_form_spec.rb, spec/rails_helper.rb, spec/requests/organisations_controller/create_account_spec.rb, spec/requests/organisations_controller/create_name_spec.rb, spec/requests/organisations_controller/email_sent_spec.rb, spec/support/add_to_session.rb, spec/support/shared_examples/without_country_name_in_session.rb
=> [NT] Refactor and add tests

app/views/dashboard/_make_payment.html.haml, app/views/dashboard/_manage_users.html.haml, app/views/dashboard/_payment_history.html.haml, app/views/dashboard/_select_direct_debit.html.haml, app/views/dashboard/_upload.html.haml, app/views/dashboard/index.html.haml, app/views/organisations/new_name.html.haml, config/locales/en.yml, features/dashboard.feature
[JIRA](https://eaflood.atlassian.net/browse/CAZ-1262)
Manage users (only super admin)  that directs to manage-users page
Payment history (only super admin) directs to payment-history page
Upload your fleet (super and fleet admin) directs to csv-upload page
Make a payment (super and fleet admin) 
Create a direct debit mandate (super and fleet admin) directs to select-direct-debit page
admin dashboard
user dashboard
[CAZ-1219](https://eaflood.atlassian.net/browse/CAZ-1219)
=> [CAZ-1262] Update dashboard page and error messages

.env.example, app/api_wrappers/accounts_api.rb, app/services/create_account.rb, config/locales/en.yml, features/organisations.feature, features/step_definitions/organisations_steps.rb, features/support/helpers.rb, spec/fixtures/responses/create_account.json, spec/services/create_account_spec.rb, spec/support/helpers.rb
[JIRA](https://eaflood.atlassian.net/browse/CAZ-1564)
=> [CAZ-1564] Add connect to account create endpoint

config/locales/en.yml, features/organisations.feature
=> [NT] Fix typo

app/controllers/application_controller.rb, app/controllers/organisations_controller.rb, config/routes.rb, spec/requests/build_id_spec.rb, spec/requests/health_spec.rb, spec/requests/organisations_controller/email_verification_spec.rb
=> [NT] Add build_id and health endpoint

.env.example, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/views/devise/sessions/sign_out.html.haml, config/application.rb, config/routes.rb, features/sign_in.feature, features/step_definitions/sign_in_steps.rb, spec/requests/sign_out_spec.rb
[JIRA](https://eaflood.atlassian.net/browse/CAZ-1629)
=> [CAZ-1629] Add sign our page

app/controllers/organisations_controller.rb, app/services/sqs/verification_email.rb, app/views/layouts/_navbar.haml, app/views/organisations/email_sent.html.haml, app/views/organisations/new.html.haml, app/views/organisations/new_credentials.html.haml, config/routes.rb, features/step_definitions/organisations_steps.rb, spec/requests/organisations_controller/create_spec.rb, spec/requests/organisations_controller/email_sent_spec.rb, spec/requests/organisations_controller/email_verification_spec.rb, spec/requests/organisations_controller/email_verified_spec.rb, spec/requests/organisations_controller/new_credentials_spec.rb, spec/requests/organisations_controller/new_spec.rb, spec/requests/organisations_controller/resend_email_spec.rb, spec/requests/organisations_controller/set_name_spec.rb, spec/requests/organisations_controller/verification_failed_spec.rb
I changed organisation routes to be more RESTful
=> [NT] Change organisation routes

app/views/layouts/_navbar.haml, app/views/organisations/new.html.haml, app/views/users/manage.html.haml, config/locales/en.yml, features/users.feature
[JIRA](https://eaflood.atlassian.net/browse/CAZ-1285)
=> [CAZ-1285] Use same error message in error summary

app/services/sqs/verification_email.rb, spec/services/sqs/verification_email_spec.rb
=> [NT] Fix verification email

.drone.yml, .rubocop.yml, Gemfile, Gemfile.lock, app/api_wrappers/accounts_api.rb, app/controllers/application_controller.rb, app/models/fleet.rb, app/models/user.rb, app/models/vehicle.rb, spec/fixtures/responses/fleet.json, spec/models/fleet_spec.rb, spec/models/user_spec.rb, spec/models/vehicle_spec.rb, spec/rails_helper.rb, spec/support/fixtures_helpers.rb, spec/support/helpers.rb, yarn.lock
https://eaflood.atlassian.net/browse/CAZ-1641 
Added Fleet and Vehicle models with some mocked API calls. 
This can be used for fleet management pages
=> [CAZ-1641] Add fleet model

app/api_wrappers/accounts_api.rb, app/views/layouts/_navbar.haml
For now, the endpoint returns invalid, hardcoded email.
=> [NT] Fix account creation for dummy endpoint

Dockerfile.test
=> [NT] Add yarn.lock to Gemfile

.drone.yml, Dockerfile.build, Dockerfile.test, app/api_wrappers/accounts_api.rb, app/api_wrappers/base_api.rb, app/controllers/application_controller.rb, app/models/user.rb, app/services/create_account.rb, config/locales/en.yml, features/dashboard.feature, features/sign_in.feature, features/step_definitions/helper_steps.rb, features/step_definitions/sign_in_steps.rb, features/support/sign_in_helper.rb, lib/devise/models/remote_authenticatable.rb, lib/devise/strategies/remote.rb, spec/rails_helper.rb, spec/requests/dashboard_controller_spec.rb, spec/requests/sign_in_spec.rb, spec/support/user_factory.rb
=> CAZ-1616 - Add checking login ip

app/controllers/fleets_controller.rb, app/controllers/users_controller.rb, app/forms/submission_method_form.rb, app/views/dashboard/_make_payment.html.haml, app/views/dashboard/_upload.html.haml, app/views/fleets/enter_details.html.haml, app/views/fleets/index.html.haml, app/views/fleets/submission_method.html.haml, app/views/fleets/upload.html.haml, app/views/users/first_upload.html.haml, config/routes.rb, features/dashboard.feature, features/fleets.feature, features/step_definitions/fleets_steps.rb, features/support/mock_fleet.rb, spec/forms/submission_method_form_spec.rb, spec/rails_helper.rb, spec/requests/fleets/enter_details_spec.rb, spec/requests/fleets/index_spec.rb, spec/requests/fleets/submission_method_spec.rb, spec/requests/fleets/submit_method_spec.rb, spec/requests/fleets/upload_spec.rb, spec/support/fleet_factory.rb, spec/support/shared_examples/login_required_view.rb
https://eaflood.atlassian.net/browse/CAZ-1636
=> [CAZ-1636] Add submission method page

app/models/vehicle.rb, spec/models/vehicle_spec.rb
=> [NT] Fix formatted charge parsing

.rubocop.yml, app/controllers/fleets_controller.rb, app/controllers/vehicles_controller.rb, app/forms/vrn_form.rb, app/javascript/styles/application.scss, app/views/fleets/add_vehicle.html.haml, app/views/vehicles/confirm_details.html.haml, app/views/vehicles/enter_details.html.haml, app/views/vehicles/vrn_input/_errored.haml, app/views/vehicles/vrn_input/_normal.haml, config/locales/en.yml, config/routes.rb, features/fleets.feature, features/step_definitions/fleets_steps.rb, features/step_definitions/helper_steps.rb, features/step_definitions/vehicles_steps.rb, features/vehicles.feature, spec/forms/vrn_form_spec.rb, spec/requests/fleets/create_spec.rb, spec/requests/fleets/enter_details_spec.rb, spec/requests/fleets/submit_method_spec.rb, spec/requests/vehicles/confirm_details_spec.rb, spec/requests/vehicles/enter_details_spec.rb, spec/requests/vehicles/submit_details_spec.rb, spec/support/shared_examples/invalid_vrn_form.rb, yarn.lock
https://eaflood.atlassian.net/browse/CAZ-1637
=> [CAZ-1637] Add enter details page

app/api_wrappers/accounts_api.rb, app/api_wrappers/base_api.rb, app/api_wrappers/compliance_checker_api.rb, app/api_wrappers/fleets_api.rb, app/models/fleet.rb, spec/models/fleet_spec.rb, spec/requests/vehicles/confirm_details_spec.rb
I moved fleet-related methods to the new wrapper as AccountsApi will get bigger and bigger.
Rdoc for methods will be added later
=> [NT] Refactor accountsApi wrapper

app/api_wrappers/accounts_api.rb, app/api_wrappers/base_api.rb, app/api_wrappers/fleets_api.rb, config/initializers/content_security_policy.rb, lib/devise/strategies/remote.rb, spec/api_wrappers/accounts_api/create_account_spec.rb, spec/api_wrappers/accounts_api/sign_in_spec.rb, spec/api_wrappers/accounts_api/verify_user_spec.rb, spec/fixtures/responses/user.json
https://eaflood.atlassian.net/browse/CAZ-1630
Added integration with endpoint, but left workaround for dev
=> [CAZ-1630] Connect to login endpoint

app/views/fleets/first_upload.html.haml, app/views/fleets/index.html.haml, app/views/fleets/reupload.html.haml, app/views/fleets/upload.html.haml, app/views/fleets/upload/_description.html.haml, app/views/organisations/form_input/_errored.html.haml, app/views/organisations/form_input/_normal.html.haml, app/views/organisations/new.html.haml, app/views/organisations/new_credentials.html.haml, app/views/users/manage.html.haml, app/views/users/new.html.haml, config/locales/en.yml, features/organisations.feature, features/users.feature
https://eaflood.atlassian.net/browse/CAZ-1623
See comment section in Jira
=> [CAZ-1623] Change content

app/api_wrappers/fleets_api.rb, app/controllers/application_controller.rb, app/controllers/fleets_controller.rb, app/controllers/vehicles_controller.rb, app/models/fleet.rb, app/views/fleets/delete.html.haml, app/views/fleets/index.html.haml, config/routes.rb, features/fleets.feature, features/step_definitions/fleets_steps.rb, features/step_definitions/helper_steps.rb, features/support/mock_fleet.rb, spec/requests/fleets/assign_delete_spec.rb, spec/requests/fleets/confirm_delete_spec.rb, spec/requests/fleets/delete_spec.rb, spec/requests/vehicles/confirm_details_spec.rb, spec/requests/vehicles/details_spec.rb, spec/requests/vehicles/enter_details_spec.rb, spec/requests/vehicles/exempt_spec.rb, spec/requests/vehicles/incorrect_details_spec.rb, spec/requests/vehicles/not_found_spec.rb, spec/support/fleet_factory.rb, spec/support/shared_examples/vrn_required_view.rb
https://eaflood.atlassian.net/browse/CAZ-1731
=> [CAZ-1731] Add removing vehicles

app/api_wrappers/accounts_api.rb, app/api_wrappers/base_api.rb, app/services/create_account.rb, features/organisations.feature, features/step_definitions/organisations_steps.rb, spec/services/create_account_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1678
=> [CAZ-1678] Change error code, remove mocks and move logging response

app/views/fleets/index.html.haml, app/views/users/manage.html.haml
https://eaflood.atlassian.net/browse/CAZ-1623
https://eaflood.atlassian.net/browse/CAZ-1732
=> [CAZ-1623] [CAZ-1732] Add more content changes

.drone.yml, app/api_wrappers/debits_api.rb, app/models/mandate.rb
=> [CAZ-1739] Add safe checks

.drone.yml
Add initial SIT deployment pipeline for SIT fleets layer
=> Add initial SIT pipeline to drone file

config/locales/en.yml, features/debits.feature, features/step_definitions/helper_steps.rb, features/uploads.feature, features/vehicles.feature
https://eaflood.atlassian.net/browse/CAZ-1637
=> [Fix] [CAZ-1637] Fix errors in vrn_form

app/views/users/manage.html.haml
https://eaflood.atlassian.net/browse/CAZ-1623
Removed "fleet" from question below the table:
=> [Fix] [CAZ-1623] Fix content in users#manage

.env.test, Dockerfile.test, app/services/encryption/base.rb, app/services/upload_file.rb, config/initializers/amazon_s3_client.rb
=> [Fix] [NT] Fix builds

.github/PULL_REQUEST_TEMPLATE, app/controllers/uploads_controller.rb, app/views/uploads/_description.html.haml, config/locales/en.yml, config/routes.rb, features/step_definitions/uploads_step.rb, features/uploads.feature, public/template.csv, spec/requests/uploads/download_template_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1734
=> [CAZ-1734] Add downloading CSV template

app/api_wrappers/debits_api.rb, app/api_wrappers/fleets_api.rb
Debits and Fleet API were using same key.
Also, added some logs to make debugging easier.
=> [Fix] [NT] Fix debits_api.rb and add logs

app/views/layouts/_cookies_banner.haml, spec/requests/uploads/download_template_spec.rb
=> [NT] Fix cookie banner and rspec test

.drone.yml
=> Implemented end to end test run on drone DEV build

.drone.yml
=> Add ST fleets pipeline

config/environments/production.rb
https://stackoverflow.com/questions/55725529/how-to-set-up-aws-elasticache-cluster-in-rails-problem-with-the-moved-response
=> [Fix] [CAZ-1834] Change redis store to use cluster

config/environments/production.rb
Update ST with redis cluster fix
=> [Fix] [CAZ-1834] Change redis store to use cluster (#73)

.drone.yml
Add code deploy ST steps to drone pipeline
=> Add drone steps for ST code deploy

app/controllers/fleets_controller.rb, app/helpers/fleets_helper.rb, app/views/fleets/index.html.haml, features/step_definitions/fleets_steps.rb, features/step_definitions/vehicles_steps.rb, features/support/mock_vccs.rb, spec/rails_helper.rb, spec/requests/fleets/index_spec.rb, spec/support/mock_caz_list.rb
https://eaflood.atlassian.net/browse/CAZ-1968
=> [CAZ-1968] Fetch CAZs on the fleet page

Gemfile, Gemfile.lock, app/api_wrappers/fleets_api.rb, app/controllers/fleets_controller.rb, app/javascript/styles/application.scss, app/javascript/styles/pagination.scss, app/views/fleets/_pagination.html.haml, app/views/fleets/_pagination_button.html.haml, app/views/fleets/index.html.haml, config/initializers/session_store.rb, features/fleets.feature, features/step_definitions/fleets_steps.rb, spec/fixtures/responses/fleet.json, spec/rails_helper.rb, spec/requests/fleets/index_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1970
Added pagination component based on GOV.UK Pay
=> [CAZ-1970] Add pagination component

.drone.yml
=> Remove unnecessary `build-arg` from drone.yml

app/api_wrappers/fleets_api.rb, app/controllers/fleets_controller.rb, app/controllers/payments_controller.rb, app/controllers/uploads_controller.rb, app/controllers/vehicles_controller.rb, app/models/fleet.rb, app/models/vehicle.rb, app/views/fleets/_pagination.html.haml, app/views/fleets/index.html.haml, features/fleets.feature, features/step_definitions/fleets_steps.rb, features/support/mock_fleet.rb, spec/fixtures/responses/fleet.json, spec/models/fleet_spec.rb, spec/models/vehicle_spec.rb, spec/requests/fleets/index_spec.rb, spec/requests/payments/index_spec.rb, spec/requests/vehicles/confirm_details_spec.rb, spec/support/fleet_factory.rb
I change the mocked fleet data structure to match the one from https://eaflood.atlassian.net/browse/CAZ-1971
I added the new method `.empty?` to the fleet model to check if there are any vehicles associated with the account more efficient.
=> [NT] Change fleet structure

.env.example, config/environments/production.rb, config/initializers/content_security_policy.rb
https://eaflood.atlassian.net/browse/CAZ-1955
=> [CAZ-1955] Add Cloudfront integration

.drone.yml
=> added e to e

app/api_wrappers/accounts_api.rb, spec/api_wrappers/accounts_api/create_account_spec.rb, spec/api_wrappers/accounts_api/sign_in_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2070
=> [CAZ-2070] Downcase login

app/javascript/styles/application.scss, app/javascript/styles/cookie_control.scss, app/views/layouts/_cookie_control.html.erb, config/initializers/content_security_policy.rb
[JIRA](https://eaflood.atlassian.net/browse/CAZB-474)
Read parent story comments.
=> [CAZB-650] Update cookie control design

.env.test, app/api_wrappers/base_api.rb, app/api_wrappers/fleets_api.rb, app/controllers/uploads_controller.rb, app/services/upload_file.rb, app/views/uploads/processing.html.haml, config/routes.rb, features/step_definitions/helper_steps.rb, features/step_definitions/uploads_step.rb, features/support/env.rb, features/uploads.feature, spec/api_wrappers/fleets_api/job_status_spec.rb, spec/api_wrappers/fleets_api/register_job_spec.rb, spec/requests/uploads/create_spec.rb, spec/requests/uploads/processing_spec.rb
https://eaflood.atlassian.net/browse/CAZ-1960
https://eaflood.atlassian.net/browse/CAZ-1961
https://eaflood.atlassian.net/browse/CAZ-1962
=> [CAZ-1960] [CAZ-1961] [CAZ-1962] Connect to upload CSV backend

app/api_wrappers/fleets_api.rb, app/services/upload_file.rb, spec/services/upload_file_spec.rb
=> [NT] Removed mocked base uri

app/controllers/payments_controller.rb, app/helpers/payments_helper.rb, app/views/payments/index.html.haml, app/views/payments/matrix.html.haml, config/routes.rb, features/payments.feature, features/step_definitions/payments_steps.rb, spec/requests/payments/index_spec.rb, spec/requests/payments/local_authority_spec.rb, spec/requests/payments/matrix_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2041
=> [CAZ-2041] Add selecting LA

app/javascript/styles/application.scss, config/initializers/content_security_policy.rb
=> [CAZB-560] Update cookies control csp

app/api_wrappers/api_exception.rb, app/api_wrappers/fleets_api.rb, app/controllers/vehicles_controller.rb, app/models/fleet.rb, app/views/vehicles/exempt.html.haml, app/views/vehicles/vrn_input/_errored.haml, features/step_definitions/vehicles_steps.rb, features/vehicles.feature, spec/api_wrappers/fleets_api/add_vehicle_to_fleet_spec.rb, spec/models/fleet_spec.rb, spec/requests/vehicles/confirm_details_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2075
Connected to the endpoint. The current version of the exempt page is under discussion
=> [CAZ-2075] Add vehicle to fleet integration

app/api_wrappers/fleets_api.rb, app/models/fleet.rb, app/views/vehicles/exempt.html.haml, config/initializers/content_security_policy.rb, config/initializers/filter_parameter_logging.rb, spec/api_wrappers/fleets_api/add_vehicle_to_fleet_spec.rb, spec/api_wrappers/fleets_api/remove_vehicle_from_fleet_spec.rb, spec/models/fleet_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2076
https://app.swaggerhub.com/apis/jaquapi/JAQU-CAZ-Contract/1.17.4#/Accounts/removeVehicleFromFleetDELETE
=> [CAZ-2076] Remove vehicle from fleet integration

app/api_wrappers/accounts_api.rb, spec/api_wrappers/accounts_api/initiate_password_reset_spec.rb, spec/api_wrappers/accounts_api/set_password_spec.rb, spec/api_wrappers/accounts_api/validate_password_reset_spec.rb
https://app.swaggerhub.com/apis/jaquapi/JAQU-CAZ-Contract/1.18.0
=> [CAZ-2048] Add password reset wrappers

.env.development
=> [NT] Remove .env.development

app/api_wrappers/base_api.rb, app/controllers/passwords_controller.rb, app/forms/new_password_form.rb, app/forms/token_form.rb, app/views/common/_errors_summary.html.haml, app/views/passwords/_password_input.html.haml, app/views/passwords/email_sent.html.haml, app/views/passwords/index.html.haml, app/views/passwords/invalid.html.haml, app/views/passwords/reset.html.haml, app/views/passwords/success.html.haml, config/locales/en.yml, config/routes.rb, features/password_reset.feature, features/step_definitions/password_reset_steps.rb, spec/forms/new_password_form_spec.rb, spec/forms/token_form_spec.rb, spec/requests/passwords/create_spec.rb, spec/requests/passwords/email_sent_spec.rb, spec/requests/passwords/index_spec.rb, spec/requests/passwords/invalid_spec.rb, spec/requests/passwords/success_spec.rb, spec/requests/passwords/validate_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2027
https://eaflood.atlassian.net/browse/CAZ-2031
https://eaflood.atlassian.net/browse/CAZ-2032
=> [CAZ-2027] [CAZ-2031] [CAZ-2032] Reset password integration

app/api_wrappers/compliance_checker_api.rb, spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb, spec/api_wrappers/compliance_checker_api/vehicle_details_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2041
Refactored `ComplianceCheckerApi` class to point to Payments API
=> [CAZ-2041] Change VCCS endpoints to Payments

app/api_wrappers/accounts_api.rb, app/services/sqs/base.rb, spec/api_wrappers/accounts_api/initiate_password_reset_spec.rb
Added downcasing email during the password reset process. 
Also, removed some logs form SQS message, as they log email addresses.
=> [NT] Downcase email and remove sensitive logs

app/services/sqs/base.rb
Readded due to emails not being sent on the DEV env - users need to click the link.
=> [NT] Re-add logs to SQS due to missing verification link on DEV env

app/controllers/fleets_controller.rb, spec/requests/fleets/confirm_delete_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2104
=> [CAZ-2104] Return to dashboard after last vehicle removal

app/controllers/payments_controller.rb, app/helpers/payments_helper.rb, app/services/session_manipulation/add_la_id.rb, app/services/session_manipulation/add_payment_details.rb, app/services/session_manipulation/add_query_details.rb, app/services/session_manipulation/base_manipulator.rb, spec/services/session_manipulation/add_la_id_spec.rb, spec/services/session_manipulation/add_payment_details_spec.rb, spec/services/session_manipulation/add_query_details_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2023
Moved logic to dedicated services.
=> [CAZ-2023] Improve payment session management

.drone.yml
=> [CAZ-2055] Drone changes for Fleets UI prod environment

app/services/session_manipulation/add_la_id.rb, spec/services/session_manipulation/add_la_id_spec.rb
It will now return to the first page on the pagination page
=> [NT] [Bug] Clear query on LA select

config/application.rb, config/environments/production.rb, config/log_format.rb
=> [CAZSM-9] Removal of ip addresses from application logs

config/application.rb, config/environments/production.rb, config/log_format.rb
=> removed ip logging (#114)

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/static_pages_controller.rb, app/helpers/application_helper.rb, app/views/layouts/_cookie_control.html.erb, app/views/layouts/_footer.html.haml, app/views/static_pages/cookies.html.haml, app/views/static_pages/cookies/_cookie_control.html.haml, app/views/static_pages/cookies/_ga.html.haml, app/views/static_pages/cookies/_session.html.haml, app/views/static_pages/cookies/_table_head.html.haml, config/initializers/session_store.rb, config/routes.rb, features/static_pages.feature, features/step_definitions/sign_in_steps.rb, features/step_definitions/static_pages_steps.rb, package.json, sonar-project.properties, spec/requests/static_pages_spec.rb, spec/support/shared_examples/static_page.rb, yarn.lock
[JIRA](https://eaflood.atlassian.net/browse/CAZB-642)
=> [CAZB-642] Update cookie control content and cookie page

app/views/passwords/invalid.html.haml
=> [NT] Fix typo on password reset page

app/views/layouts/_cookie_control.html.erb
https://eaflood.atlassian.net/browse/CAZ-2122
=> [CAZ-2122] Hide Control Cookie buttons and add `Save and close` button

app/services/session_manipulation/add_payment_details.rb
QA found a bug when pressing the next page on the payment matrix with no vehicles to pay selected. 
Added try to avoid server error while getting params.
Added more than 10 vehicles to the account and tried to use the payment matrix.
=> [NON JIRA] Fixes bug while getting next page with no vehicles selected

.drone.yml
=> Added nightly drone steps

.drone.yml
Add yarn exclusion to fleets to mirror changes under https://github.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/pull/389
=> Add yarn exclusion to fleets

app/views/dashboard/user_dashboard.html.haml, app/views/organisations/new.html.haml, app/views/organisations/new_credentials.html.haml, app/views/organisations/verification_failed.html.haml, app/views/passwords/email_sent.html.haml, app/views/passwords/index.html.haml, app/views/passwords/invalid.html.haml, app/views/passwords/reset.html.haml, app/views/vehicles/details.html.haml, config/locales/en.yml, features/debits.feature, features/fleets.feature, features/organisations.feature, features/password_reset.feature, features/payments.feature, features/sign_in.feature, features/vehicles.feature, spec/forms/confirmation_form_spec.rb
Removes TBA error messages and draft content banners across the Fleets service.
=> [CAZ-2112] Remove TBA error messages and draft badges

config/environments/production.rb
=> Remove require `logstash-logger` from production.rb

app/controllers/payments_controller.rb, app/views/payments/review.html.haml, app/views/payments/review_details.html.haml, config/routes.rb, features/payments.feature, features/step_definitions/payments_steps.rb
Jira card: https://eaflood.atlassian.net/browse/CAZ-2042
We need to display selected payment details on the confirmation page.
Added views for confirmation page and details page with selected dates for account vehicles. 
Tried to process payment using UI
=> [CAZ-2042] Confirm Payment with details page

.drone.yml
Update survey link to newly provided URL
=> Update survey link to newly provided URL

app/controllers/static_pages_controller.rb, app/views/layouts/_footer.html.haml, app/views/static_pages/accessibility_statement.html.haml, config/routes.rb, features/static_pages.feature, features/step_definitions/static_pages_steps.rb, spec/requests/static_pages_spec.rb
Add accessibility page to Fleets service based on Payments IOD copy.
=> [CAZ-2146] Add accessibility page to Fleets service

app/helpers/application_helper.rb, app/models/vehicle.rb, app/views/fleets/index.html.haml, config/application.rb, config/environments/test.rb, spec/models/vehicle_spec.rb
Update vehicle management page with latest copy. Copy has been inspected locally and unit tests/integration tests executed.
=> [CAZ-2141] Update vehicle management page with latest copy

app/api_wrappers/payments_api.rb, app/controllers/payments_controller.rb, app/services/make_payment.rb, features/payments.feature, features/step_definitions/payments_steps.rb, spec/api_wrappers/payments_api/create_payment_spec.rb, spec/services/make_payment_spec.rb, yarn.lock
[Link to CAZ-2022 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2022)
N/A
=> [CAZ-2022] Initiate Payment Journey - make an API call to create payment

app/forms/base_form.rb, app/views/passwords/reset.html.haml, spec/models/reset_password_form_spec.rb
[JIRA](https://eaflood.atlassian.net/browse/CAZ-2149)
I also added a value to email input so user can see an invalid email address
=> [CAZ-2149] Update email regex

app/views/fleets/index.html.haml
Minor update to vehicle management page copy in response to feedback from PO.
=> Minor copy update on vehicle management

app/forms/email_and_password_form.rb, features/organisations.feature, features/password_reset.feature, features/step_definitions/password_reset_steps.rb
https://eaflood.atlassian.net/browse/CAZ-2150
------------------------------------------
=> [CAZ-2150] Fix duplicate error message on account registration

.drone.yml
Update release with drone file corrections
=> Update release with drone file corrections

.drone.yml, app/views/organisations/new.html.haml
Promote drone fixes and error message correction to ST
=> Promote drone fixes and error message correction to ST

.drone.yml, app/views/organisations/new.html.haml
* Correct SIT codedeploy pointer in drone file
* Further correction to SIT pointer
* Drone file corrections
* Drone file corrections for codedeploy
* Update production URL for defra domain
* Directory correction in drone file
* Update new.html.haml (#145)
Remove tba from company name error
=> Promote drone fixes and error message correction to SIT

app/models/chargeable_fleet.rb, app/views/payments/matrix/_next_week_tab.html.haml, app/views/payments/matrix/_past_week_tab.html.haml, features/payments.feature, features/step_definitions/fleets_steps.rb, features/step_definitions/payments_steps.rb, features/support/mock_fleet.rb, spec/fixtures/responses/chargeable_vehicles_with_unpaid_dates.json, spec/models/chargeable_fleet_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2139
--------------------------------
=> [CAZ-2139] Dynamic content on the matrix page

.drone.yml
Drone file corrections for preprod and prod steps
=> Drone file corrections

app/api_wrappers/payments_api.rb, app/controllers/payments_controller.rb, app/helpers/application_helper.rb, app/javascript/packs/application.js, app/javascript/src/printLink/init.js, app/models/payment_details.rb, app/models/payment_status.rb, app/services/make_payment.rb, app/services/session_manipulation/set_payment_details.rb, app/services/session_manipulation/set_payment_details_spec.rb, app/services/session_manipulation/set_payment_id.rb, app/views/common/_print_link.haml, app/views/payments/failure.html.haml, app/views/payments/success.html.haml, config/routes.rb, features/password_reset.feature, features/payments.feature, features/step_definitions/payments_steps.rb, features/support/mock_payments.rb, spec/api_wrappers/payments_api/payment_status_spec.rb, spec/fixtures/responses/payment_status.json, spec/models/payment_details_spec.rb, spec/models/payment_status_spec.rb, spec/services/make_payment_spec.rb, spec/services/session_manipulation/set_payment_id_spec.rb
[CAZ-2043 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2043)
Implemented flow:
* After confirming payment data, a request is sent to Payments API.
* Response coming from Payments API returns URL on which user should be redirected.
* Redirection is going to an action that performs another call to Payments API in order to get payments data.
* When payment is successfully processed - redirection is made to success result page.
* Else -> redirection is made to failure page.
* RSpec + cucumber test suites
* Manually
----
=> [CAZ-2043] Payment status screen

spec/services/session_manipulation/set_payment_details_spec.rb
=> [CAZ-2043] Move spec to proper directory

.drone.yml
=> CAZ-2143 Feature/caz 2143/refresh prod deployment

app/controllers/payments_controller.rb, app/helpers/payments_helper.rb, app/javascript/packs/application.js, app/javascript/src/printLink/init.js, app/javascript/src/printLink/styles.scss, app/views/common/_print_link.haml, app/views/payments/_payment_details.html.haml, app/views/payments/post_payment_details.html.haml, app/views/payments/success.html.haml, config/routes.rb, features/payments.feature, features/step_definitions/payments_steps.rb
[CAZ-2044 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2044)
* Added link to details page on the payment success page.
* Adjusted code responsible for printing page.
* Cucumber 
* Manually
=> [CAZ-2044] Payment Status Confirmation - Details page

app/controllers/payments_controller.rb, app/helpers/payments_helper.rb, app/javascript/packs/application.js, app/javascript/src/printLink/init.js, app/javascript/src/printLink/styles.scss, app/views/common/_print_link.haml, app/views/payments/_payment_details.html.haml, app/views/payments/post_payment_details.html.haml, app/views/payments/success.html.haml, config/routes.rb, features/payments.feature, features/step_definitions/payments_steps.rb
Update ST with Payment Status Confirmation - Details page
=> Update ST with Payment Status Confirmation - Details page

app/views/uploads/processing.html.haml
Alter text on validating submission page
=> [CAZ-2156] Alter text on validating submission page

app/javascript/packs/payment_matrix.js, app/javascript/src/payment_matrix/emptyMatrixContinuePrevention.js, app/javascript/src/payment_matrix/initPaginationButton.js, app/views/payments/matrix.html.haml
It was possible to submit form without selecting any date. The provided JS script disabled the `Continue` button when no date is selected.
Manually.
=> [NT] Prevent from submitting payment with empty dates

additional_urls.yaml, app/helpers/payments_helper.rb, app/views/payments/success.html.haml
[Link to CAZ-2153 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2153)
* Updated section on the payment success page.
- Manually.
----
=> [CAZ-2153] Payment Complete - City Council links

app/helpers/payments_helper.rb, app/views/payments/review.html.haml
[Link to CAZ-2044 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2044)
Updated the precision of the charge.
Manually.
=> [CAZ-2044] Charge precision update

app/javascript/styles/application.scss, app/views/fleets/index.html.haml
Minor CSS formatting on manage vehicles page for sizing of table columns.
=> Minor CSS formatting on manage vehicles page

app/javascript/styles/application.scss, app/views/fleets/index.html.haml
Update positioning of columns in vehicle management matrix to balance them across the page. Also adds a hidden "Actions" title to the remove row for non-visual users.
=> CSS and accessibility update

app/views/payments/success.html.haml
Small typo correction following testing feedback on CAZ-2153.
=> [CAZ-2153] Small typo correction

app/api_wrappers/payments_api.rb, app/controllers/payments_controller.rb, app/javascript/src/payment_matrix/initSearch.js, app/models/chargeable_fleet.rb, app/models/fleet.rb, app/models/user.rb, app/services/session_manipulation/clear_vrn_search.rb, app/views/payments/matrix.html.haml, app/views/payments/matrix/_errors.html.haml, app/views/payments/matrix/_headling.html.haml, app/views/payments/matrix/_no_chnargeable_vehicles.html.haml, app/views/payments/matrix/_search.html.haml, app/views/payments/matrix/vrn_input/_errored.html.haml, app/views/payments/matrix/vrn_input/_normal.html.haml, config/routes.rb, spec/api_wrappers/payments_api/chargeable_vehicle_spec.rb, spec/api_wrappers/payments_api/chargeable_vehicles_spec.rb, spec/fixtures/responses/chargeable_vehicle.json, spec/models/chargeable_fleet_spec.rb, spec/models/fleet_spec.rb, spec/requests/payments/clear_search_spec.rb, spec/services/session_manipulation/clear_vrn_search_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZ-2016
Users need to be able to search VRN on the payment matrix. 
Added support for full VRN search on the payment matrix. 
Tried to use the search on payment matrix (with validations check)
=> [CAZ-2016] VRN search on payment matrix

app/api_wrappers/payments_api.rb, app/controllers/payments_controller.rb, app/javascript/src/payment_matrix/createHiddenInput.js, app/views/payments/matrix/_no_chnargeable_vehicles.html.haml
Fixes case-sensitivity of search. Note that the fix in this instance uses Javascript. It feels that the upper-casing should also be done server-side for completeness (@dratka @likeuwill - if you could take a look that would be great 👍). 
There has also been a minor copy update on the VRN not found scenario.
=> [CAZ-2016] Case sensitivity fix for search

.drone.yml, app/views/fleets/submission_method.html.haml, app/views/payments/matrix.html.haml, app/views/payments/matrix/_headling.html.haml, app/views/payments/matrix/_no_chnargeable_vehicles.html.haml, app/views/payments/matrix/_search.html.haml
Update to view logic for when continue buttons are shown on the payment matrix and conditional copy.
=> Update view presentation logic based on PO feedback

app/views/payments/_payment_details.html.haml, app/views/payments/matrix/_table.html.haml, app/views/vehicles/enter_details.html.haml, config/locales/en.yml, features/vehicles.feature
Update references to registration number such that they read "number plate"
=> Update references to registration number

.drone.yml, app/services/session_manipulation/add_query_details.rb
Fixes Payment Matrix pagination issue.
=> [NonJIRA] Fixes payment matrix pagination

app/javascript/src/payment_matrix/emptyMatrixContinuePrevention.js, app/views/payments/matrix/_search.html.haml
=> [NonJIRA] Fixes payment matrix servch after empty results / Fixes reset search

app/views/dashboard/_manage_vehicles.html.haml, app/views/uploads/_description.html.haml, app/views/uploads/_reupload.html.haml, app/views/uploads/_upload.html.haml, features/uploads.feature, public/template.csv
=> Update copy after PO review

app/helpers/payments_helper.rb, app/javascript/src/payment_matrix/emptyMatrixContinuePrevention.js, app/views/payments/matrix.html.haml
Fixes disabled continue button on payment matrix.
=> [CAZ-2010] Fixes disabled Continue button

app/views/fleets/delete.html.haml
Minor copy update to remove registration term on vehicle removal page.
=> Minor copy update

app/views/fleets/delete.html.haml
* Minor revision following discussion with PO
=> Minor copy update (#173)

app/javascript/packs/autorefresh_page.js
Jira card: https://eaflood.atlassian.net/browse/CAZ-2265
Updated JS which refresh the page on Processing page. 
I tried to upload CSV file on cold backend lambda.
=> [CAZ-2265] Fix redirect issue from Processing page on cold Lambda

app/api_wrappers/debits_api.rb, app/api_wrappers/debits_api_responses.rb
https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logEventViewer:group=/aws/ecs/fleet/dev;stream=/aws/ecs/fleet-web/f3b5c9fd-525b-4835-8ed1-97597f6b2cc6;start=PT30S
We can't use `File.read` method in production mode. So i moved all responses to module methods.
=> Use temporary mocked responses from `DebitsApiResponses` module

app/controllers/debits_controller.rb, app/models/direct_debit.rb, features/step_definitions/debits_steps.rb, spec/requests/debits/first_mandate_spec.rb, spec/support/mocked_responses.rb
https://eaflood.atlassian.net/browse/CAZ-2167
=> [CAZ-2167] Allow to pay with mandate in `pending` status

app/views/fleets/index.html.haml, app/views/organisations/new.html.haml, spec/api_wrappers/debits_api/create_mandate_spec.rb, spec/api_wrappers/debits_api/mandates_spec.rb, spec/requests/credit_cards/result_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2299
=> [CAZ-2299] Link capitalisation on Vehicle Management page

app/views/devise/sessions/sign_out.html.haml, features/sign_in.feature
[Link to CAZ-2295 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2295)
* Updated typo
* Updated specs.
=> [CAZ-2295] Sign out page content update

app/javascript/packs/payment_matrix.js, package.json, yarn.lock
https://eaflood.atlassian.net/browse/CAZ-2268
[How to add support url](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelpolyfill)
In IE 11 Windows 10
=> [CAZ-2268] Add compatibility between IE and babel javascript

app/views/debits/index.html.haml
https://eaflood.atlassian.net/browse/CAZ-2166
=> [CAZ-2166] Add a return to dashboard button on the debits page

app/javascript/packs/payment_matrix.js, app/views/debits/index.html.haml, package.json, yarn.lock
=> ST Update for minor bug fixes

app/views/debits/success.html.haml
https://eaflood.atlassian.net/browse/CAZ-2167
Add payment id to the success page
=> [CAZ-2167] Add payment id to the success dd page

app/javascript/packs/payment_matrix.js, app/views/debits/index.html.haml, app/views/debits/success.html.haml, package.json, yarn.lock
Add payment ID to confirmation page
=> Add payment ID to confirmation page

app/views/vehicles/exempt.html.haml
https://eaflood.atlassian.net/browse/CAZ-2303
=> [CAZ-2303] Update the exempt page

app/views/vehicles/not_found.html.haml
https://eaflood.atlassian.net/browse/CAZ-2302
=> [CAZ-2302] Update the not found page

app/views/fleets/submission_method.html.haml, features/fleets.feature, features/step_definitions/fleets_steps.rb
https://eaflood.atlassian.net/browse/CAZ-2301
=> [CAZ-2301] Update the submission method page

app/views/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZ-2300
=> [CAZ-2300] Update the vehicle management page

config/locales/en.yml, features/uploads.feature
https://eaflood.atlassian.net/browse/CAZ-2298
=> [CAZ-2298] Update the upload page

app/views/payments/review_details.html.haml, features/payments.feature
https://eaflood.atlassian.net/browse/CAZ-2305
=> [CAZ-2305] Add a return button to the Charge details page

config/locales/en.yml, features/debits.feature, features/payments.feature
https://eaflood.atlassian.net/browse/CAZ-2304
=> [CAZ-2304] Update error messaging for Clean Air Zone selection page

app/forms/email_and_password_form.rb, spec/forms/email_and_password_form_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2296
=> [CAZ-2296] Account registration page error messaging revisions

app/views/payments/failure.html.haml
Changes required as part of  CAZ-2203
Added wording, link to start and link to print page
manually went on the page and checked the links
=> [NT] Added wording

app/controllers/organisations_controller.rb, app/views/organisations/form_input/_errored.html.haml, app/views/organisations/form_input/_normal.html.haml, app/views/organisations/new.html.haml, features/organisations.feature, features/step_definitions/helper_steps.rb, spec/requests/organisations_controller/create_spec.rb, spec/requests/organisations_controller/email_sent_spec.rb, spec/requests/organisations_controller/new_credentials_spec.rb, spec/requests/organisations_controller/resend_email_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2317
This is the only a part of story.
=> [CAZ-2317] Keep the company creation input data in session

app/forms/base_form.rb, spec/models/reset_password_form_spec.rb
likeuwifsdfdsfsfdll@@gmail.com
=> [CAZ-2149] Validate two `at sign` symbols for email address

app/controllers/organisations_controller.rb
=> [NT] Redis can't read session key as a symbol

app/controllers/organisations_controller.rb, app/views/organisations/form_input/_errored.html.haml, app/views/organisations/form_input/_normal.html.haml, app/views/organisations/new.html.haml
https://eaflood.atlassian.net/browse/CAZ-2317
=> [CAZ-2317] Stringify all cookies keys for organisation creation flow

app/helpers/application_helper.rb
https://eaflood.atlassian.net/browse/CAZB-36
=> [NT] Fix aria-label typo

app/api_wrappers/accounts_api.rb, app/controllers/organisations_controller.rb, app/services/create_user_account.rb, features/step_definitions/organisations_steps.rb, spec/api_wrappers/accounts_api/create_account_spec.rb, spec/api_wrappers/accounts_api/create_user_spec.rb, spec/fixtures/responses/create_user.json, spec/fixtures/responses/user.json, spec/requests/organisations_controller/create_spec.rb, spec/requests/organisations_controller/email_sent_spec.rb, spec/requests/organisations_controller/new_credentials_spec.rb, spec/requests/organisations_controller/resend_email_spec.rb, spec/services/create_user_account_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2271
=> [CAZ-2271] Make API call to create user

app/javascript/styles/cookie_control.scss, app/views/layouts/_cookie_control.html.erb, app/views/layouts/application.html.haml
https://eaflood.atlassian.net/browse/CAZ-2242
=> [CAZ-2242] Bump Control Cookies to version 9

app/api_wrappers/accounts_api.rb, app/controllers/organisations_controller.rb, app/exceptions/invalid_company_name_exception.rb, app/forms/company_name_form.rb, app/services/create_account.rb, app/views/shared/sign_in/_error_summary.html.haml, config/locales/en.yml, features/step_definitions/organisations_steps.rb, spec/api_wrappers/accounts_api/create_account_spec.rb, spec/fixtures/responses/create_account.json, spec/forms/company_name_form_spec.rb, spec/requests/organisations_controller/set_name_spec.rb, spec/services/create_account_spec.rb
[Link to CAZ-2269 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2269)
* Changed the implementation of `CreateAccount` service to only send `company_name` to the API
* Added validation rules for the company name format
* Rspec and cucumber tests
* Manually test with the local instance of Accounts API.
=> [CAZ-2269] API call to create company

config/locales/en.yml
=> [CAZ-2274] Updated error messages

app/api_wrappers/accounts_api.rb, app/controllers/organisations_controller.rb, app/exceptions/invalid_company_name_exception.rb, app/forms/company_name_form.rb, app/javascript/styles/cookie_control.scss, app/services/create_account.rb, app/views/layouts/_cookie_control.html.erb, app/views/layouts/application.html.haml, app/views/shared/sign_in/_error_summary.html.haml, config/locales/en.yml, features/step_definitions/organisations_steps.rb, spec/api_wrappers/accounts_api/create_account_spec.rb, spec/fixtures/responses/create_account.json, spec/forms/company_name_form_spec.rb, spec/requests/organisations_controller/set_name_spec.rb, spec/services/create_account_spec.rb
=> Update ST environment release v1.0.0

app/views/payments/matrix/_details.html.haml
[Link to CAZ-2345 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2345)
* Added `<ul>` tag
Manually.
=> [CAZ-2345] List display improvement

.drone.yml
Update echo command in drone file
=> Update echo command in drone file

app/views/vehicles/details.html.haml
https://eaflood.atlassian.net/browse/CAZ-2343
Added table header on the vehicle details page.
The header is the same as in the [VCCs project.](https://github.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/pull/405/files)
Manually.
----
=> [CAZ-2343] Table markup fix

app/forms/company_name_form.rb, app/views/organisations/new.html.haml, features/organisations.feature, features/step_definitions/organisations_steps.rb
=> [CAZ-2319] Error if company name is longer than 180 characters

app/views/layouts/application.html.haml
https://eaflood.atlassian.net/browse/CAZ-2344
* Added skip to content link.
* Manually.
=> [CAZ-2344] Skip to content link

.rubocop.yml, Gemfile.lock, app/controllers/uploads_controller.rb, app/controllers/vehicles_controller.rb, spec/requests/uploads/download_template_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2317
=> [CAZ-2317] Save the previous state of  submission_method page

app/views/uploads/_description.html.haml
https://eaflood.atlassian.net/browse/CAZ-2346
* Change download URL to more the descriptive one.
Manually.
=> [CAZ-2346] More descriptive download link

app/views/payments/select_payment_method.html.haml
https://eaflood.atlassian.net/browse/CAZ-2521 - fix card for: https://eaflood.atlassian.net/browse/CAZ-2519
* Back button was directing to the wrong page.
Manually.
N/A
=> [CAZ-2521] Back button on payment method select page

app/helpers/application_helper.rb, app/views/fleets/index.html.haml
=> Add link descriptors

app/views/payments/success.html.haml
=> Add return to your account link on payment confirmation

app/views/fleets/submission_method.html.haml, app/views/uploads/_description.html.haml, app/views/uploads/_reupload.html.haml, app/views/uploads/_upload.html.haml, features/payments.feature, features/step_definitions/fleets_steps.rb, features/uploads.feature
https://eaflood.atlassian.net/browse/CAZ-2374
Updated texts associated with CSV upload.
Manually and with cucumber specs.
=> [CAZ-2374] Improved upload CSV guidance

app/views/payments/success.html.haml
=> Correct wording of link

app/views/debits/success.html.haml
=> Add back link to debit confirmation page

app/helpers/application_helper.rb, app/views/fleets/_pagination.html.haml, app/views/fleets/_pagination_button.html.haml, app/views/fleets/index.html.haml, app/views/payments/matrix/_pagination.html.haml, features/fleets.feature
https://eaflood.atlassian.net/browse/CAZ-2352
* Added more descriptive links to pagination so it may be more readable for screen reader users.
* Manually.
=> [CAZ-2352] More descriptive pagination links

app/views/uploads/_description.html.haml, app/views/uploads/_reupload.html.haml, app/views/uploads/_upload.html.haml
* Link text update
* Changed first letters in list elements lowercased to march card description
=> [CAZ-2374] link text update

app/views/fleets/submission_method.html.haml
=> [CAZ-2374] Submission method description change

app/views/fleets/index.html.haml
=> Fix/cazb 2397/exempt vehicle

app/views/fleets/index.html.haml
=> revert change

app/views/dashboard/index.html.haml, features/dashboard.feature
https://eaflood.atlassian.net/browse/CAZ-2581
----------------------
=> [CAZ-2581] Prevent Direct Debit dashboard feature from being hidden

app/api_wrappers/debits_api.rb, app/controllers/debits_controller.rb, app/services/make_debit_payment.rb, app/views/dashboard/_direct_debit.html.haml, app/views/debits/first_mandate.html.haml, app/views/debits/index.html.haml, app/views/debits/new.html.haml, features/debits.feature, features/step_definitions/debits_steps.rb, spec/requests/debits/new_spec.rb, spec/requests/payments/select_payment_method_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2536
=> [CAZ-2536] Capitalise every instance of Direct Debit text

features/dashboard.feature
=> Fix dashboard feature test

app/views/uploads/_description.html.haml
=> [CAZ-2374] Typo fix

app/views/debits/index.html.haml, features/debits.feature
[Link to CAZ-2537 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2537)
* Updated text on Direct Debit page.
Manually.
=> [CAZ-2537] DirectDebits page text update

app/views/debits/new.html.haml
[Link to CAZ-2538 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2538)
=> [CAZ-2538] DirectDebits - CAZ selection text update

Dockerfile.build, Dockerfile.test, Gemfile.lock, app/views/dashboard/_direct_debit.html.haml, app/views/dashboard/_make_payment.html.haml, app/views/dashboard/_manage_vehicles.html.haml, app/views/dashboard/index.html.haml, features/dashboard.feature
https://eaflood.atlassian.net/browse/CAZ-2534
I also unlocked bundler version, as it was tested on CS UI and with last version of bundler all works fine(in production mode)
=> [CAZ-2534] Update dashboard page

app/views/debits/index.html.haml
[Link to CAZ-2537 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2537)
=> [CAZ-2537] Added missing paragraph

app/controllers/debits_controller.rb, app/helpers/application_helper.rb, app/views/debits/confirm.html.haml, spec/fixtures/responses/debits/active_mandates.json, spec/fixtures/responses/debits/caz_mandates.json, spec/fixtures/responses/debits/inactive_caz_mandates.json, spec/fixtures/responses/debits/inactive_mandates.json, spec/fixtures/responses/debits/mandates.json
https://eaflood.atlassian.net/browse/CAZ-2616
=> [CAZ-2616] Show Mandate ID and Creation date on payment confirm page

app/controllers/payments_controller.rb, features/step_definitions/fleets_steps.rb, features/step_definitions/payments_steps.rb, spec/requests/payments/select_payment_method_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2533
=> [CAZ-2533] Check active caz mandates on select payment method page

app/views/uploads/_reupload.html.haml, app/views/uploads/_upload.html.haml
https://eaflood.atlassian.net/browse/CAZ-2537
=> [CAZ-2346] Extend download template link

app/helpers/application_helper.rb
=> Change back link to remove dashboard reference

app/views/debits/index.html.haml
=> Replace CAZ with Clean Air Zone

app/controllers/debits_controller.rb, app/helpers/application_helper.rb, app/models/clean_air_zone.rb, app/views/debits/confirm.html.haml, app/views/fleets/submission_method.html.haml, spec/helpers/application_helpers_spec.rb, spec/models/clean_air_zones_spec.rb, spec/requests/debits/confirm_spec.rb, spec/requests/fleets/index_spec.rb, spec/support/mocked_responses.rb
Some UI changes. 
Also, I fixed a bug with calling API endpoint `clean_air_zones` 3 unnecessary times. So we calling 1st time and then just using data from memory
--------------
=> Add zone name to `Confirm your payment` page and fix `Back` link

app/views/debits/index.html.haml
=> [CAZ-2537] Removed duplicated text

app/views/payments/review_details.html.haml, features/payments.feature
https://eaflood.atlassian.net/browse/CAZ-2654
=> [CAZ-2654] - Update link text on `Charge details` page

app/helpers/payments_helper.rb
https://eaflood.atlassian.net/browse/CAZ-2654
=> [CAZ-2654] Update dates format on `Charge details` page

app/helpers/payments_helper.rb, app/views/debits/index.html.haml, app/views/payments/failure.html.haml, app/views/payments/review_details.html.haml, features/payments.feature
Promote selective text changes to v1.0.0 based on PO feedback.
=> V1.0.0 selective commits

app/controllers/organisations_controller.rb, app/exceptions/account_for_multiple_vehicles_exception.rb, app/exceptions/invalid_company_create_exception.rb, app/exceptions/unable_to_create_account_exception.rb, app/forms/create_account_form.rb, app/services/check_company_name.rb, app/services/create_account.rb, app/services/session_manipulation/set_company_name.rb, app/views/organisations/cannot_create.html.haml, app/views/organisations/fleet_check.html.haml, app/views/organisations/new.html.haml, config/routes.rb, features/organisations.feature, spec/forms/create_account_form_spec.rb, spec/requests/organisations_controller/cannot_create_spec.rb, spec/requests/organisations_controller/create_account_spec.rb, spec/requests/organisations_controller/fleet_check_spec.rb, spec/requests/organisations_controller/set_name_spec.rb, spec/services/check_company_name_spec.rb, spec/services/create_account_spec.rb, spec/services/session_manipulation/set_company_name_spec.rb
Jira Cards: 
https://eaflood.atlassian.net/browse/CAZ-2597
https://eaflood.atlassian.net/browse/CAZ-2598
Add a new step in the Sign Up process to check if fleet has more than two vehicles. 
Tried to create account
-------
=> [CAZ-967] Add new step in sign up to check if Fleet has more than two vehicles

app/controllers/organisations_controller.rb, app/helpers/fleets_helper.rb, app/services/session_manipulation/set_fleet_check.rb, app/views/organisations/fleet_check.html.haml, app/views/organisations/new_credentials.html.haml, features/organisations.feature, spec/services/session_manipulation/set_fleet_check_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZ-967
Fixed issue when not selected Fleet check, 
Fixed back button after Fleet check
=> [CAZ-967] Fix Fleet check when not checked

app/views/organisations/new.html.haml, config/locales/en.yml
=> [CAZ-2274] Update error message for duplicate company name

app/controllers/payments_controller.rb, app/models/fleet.rb, app/views/payments/no_chargeable_vehicles.html.haml, config/routes.rb, features/payments.feature, features/step_definitions/fleets_steps.rb, features/step_definitions/payments_steps.rb, features/support/mock_fleet.rb, spec/models/fleet_spec.rb, spec/requests/payments/local_authority_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2134
* Redirects to page informing that there are no chargeable vehicles in the fleet when trying to pay in a selected clean air zone.
Manually, rspec, cucumber.
=> [CAZ-2134] No chargeable fleet vehicles in CAZ

app/views/vehicles/incorrect_details.html.haml
https://eaflood.atlassian.net/browse/CAZ-2582
The text was changed to the proposed one.
Manually.
=> [CAZ-2582] Accounts - Incorrect vehicle details page update

app/views/layouts/_cookie_control.html.erb
https://eaflood.atlassian.net/browse/CAZB-1033
https://www.civicuk.com/cookie-control/v9/documentation-v9.1.html
=> [CAZB-1033] Update CookieControl to version 9

.drone.yml
=> added drone

.drone.yml, Gemfile.lock, app/views/layouts/application.html.haml, package.json, yarn.lock
=> Add the SRI hash to Cookie Control

.drone.yml, Gemfile.lock, app/views/layouts/application.html.haml, package.json, yarn.lock
Add the SRI hash to Cookie Control (#285)
=> [CAZB-1033] Add the SRI hash to Cookie Control (#285)

app/api_wrappers/debits_api.rb, app/controllers/debits_controller.rb, app/services/make_debit_payment.rb, spec/services/make_debit_payment_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZ-2671
Added new attribute which is sent do Payments API during Direct Debit payment creation. 
Tried to make a payment and checked attributes.
N/A
=> [CAZ-2671] add userEmail attribute to DebitsAPI create_payment

app/views/fleets/index.html.haml, app/views/uploads/processing.html.haml
=> [CAZ-2341] Add indicative content for screenreaders

app/views/layouts/application.html.haml
https://eaflood.atlassian.net/browse/CAZB-1507
=> [CAZB-1542]  Update check sum for Cookie Controller

app/controllers/payments_controller.rb, app/helpers/application_helper.rb, app/javascript/styles/application.scss, app/models/clean_air_zone.rb, app/services/payment_dates.rb, app/views/payments/matrix.html.haml, app/views/payments/matrix/_headling.html.haml, app/views/payments/matrix/_next_week_tab.html.haml, app/views/payments/matrix/_past_week_tab.html.haml, app/views/payments/matrix/_table.html.haml, app/views/payments/matrix/_tabs.html.haml, features/payments.feature, features/step_definitions/fleets_steps.rb, features/support/mock_vccs.rb, spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb, spec/fixtures/responses/caz_list.json, spec/models/clean_air_zones_spec.rb, spec/services/payment_dates_spec.rb
Jira cards: 
https://eaflood.atlassian.net/browse/CAZ-2392
https://eaflood.atlassian.net/browse/CAZ-2656
Updated the matrix methods to show only checkboxes to data after the CAZ started charging date. 
I tried to manipulate the date in the CleanAirZone model.
More than 6 days:
3 days ago:
Today:
=> [CAZ-2392] Apply logic to payment matrix to filter out dates before a CAZ started charging

app/api_wrappers/accounts_api.rb, app/controllers/organisations_controller.rb, app/services/create_user_account.rb, spec/api_wrappers/accounts_api/create_user_spec.rb, spec/requests/organisations/create_spec.rb, spec/services/create_user_account_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZ-2680
Added verificationUrl to create user account. 
Tried to create an account and checked params.
=> [CAZ-2680] Include validation URL in API call to create user

app/api_wrappers/accounts_api.rb, app/controllers/organisations_controller.rb, app/services/verify_account.rb, app/views/organisations/verification_expired.html.haml, config/routes.rb, features/organisations.feature, features/step_definitions/organisations_steps.rb, spec/api_wrappers/accounts_api/verify_user_spec.rb, spec/requests/organisations/email_verification_spec.rb, spec/requests/organisations/verification_expired_spec.rb, spec/services/verify_account_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2681
* Changed behaviour of the `VerifyUser` service as currently the backend stores verification tokens and validates them. 
* `VerifyUser` service returns the following verification results: `emailAlreadyVerified`, `invalid`, `expired`
* OrganisationsController redirects accordingly to the returned status.
* Create a new account and click the verification link. Click for the second time and you should see the information that email is already confirmed.
* Create a new account and wait for the verification link to expire. After clicking the expired link there should be page informing that link is expired.
=> [CAZ-2681] Token validation and expired page

app/views/layouts/application.html.haml
=> temporarily remove Civic SRI hash

app/api_wrappers/accounts_api.rb, app/controllers/organisations_controller.rb, app/services/session_manipulation/set_account_id.rb, app/services/verify_account.rb, app/views/layouts/application.html.haml, app/views/organisations/fleet_check.html.haml, app/views/organisations/verification_expired.html.haml, config/routes.rb, features/organisations.feature, features/step_definitions/organisations_steps.rb, spec/api_wrappers/accounts_api/verify_user_spec.rb, spec/requests/organisations/email_verification_spec.rb, spec/requests/organisations/set_name_spec.rb, spec/requests/organisations/verification_expired_spec.rb, spec/services/session_manipulation/set_account_id_spec.rb, spec/services/verify_account_spec.rb
Update ST with latest develop code
=> Update ST with latest develop code

app/controllers/uploads_controller.rb, app/controllers/vehicles_controller.rb, app/views/vehicles/local_exemptions.html.haml, config/routes.rb, features/vehicles.feature, spec/requests/vehicles/add_to_fleet_spec.rb, spec/requests/vehicles/confirm_details_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2582?focusedCommentId=214837
In this PR - process of adding new vehicle to the fleet was changed. Right now both valid and invalid vehicles are added to the fleet.
Manually, new test cases and old ones fixed.
n/a
=> [CAZ-2582] Store vehicle with incorrect details

app/api_wrappers/accounts_api.rb, app/controllers/organisations_controller.rb, app/controllers/uploads_controller.rb, app/controllers/vehicles_controller.rb, app/services/session_manipulation/set_account_id.rb, app/services/verify_account.rb, app/views/layouts/application.html.haml, app/views/organisations/fleet_check.html.haml, app/views/organisations/verification_expired.html.haml, app/views/vehicles/local_exemptions.html.haml, config/routes.rb, features/organisations.feature, features/step_definitions/organisations_steps.rb, features/vehicles.feature, spec/api_wrappers/accounts_api/verify_user_spec.rb, spec/requests/organisations/email_verification_spec.rb, spec/requests/organisations/set_name_spec.rb, spec/requests/organisations/verification_expired_spec.rb, spec/requests/vehicles/add_to_fleet_spec.rb, spec/requests/vehicles/confirm_details_spec.rb, spec/services/session_manipulation/set_account_id_spec.rb, spec/services/verify_account_spec.rb
Update RC 1.1.0 with revised verification methods
=> Update RC 1.1.0 with revised verification methods

app/controllers/static_pages_controller.rb, app/views/layouts/_footer.html.haml, app/views/static_pages/privacy_notice.html.haml, config/routes.rb, features/static_pages.feature, features/step_definitions/static_pages_steps.rb, spec/requests/static_pages_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2795
* Added `Privacy notice` page and link
=> [CAZ-2795] Added privacy notice

app/views/debits/success.html.haml, app/views/payments/success.html.haml
=> [CAZ-2827] Add missing content to the direct debit confirmation page

app/api_wrappers/accounts_api.rb, app/controllers/application_controller.rb, app/controllers/organisations_controller.rb, app/models/user.rb, config/initializers/assets.rb, features/dashboard.feature, features/sign_in.feature, features/step_definitions/sign_in_steps.rb, features/support/sign_in_helper.rb, spec/api_wrappers/accounts_api/create_user_spec.rb, spec/api_wrappers/accounts_api/sign_in_spec.rb, spec/fixtures/responses/create_user.json, spec/requests/fleets/create_spec.rb, spec/requests/sign_in_spec.rb, spec/requests/sign_out_spec.rb, spec/services/create_user_account_spec.rb, spec/support/user_factory.rb
https://eaflood.atlassian.net/browse/CAZ-2786
I also fixed unpermitted parameters warning from logs for login_ip when user trying to sign in with invalid credentionals
=> [CAZ-2786] Rename `admin` field to `owner`

app/views/static_pages/privacy_notice.html.haml
Fix for https://eaflood.atlassian.net/browse/CAZ-2795 -> comment
=> [CAZ-2795] Link update

app/models/clean_air_zone.rb, features/support/mock_vccs.rb, spec/models/clean_air_zones_spec.rb
=> [NT] Remove memoization for `ComplianceCheckerApi.clean_air_zones` endpoint

app/api_wrappers/compliance_checker_api.rb
=> Remove logger for clean_air_zones endpoint

app/models/vehicle.rb, app/views/fleets/index.html.haml
=> [CAZ-2731] amend account display to display exempt as a charge for those vehicles

.drone2.yml
=> updated secrets and accountname

app/views/static_pages/privacy_notice.html.haml
=> [CAZ-2795] Privacy notice links update

app/api_wrappers/accounts_api.rb, config/routes.rb, spec/api_wrappers/accounts_api/resend_verification_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2801
=> [CAZ-2801] Removed mocked request

.drone.yml, pa11y/.gitignore, pa11y/.pa11yci.conf.js, pa11y/Dockerfile, pa11y/Makefile, package.json
=> fleet accessibility tests

app/views/payments/matrix/_next_week_tab.html.haml
https://eaflood.atlassian.net/browse/CAZ-2809
=> [CAZ-2709] Show D-Day notice if it starting from today

.env.test, Dockerfile.build, config/initializers/amazon_s3_client.rb
https://eaflood.atlassian.net/browse/CAZB-1522
Use ECSCredentials to connect with AWS in production environment or if credential envs not set
=> [CAZB-1522] Use ECS Credentials for production environment

app/controllers/fleets_controller.rb
Currently, if a user manipulates the URL on the grid page in Fleets to set it to a page greater than the pages available, we show a service unavailable page.
Catch 400 error supplied from Payments API and redirect to first page.
=> [CAZ-2723] redirect to page 1 if page out of bounds

Dockerfile.build, Dockerfile.test, config/initializers/amazon_s3_client.rb
=> refactor aws env vars in dockerfile

.env.test, Dockerfile.build, Dockerfile.test, app/controllers/fleets_controller.rb, app/javascript/styles/cookie_control.scss, app/services/payment_dates.rb, config/initializers/amazon_s3_client.rb, features/payments.feature, spec/services/payment_dates_spec.rb
Merge ECS task role to AWS restructure branch
=> Merge ECS task role to AWS restructure branch

.drone2.yml, .env.test, Dockerfile.build, Dockerfile.test, app/controllers/fleets_controller.rb, app/javascript/styles/cookie_control.scss, app/services/payment_dates.rb, config/initializers/amazon_s3_client.rb, features/payments.feature, spec/services/payment_dates_spec.rb
=> Iac restructure baseline

app/views/debits/confirm.html.haml, app/views/devise/sessions/sign_out.html.haml, app/views/fleets/index.html.haml, app/views/layouts/application.html.haml, app/views/static_pages/accessibility_statement.html.haml, config/application.rb, features/sign_in.feature, features/static_pages.feature
=> Update banner name

.env.example, Gemfile.lock, app/controllers/vehicles_controller.rb, app/views/debits/confirm.html.haml, app/views/devise/sessions/sign_out.html.haml, app/views/fleets/index.html.haml, app/views/layouts/_gtm_noscript.html.erb, app/views/layouts/_gtm_script.html.erb, app/views/layouts/application.html.haml, app/views/static_pages/accessibility_statement.html.haml, app/views/vehicles/exempt.html.haml, config/application.rb, config/routes.rb, features/sign_in.feature, features/static_pages.feature, features/vehicles.feature, spec/requests/vehicles/confirm_and_add_exempt_vehicle_to_fleet_spec.rb
Merge up latest app to new AWS setup
=> Merge up latest app to new AWS setup

app/services/payment_dates.rb, app/views/payments/matrix.html.haml, app/views/payments/matrix/_details.html.haml, app/views/payments/matrix/_next_week_tab.html.haml, app/views/payments/matrix/_past_week_tab.html.haml, features/payments.feature, spec/services/payment_dates_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2909
=> [CAZ-2909] Update D-Day notice

config/initializers/content_security_policy.rb
=> [NT] Update CSP for GTM

app/views/layouts/_gtm_noscript.html.erb
=> Changed GTM noscript parameter

app/views/layouts/_gtm_noscript.html.erb
=> [NT] Add title for iframe

.drone2.yml
=> Updated preprod drone changes

app/controllers/fleets_controller.rb
https://eaflood.atlassian.net/browse/CAZ-2958
https://eaflood.atlassian.net/browse/CAZ-2960
After CSV upload - single vehicle cannot be added - fixed.
Manually
=> [CAZ-2960] Unable to add single vehicle after CSV upload

app/views/payments/matrix/_next_week_tab.html.haml, app/views/payments/matrix/_past_week_tab.html.haml
https://eaflood.atlassian.net/browse/CAZ-2656
=> [CAZ-2656] Remove D-Day notice from past and next week tabs

.env.example, app/views/layouts/_gtm_noscript.html.erb, app/views/layouts/_gtm_script.html.erb, app/views/layouts/application.html.haml, config/initializers/content_security_policy.rb
=> Update ST with v1.2.0

.drone2.yml
=> Updated prod deployment steps

app/controllers/fleets_controller.rb, app/views/payments/matrix/_next_week_tab.html.haml, app/views/payments/matrix/_past_week_tab.html.haml
=> Promote dev to ST v1.2.0

app/assets/stylesheets/application.css, app/views/fleets/_pagination_button.html.haml, app/views/layouts/_timeout.html.haml
JIRA Card: https://eaflood.atlassian.net/browse/CAZ-2352
* Added hidden content for pagination so that user who uses a screen-reader and navigates without a context, can see what page numbers means.
* Verified using `Screen Reader for Chrome Google` plugin
=> [CAZ-2352] Descriptive links for screen readers

.drone2.yml
=> updated drone fix for sit deployment

.drone2.yml
=> updated ecs rollout update task for preprod and prod

app/models/direct_debit.rb
=> [CAZ-2842] Put cazes in alphabetical order

.drone2.yml
=> Removed preprod  and prod service account credential references

Dockerfile.build, Dockerfile.test, config/initializers/amazon_s3_client.rb
Merge in dockerfile update for ECS task usage
=> Refactor aws env vars in dockerfile (#330)

app/api_wrappers/accounts_api.rb, app/controllers/users_controller.rb, app/forms/new_user_form.rb, app/services/session_manipulation/set_new_user.rb, app/views/users/add_permissions.html.haml, app/views/users/new.html.haml, app/views/users/new_user_form_input/_errored.html.haml, app/views/users/new_user_form_input/_normal.html.haml, config/locales/en.yml, config/routes.rb, spec/api_wrappers/accounts_api/user_validations_spec.rb, spec/services/session_manipulation/set_new_user_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2402
Add user page - the first step of the adding new user process
Manually, new Rspec added, cucumber tests will be added in the next issue CAZ-2925 when the process will be more fully.
=> [CAZ-2402] Add User Page

.drone2.yml
=> updated UAT drone steps

app/controllers/users_controller.rb, features/manage_users.feature
https://eaflood.atlassian.net/browse/CAZ-2402?focusedCommentId=224333
Redirects changed to renders to properly shows errors
Manually, feature tests changed.
=> [CAZ-2402] Change redirects to renders in order to properly show errors

app/helpers/users_helper.rb, app/models/manage_users/user.rb, app/views/users/index.html.haml, features/support/mock_users.rb, spec/models/manage_users/user_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2400
=> [CAZ-2400] Hide manage link for current user

app/views/dashboard/index.html.haml, app/views/organisations/cannot_create.html.haml
https://eaflood.atlassian.net/browse/CAZ-3011
https://eaflood.atlassian.net/browse/CAZ-3012
CAZ-3011 - Text changes
CAZ-3012 - Typo fix
=> [CAZ-3011|CAZ-3012] Text changes

app/controllers/passwords_controller.rb, app/forms/add_new_user_form.rb, app/forms/base_form.rb, app/forms/company_name_form.rb, app/forms/email_and_password_form.rb, app/forms/fleet_check_form.rb, app/forms/new_password_form.rb, app/forms/reset_password_form.rb, app/forms/submission_method_form.rb, app/services/base_service.rb, app/services/create_account.rb, app/services/validate_fleet_check.rb, config/locales/en.yml, features/fleets.feature, features/manage_users.feature, features/organisations.feature, features/password_reset.feature, features/uploads.feature, spec/forms/company_name_form_spec.rb, spec/forms/email_and_password_form_spec.rb, spec/forms/fleet_check_form_spec.rb, spec/forms/new_password_form_spec.rb, spec/forms/reset_password_form_spec.rb, spec/forms/submission_method_form_spec.rb, spec/models/reset_password_form_spec.rb, spec/requests/passwords/create_spec.rb, spec/services/create_account_spec.rb, spec/services/validate_fleet_check_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZ-2949
Updated error messages and all related tests
- CAZ-2962:
- CAZ-2963: 
- CAZ-2965:
- CAZ-2966:
- CAZ-2967/CAZ-2968:
- CAZ-2969:
- CAZ-2970:
=> [CAZ-2949] Error message changes

.drone.yml
=> Fix yarn audit warning

app/views/payments/failure.html.haml
https://eaflood.atlassian.net/browse/CAZB-2172
=> [CAZB-2172] Contact details on Payment Unsuccessful page

app/views/static_pages/accessibility_statement.html.haml
https://eaflood.atlassian.net/browse/CAZB-2056
=> [CAZB-2056] Fleets accessibility policy updates

app/views/static_pages/accessibility_statement.html.haml, pa11y/.pa11yci.conf.js
http://drone-185002984.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Fleets-UI/237/1/10
=> Fix pa11y test

pa11y/.pa11yci.conf.js
http://drone-185002984.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Fleets-UI/237/1/10
fixed here
http://drone-185002984.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Fleets-UI/241
=> Uncomment Pa11y test after it was fixed on dev

.drone2.yml
=> drone2 migrate changes to develop branch

app/views/users_management/create_users/confirmation.html.haml
https://eaflood.atlassian.net/browse/CAZ-2412?focusedCommentId=226757
Change in user confirmation page
Manually
=> [CAZ-2412] Fix text in User Confirmation Page

app/controllers/users_management/remove_users_controller.rb, app/views/users_management/remove_users/remove.haml
https://eaflood.atlassian.net/browse/CAZB-2144
=> [CAZB-2144] Fix design on the user removal page

app/views/devise/sessions/new.html.haml, app/views/organisations/organisations/email_verified.haml, app/views/shared/sign_in/_email_field.html.haml, app/views/shared/sign_in/_error_summary.html.haml, app/views/shared/sign_in/_password_field.html.haml, app/views/users_management/create_users/set_up_confirmation.html.haml, config/initializers/devise.rb, features/sign_in.feature, features/step_definitions/sign_in_steps.rb, lib/custom_failure.rb, spec/requests/sign_in_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2141
Manual, cucumber, rspec
=> [CAZB-2141] Account set up confirmation page

.drone2.yml
=> Updated st env url

app/controllers/users_management/remove_users_controller.rb, app/views/users_management/remove_users/remove.haml, features/users_management/remove_user.feature
https://eaflood.atlassian.net/browse/CAZB-2144
=> [CAZB-2144] Fix back button on the user removal page

app/views/static_pages/accessibility_statement.html.haml
=> [CAZB-2056] Update gov pay accessibility link

Gemfile, Gemfile.lock, app/api_wrappers/accounts_api.rb, app/controllers/users_management/create_users_controller.rb, app/views/users_management/create_users/set_up.html.haml, config/initializers/filter_parameter_logging.rb, features/step_definitions/users_steps.rb, features/users_management/account_set_up.feature, spec/requests/users_management/create_users/confirm_set_up_spec.rb, spec/requests/users_management/create_users/set_up_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2365
Added API call before page render, error handling and tests
Manually - valid token and account uuid are required - can be taken from accounts lambda logs after inviting new user to the organisation.
Rspec and cucumber tests
Valid account uuid:
If invalid or missing account uuid:
=> [CAZB-2365] Dynamic company name on account set up page

app/controllers/users_management/create_users_controller.rb
=> Fix verification_url when sending set up link to user

app/controllers/users_management/create_users_controller.rb
=> Fix verification_url when sending set up link to user (#412)

app/views/users_management/users/index.html.haml, features/users_management/edit_user.feature, features/users_management/manage_users.feature, features/users_management/remove_user.feature
https://eaflood.atlassian.net/browse/CAZ-2400
=> [CAZ-2400] Rename 'Manage' link to 'Change'

.drone2.yml
=> Updated URLs for SIT, Preprod and UAT environments

app/views/users_management/create_users/add_permissions.html.haml, app/views/users_management/create_users/set_up.html.haml, config/routes.rb, features/users_management/manage_users.feature, spec/requests/users_management/create_users/confirm_set_up_spec.rb, spec/requests/users_management/create_users/set_up_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2143
=> [CAZB-2143] Fix back button on the add permissions page

app/api_wrappers/base_api.rb, app/models/users_management/user.rb, app/services/users_management/users.rb, spec/fixtures/responses/users_management/users.json, spec/models/manage_users/user_spec.rb, spec/services/users_management/users_spec.rb
https://eaflood.atlassian.net/browse/CAZ-3091
https://eaflood.atlassian.net/browse/CAZ-2400
=> [CAZ-3091] Sort users by name and downcase email

app/api_wrappers/accounts_api.rb, app/controllers/users_management/create_users_controller.rb, features/step_definitions/dashboard_steps.rb, features/step_definitions/users_management/manage_users_steps.rb, features/users_management/manage_users.feature
https://eaflood.atlassian.net/browse/CAZ-2413
=> [CAZ-2413] Fix back button on the Add a new user page

.drone2.yml
=> updated prod url

app/controllers/passwords_controller.rb, app/views/passwords/reset.html.haml, features/sign_in.feature, features/users_management/account_set_up.feature
https://eaflood.atlassian.net/browse/CAZB-2141?focusedCommentId=228581
Manually, cucumber tests
=> [CAZB-2141] Account set up confirmation back button fix

config/locales/en.yml, features/password_reset.feature, features/users_management/account_set_up.feature
https://eaflood.atlassian.net/browse/CAZB-2142?focusedCommentId=229085
Changed password errors and hints back to require 8 characters
=> [CAZB-2142] Change password complexity error

app/views/payment_history/payment_history/user_payment_history.html.haml
https://eaflood.atlassian.net/browse/CAZB-2155
=> [CAZB-2155] Update the user payment page title

.env.example, app/controllers/application_controller.rb
=> Add basic auth to Fleets UI

app/forms/set_up_account_form.rb, features/users_management/account_set_up.feature, spec/forms/set_up_account_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2142?focusedCommentId=229774
Updated password message
Manually, cucumber and rspec updated
=> [CAZB-2142] Fixed password missing error

app/controllers/logout_controller.rb, app/controllers/passwords_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_management/create_users_controller.rb, config/routes.rb, features/users_management/account_set_up.feature
https://eaflood.atlassian.net/browse/CAZB-2141?focusedCommentId=229849
Referer is used if available, if not, a session value is used which is assigned during login and set up confirmation page render.
Manually, added cucumber tests
=> [CAZB-2141] Fix Password Reset view back button behavior

app/controllers/users_management/remove_users_controller.rb, config/locales/en.yml, features/users_management/remove_user.feature, spec/requests/users_management/remove_users/confirm_remove_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2144
=> [CAZB-2144] Update error message on user removal page

app/api_wrappers/accounts_api.rb
=> Downcase user invitation email

Gemfile.lock, app/api_wrappers/payment_history_api.rb, app/controllers/concerns/check_permissions.rb, app/controllers/dashboard_controller.rb, app/controllers/payment_history/payment_history_controller.rb, app/controllers/users_management/create_users_controller.rb, app/controllers/users_management/users_controller.rb, app/models/payment_history/details.rb, app/models/payment_history/details_payment.rb, app/models/payment_history/history.rb, app/services/users_management/users.rb, app/views/payment_history/payment_history/company_payment_history.html.haml, app/views/payment_history/payment_history/payment_history_details.html.haml, app/views/payment_history/payment_history/user_payment_history.html.haml, config/environments/development.rb, features/payment_history.feature, features/step_definitions/payment_history_steps.rb, package.json, spec/api_wrappers/payment_history_api/payment_details_spec.rb, spec/api_wrappers/payment_history_api/payments_spec.rb, spec/fixtures/responses/payment_history/payment_details.json, spec/models/payment_history/details_spec.rb, spec/models/payment_history/history_spec.rb, spec/requests/payment_history/payment_history_details_spec.rb, spec/services/users_management/users_spec.rb, yarn.lock
https://eaflood.atlassian.net/browse/CAZB-2166
=> [CAZB-2166] Add payment details page

app/forms/company_name_form.rb, config/locales/en.yml, features/organisations.feature, spec/forms/company_name_form_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZ-2962
Updated account name validation messages
=> [CAZ-2962] Update Company Name validation messages

app/forms/new_password_form.rb, config/locales/en.yml, features/password_reset.feature, features/users_management/account_set_up.feature
=> [CAZ-2966] update error message content and ordering

app/controllers/payment_history/payment_history_controller.rb, spec/requests/users_management/users/index_spec.rb
=> Use double pipe and add test

app/views/static_pages/privacy_notice.html.haml
Jira card: https://eaflood.atlassian.net/browse/CAZB-2283
Updated the text in Privacy Notice.
=> [CAZB-2283] Remove DD info from Privacy Notice

app/helpers/users_helper.rb, app/services/users_management/users.rb, app/views/users_management/users/index.html.haml, spec/services/users_management/users_spec.rb
https://eaflood.atlassian.net/browse/CAZ-2400
=> [CAZ-2400] Show himself on the list but without Change link

app/controllers/payment_history/payment_history_controller.rb, features/payment_history.feature, features/step_definitions/payment_history_steps.rb
https://eaflood.atlassian.net/browse/CAZB-2222
=> [CAZB-2222] Hide `payment made by` on payment details history page

app/controllers/application_controller.rb
=> [CAZB-2687] Correct basic auth usage

app/controllers/application_controller.rb, app/controllers/payment_history/payment_history_controller.rb, features/payment_history.feature, features/step_definitions/payment_history_steps.rb
Do not merge until regression testing has been completed on v.1.1.0.
=> Update ST v1.2 with develop (selected commits)

.env.test, Dockerfile.test, app/javascript/styles/application.scss
https://eaflood.atlassian.net/browse/CAZB-2271
=> [CAZB-2271] Fix button url width on print page

.env.example, app/controllers/direct_debits/debits_controller.rb, app/helpers/application_helper.rb, app/helpers/users_helper.rb, app/javascript/styles/application.scss, app/views/dashboard/_make_payment.html.haml, app/views/dashboard/index.html.haml, app/views/users_management/create_users/add_permissions.html.haml, app/views/users_management/create_users/new.html.haml, app/views/users_management/edit_users/edit.html.haml, config/application.rb, features/owner_dashboard.feature, features/step_definitions/dashboard_steps.rb, features/step_definitions/debits_steps.rb, features/support/mock_fleet.rb, spec/requests/direct_debits/debits/create_spec.rb, spec/requests/direct_debits/debits/index_spec.rb, spec/requests/direct_debits/debits/new_spec.rb, spec/support/mocked_responses.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-2286
Added new configuration variable
Updated the content to be updated based on the variable if Direct Debit feature is enabled. 
Disabled: 
Enabled:
=> [CAZB-2286] Make direct debits content dynamic

app/controllers/application_controller.rb, app/models/direct_debits/debit.rb, features/debits.feature, features/step_definitions/debits_steps.rb, features/step_definitions/payments_steps.rb, spec/fixtures/responses/debits/active_mandates.json, spec/fixtures/responses/debits/inactive_mandates.json, spec/fixtures/responses/debits/mandates.json, spec/models/direct_debits/debit_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2645
=> [CAZB-2645] Hide disabled CAZes on Set up a Direct Debit page

app/controllers/payments/payments_controller.rb, features/payments.feature, features/step_definitions/payments_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, spec/requests/payments/payments/select_payment_method_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-2285
Added logic to skip select payment method step if DirectDebits are disabled. 
Tried to make a payment for all AC in the card. 
N/A
=> [CAZB-2285] Add business logic for direct debit feature toggle

.drone2.yml
Correct Production plan step in drone pipeline (correction of task pointer) in PR event
=> Correct Production plan step

.drone.yml, .drone2.yml
https://eaflood.atlassian.net/browse/CAZB-2037
Updated env variable.
=> [CAZB-2037] Survey Link Update - Qualtrics (Production)

.drone2.yml, app/javascript/styles/application.scss
QA suggestion to don't wrap No charge text.
=> [CAZB-2641] Fix table style

.drone.yml, .drone2.yml, app/controllers/application_controller.rb, app/controllers/payments/payments_controller.rb, app/javascript/styles/application.scss, app/models/clean_air_zone.rb, app/models/direct_debits/debit.rb, app/views/payments/payments/failure.html.haml, app/views/vehicles_management/fleets/index.html.haml, features/debits.feature, features/payments.feature, features/step_definitions/debits_steps.rb, features/step_definitions/payments_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/vehicles_management/fleets.feature, spec/fixtures/responses/debits/active_mandates.json, spec/fixtures/responses/debits/inactive_mandates.json, spec/fixtures/responses/debits/mandates.json, spec/models/clean_air_zones_spec.rb, spec/models/direct_debits/debit_spec.rb, spec/requests/payments/payments/select_payment_method_spec.rb
=> Update RC with develop

app/views/vehicles_management/fleets/index.html.haml
Jira card: https://eaflood.atlassian.net/browse/CAZB-2580
Updated link to external link.
=> [CAZB-2580] Fix Open link in new window for Upcoming CAZ

app/views/vehicles_management/uploads/_description.html.haml
[CAZB-2100] Remove content noting no upload file size restriction as this is now set to 50MB.
=> [CAZB-2100] Remove content noting no upload file size restriction

app/views/direct_debits/debits/new.html.haml, features/debits.feature
Jira card: https://eaflood.atlassian.net/browse/CAZB-2903
Updated text and tests.
=> [CAZB-2903] Add copy to DD selection screen

config/locales/en.yml, features/password_reset.feature, features/users_management/account_set_up.feature
https://eaflood.atlassian.net/browse/CAZB-2330
=> [CAZB-2330] Update password policy

.drone2.yml
fix for basic auth and password complexity improvements
=> fixed variables

app/views/direct_debits/debits/new.html.haml, features/debits.feature
=> Update RC with selected commits

app/views/layouts/_footer.html.haml, app/views/static_pages/privacy_notice.html.haml, app/views/vehicles_management/fleets/delete.html.haml
https://eaflood.atlassian.net/browse/CAZB-2666
https://eaflood.atlassian.net/browse/CAZB-2610
https://eaflood.atlassian.net/browse/CAZB-2792
=> [CAZB-2666] [CAZB-2792] [CAZB-2610] Accounts content updates

features/static_pages.feature, features/users_management/account_set_up.feature
=> [CAZB-2610]  Update integration tests for privacy notice

app/views/static_pages/privacy_notice.html.haml
=> [CAZB-2610] remove capital letters in privacy notice

app/controllers/application_controller.rb, app/controllers/vehicles_management/uploads_controller.rb, config/initializers/redis.rb, features/step_definitions/vehicles_management/uploads_step.rb, spec/requests/vehicles_management/uploads/create_spec.rb, spec/requests/vehicles_management/uploads/processing_spec.rb
=> Fix redis initializer

app/controllers/vehicles_management/uploads_controller.rb, app/controllers/vehicles_management/vehicles_controller.rb, features/vehicles_management/uploads.feature, spec/requests/vehicles_management/fleets/index_spec.rb, spec/requests/vehicles_management/uploads/processing_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2866
Remove duplicated code, because on 2nd step we again check status and assign flash message, also I added more tests
=> [CAZB-2866] Remove duplicated code and add more tests

app/controllers/sessions_controller.rb
=> Fix firefox bug when using the sign out page

app/controllers/sessions_controller.rb
=> Revert "Fix firefox bug when using the sign out page"

app/controllers/application_controller.rb, app/controllers/concerns/chargeability_calculator.rb, app/controllers/payments/payments_controller.rb, app/controllers/vehicles_management/fleets_controller.rb, app/controllers/vehicles_management/uploads_controller.rb, features/step_definitions/vehicles_management/uploads_step.rb, spec/requests/vehicles_management/fleets/index_spec.rb, spec/requests/vehicles_management/uploads/processing_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2933
=> [CAZB-2933] Change upload job statuses

app/controllers/concerns/chargeability_calculator.rb, spec/requests/vehicles_management/fleets/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2933
We need to clear job data from redis in case if job not exists in api db
=> [CAZB-2933] Delete job data from redis if api returns 404 error

config/locales/en.yml, features/users_management/account_set_up.feature
https://eaflood.atlassian.net/browse/CAZB-2330?focusedCommentId=237196
=> [CAZB-2330] Password hint typo fix

app/controllers/dashboard_controller.rb, app/models/user.rb, app/views/dashboard/_update_password_notice.html.haml, app/views/dashboard/index.html.haml, features/dashboard/owner_dashboard.feature, features/step_definitions/dashboard_steps.rb, features/support/sign_in_helper.rb, spec/requests/dashboard_spec.rb, spec/support/users_factory.rb
https://eaflood.atlassian.net/browse/CAZB-2606
Manually (`AccountsAPI.sign_in` response has to be mocked to contain `'passwordUpdateTimestamp' => '2020-06-05 00:00:00'` or other date)
rspec, cucumber
Today: `2020-09-02`
Password update date: `2020-06-14`:
Password update date: `2020-06-10`:
Password update date: `2020-06-05`:
=> [CAZB-2606] Update password notice on Dashboard page

app/views/vehicles_management/uploads/calculating_chargeability.html.haml
https://eaflood.atlassian.net/browse/CAZB-2933
=> [CAZB-2933] Fix typo

config/application.rb
Fix deploy
http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Fleets-UI/431/1/9
=> Revert deleted sprockets files

app/controllers/payments/payments_controller.rb, app/views/payments/payments/index.html.haml, app/views/payments/payments/review.html.haml, features/debits.feature, features/organisations.feature, features/payments.feature, features/step_definitions/helper_steps.rb, features/step_definitions/payments_steps.rb, features/vehicles_management/vehicles.feature
https://eaflood.atlassian.net/browse/CAZB-2847
=> [CAZB-2847] Fix back button on CAZ selection and Select payment method pages

app/controllers/dashboard_controller.rb, app/controllers/logout_controller.rb, spec/requests/dashboard_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2847
=> [CAZB-2847] Release lock when user returns to the dashboard

app/controllers/concerns/caz_lock.rb, app/controllers/direct_debits/debits_controller.rb, app/controllers/payments/payments_controller.rb, features/debits.feature, features/payments.feature, features/step_definitions/payments_steps.rb, spec/requests/direct_debits/debits/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2847
=> [CAZB-2847] Release CAZ lock on success payment page

app/views/users_management/create_users/new.html.haml
https://eaflood.atlassian.net/browse/CAZB-2977
Change text according to jira issue
Manually
=> [CAZB-2977] Accounts - small text change

app/views/devise/sessions/logout_notice.html.haml, app/views/devise/sessions/sign_out.html.haml, app/views/layouts/_navbar.haml, app/views/passwords/email_sent.html.haml, config/locales/en.yml, features/organisations.feature, features/sign_in.feature, features/step_definitions/sign_in_steps.rb
https://eaflood.atlassian.net/browse/CAZB-2897 - parent main issue
https://eaflood.atlassian.net/browse/CAZB-2898
https://eaflood.atlassian.net/browse/CAZB-2899
https://eaflood.atlassian.net/browse/CAZB-2900
https://eaflood.atlassian.net/browse/CAZB-2901
https://eaflood.atlassian.net/browse/CAZB-2902
https://eaflood.atlassian.net/browse/CAZB-2942
Change text according to Jira issues
Manually, correct existing tests
=> [CAZB-2897] Accounts - Small text changes

Gemfile.lock, app/api_wrappers/fleets_api.rb, app/controllers/vehicles_management/uploads_controller.rb, app/controllers/vehicles_management/vehicles_controller.rb, spec/api_wrappers/accounts_api/account_spec.rb, spec/api_wrappers/fleets_api/register_job_spec.rb, spec/helpers/application_helpers_spec.rb, spec/models/manage_vehicles/fleet_spec.rb, spec/models/user_management/edit_user_spec.rb, spec/models/user_management/user_spec.rb, spec/requests/dashboard_spec.rb, spec/requests/direct_debits/debits/success_spec.rb, spec/requests/payments/credit_cards/result_spec.rb, spec/requests/payments/payments/clear_search_spec.rb, spec/requests/payments/payments/in_progress_spec.rb, spec/requests/payments/payments/index_spec.rb, spec/requests/payments/payments/matrix_spec.rb, spec/requests/users_management/create_users/create_spec.rb, spec/requests/vehicles_management/fleets/index_spec.rb, spec/requests/vehicles_management/uploads/create_spec.rb, spec/requests/vehicles_management/vehicles/details_spec.rb, spec/services/organisations/create_user_account_spec.rb, spec/support/mocked_responses.rb
https://eaflood.atlassian.net/browse/CAZB-2995
=> [CAZB-2995] Dispatch upload job with no email notification for smaller fleet

app/models/vehicles_management/vehicle.rb, spec/models/manage_vehicles/vehicle_spec.rb
Fixed issue to display 'Undermined' instead of 'No charge' if charge is not present in the API response.
=> [CAZB-3039] Fix Undetermined vehicles on manage fleet page

app/controllers/payments/payments_controller.rb, features/payments.feature
https://eaflood.atlassian.net/browse/CAZB-2847
=> [CAZB-2847] Fix back button on local authority page

app/views/vehicles_management/vehicles/incorrect_details.html.haml
https://eaflood.atlassian.net/browse/CAZB-2873
=> [CAZB-2873] Text change on incorrect vehicle details page

app/views/vehicles_management/vehicles/not_found.html.haml, spec/helpers/application_helpers_spec.rb, spec/helpers/payments_helpers_spec.rb, spec/requests/organisations/email_verification_spec.rb, spec/requests/passwords/reset_spec.rb, spec/services/organisations/create_account_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2874
=> [CAZB-2874] Text change on vehicle not found page

Gemfile, Gemfile.lock
=> Bump Rails version to 6.0.3.3

spec/requests/logout_spec.rb
=> [NON-JIRA] Logout controller tests

app/controllers/dashboard_controller.rb
=> Do not perform api call if direct debits disabled on the dashboard page

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb
https://eaflood.atlassian.net/browse/CAZB-3002
=> [CAZB-3002] Disable cache on the dashboard page

app/controllers/vehicles_management/fleets_controller.rb
https://eaflood.atlassian.net/browse/CAZB-3002
After upload vehicles in Firefox page, still cached with old vehicles.
=> [CAZB-3002] Disable cache on the Manage your vehicles page

app/views/payments/payments/in_progress.html.haml
=> [NON-JIRA] correct typo in lock screen

app/controllers/payments/payments_controller.rb, features/payments.feature
=> [NON-JIRA] fix typo

app/views/vehicles_management/vehicles/incorrect_details.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml, spec/helpers/application_helpers_spec.rb, spec/helpers/payments_helpers_spec.rb, spec/requests/organisations/email_verification_spec.rb, spec/requests/passwords/reset_spec.rb, spec/services/organisations/create_account_spec.rb
@likeuwill the changes for the refund wording are being reverted out for now, but I notice there are a number of other changes in one of these commits. Could these be committed separately?
=> Revert [CAZB-2873 | CAZB-2874]

app/api_wrappers/fleets_api.rb, app/models/vehicles_management/fleet.rb, app/views/vehicles_management/fleets/index.html.haml, features/step_definitions/vehicles_management/fleets_steps.rb, features/support/mock_fleet.rb, features/vehicles_management/fleets.feature, spec/fixtures/responses/vehicles.json, spec/models/manage_vehicles/fleet_spec.rb, spec/support/fleet_factory.rb
https://eaflood.atlassian.net/browse/CAZB-3138
Parent: https://eaflood.atlassian.net/browse/CAZB-3058
Manually, rspec, cucumber
No undetermined vehicles:
=> [CAZB-3138] Vehicle management - Content refinements

config/initializers/amazon_s3_client.rb, config/initializers/content_security_policy.rb, config/initializers/redis.rb, config/initializers/webpacker.rb, sonar-project.properties
We're already ignoring lib and config folders when checking code coverage by simplecov, so i removed `nocov` setting.
```
add_filter %w[
app/models/application_record.rb
lib/
config/
]
```
Same for sonar, we're scanning only `app` folder.
=> Remove unused settings for simplecov and sonar

app/models/direct_debits/debit.rb, app/models/direct_debits/mandate.rb, spec/fixtures/responses/debits/active_mandates.json, spec/models/direct_debits/mandate_spec.rb, spec/requests/direct_debits/debits/new_spec.rb
=> Support new statuses for Direct Debit

app/models/direct_debits/debit.rb
=> Refactor Direct Debits select active status method

app/controllers/account_details/non_primary_users_controller.rb, app/controllers/account_details/primary_users_controller.rb, app/views/account_details/non_primary_users/index.html.haml, app/views/account_details/primary_users/index.html.haml, app/views/layouts/_navbar.haml, config/routes.rb, spec/requests/account_details/non_primary_users/index_spec.rb, spec/requests/account_details/primary_users/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2633
* Created link which redirects user based on his `owner` property.
* Prepared controllers for different kind of users.
Manually + rspec.
=> [CAZB-2633] Account details link on dashboard

app/controllers/vehicles_management/uploads_controller.rb, spec/requests/vehicles_management/uploads/processing_spec.rb
=> Clears upload job from redis when upload failed

app/models/direct_debits/mandate.rb, spec/models/direct_debits/mandate_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3187
=> [CAZB-3187] Map `Submitted` Direct Debit status to `Pending`

app/helpers/fleets_helper.rb, app/views/vehicles_management/fleets/_pagination.html.haml, app/views/vehicles_management/fleets/_pagination_button.html.haml, features/vehicles_management/fleets.feature, spec/helpers/fleets_helpers_spec.rb
Jira issue: https://eaflood.atlassian.net/browse/CAZB-3054
Change the look and way how pagination works on fleets management page
Manually
=> [CAZB-3054] Vehicle management page - Pagination control updates

app/api_wrappers/accounts_api.rb, app/controllers/account_details/names_controller.rb, app/forms/account_details/edit_user_name_form.rb, app/forms/organisations/company_name_form.rb, app/javascript/packs/application.js, app/javascript/src/backLink/init.js, app/views/account_details/names/edit.html.haml, app/views/account_details/non_primary_users/edit_name.html.haml, app/views/layouts/_navbar.haml, app/views/shared/_js_back_link.html.haml, config/locales/en.yml, config/routes.rb, features/account_details/non_primary_user.feature, features/step_definitions/account_details/non_primary_user_steps.rb, features/support/mock_users.rb, spec/api_wrappers/accounts_api/update_user_spec.rb, spec/forms/account_details/edit_user_name_form_spec.rb, spec/forms/organisations/company_name_form_spec.rb, spec/requests/account_details/names/edit_spec.rb, spec/requests/account_details/names/update_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2819
* Added new form for non-primary user name change.
* Added js-back link to the project
* Sign in as non-primary user
* Go to `Account details` tab
* Verify name changing process
=> [CAZB-2819] Update name page

app/forms/base_form.rb
https://eaflood.atlassian.net/browse/CAZB-3063
=> CAZB-3063 validating user with the default Ruby email regex

app/controllers/dashboard_controller.rb, app/controllers/payments/payments_controller.rb, app/controllers/users_management/create_users_controller.rb, app/views/payments/payments/review.html.haml, app/views/payments/payments/select_payment_method.html.haml, app/views/users_management/create_users/new.html.haml, spec/requests/users_management/create_users/new_spec.rb
=> Clear checkbox input on the review page after successful payment

spec/requests/passwords/create_spec.rb
=> Temporary skip rspec test

config/initializers/amazon_s3_client.rb
=> Fix - Enable S3 connection on local environment through STS Assume Role

app/views/vehicles_management/fleets/_pagination.html.haml
Jira comment: https://eaflood.atlassian.net/browse/CAZB-3054?focusedCommentId=242695
Fix AC 1 for less than 13 pages
Manually
=> [CAZB-3054] Not show pagination when there is only one page

features/step_definitions/account_details/non_primary_user_steps.rb, features/step_definitions/account_details/primary_user_steps.rb, spec/forms/users_management/add_user_form_spec.rb, spec/requests/users_management/create_users/confirm_permissions_spec.rb, spec/requests/users_management/create_users/create_spec.rb
=> [CAZB-3063] Add tests

app/controllers/static_pages_controller.rb, app/views/static_pages/accessibility_statement.html.haml, app/views/static_pages/cookies.html.haml, app/views/static_pages/privacy_notice.html.haml, features/payment_history.feature, features/users_management/account_set_up.feature, features/users_management/manage_users.feature
https://eaflood.atlassian.net/browse/CAZB-2637?focusedCommentId=242925
Changed static page back links to be js driven
Manually
=> [CAZB-2850] Account management - update password back link fix

app/controllers/direct_debits/debits_controller.rb, spec/requests/dashboard_spec.rb, spec/requests/direct_debits/debits/complete_setup_spec.rb, spec/requests/vehicles_management/fleets/assign_delete_spec.rb, spec/requests/vehicles_management/fleets/confirm_delete_spec.rb, spec/requests/vehicles_management/vehicles/add_to_fleet_spec.rb, spec/requests/vehicles_management/vehicles/confirm_and_add_exempt_vehicle_to_fleet_spec.rb, spec/requests/vehicles_management/vehicles/confirm_details_spec.rb, spec/requests/vehicles_management/vehicles/confirm_not_found_spec.rb, spec/requests/vehicles_management/vehicles/submit_details_spec.rb, spec/support/shared_examples/login_required.rb, spec/support/shared_examples/vrn_required_view.rb
https://eaflood.atlassian.net/browse/CAZB-3080
=> [CAZB-3080] Redirect to the debits page when submit mandate  twice

app/controllers/payments/payments_controller.rb, spec/requests/payments/payments/matrix_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3184
* Error was caused by the missing `@fleet` variable when entering the payment matrix
=> [CAZB-3184] Payment matrix after fleet upload fix

config/routes.rb, lib/custom_logger.rb, lib/tasks/rdoc.rake
Before that changes we can't to run `rails rdoc` with that [config](https://github.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/blob/develop/lib/tasks/rdoc.rake), now all works fine
=> Add rdoc configuration

app/api_wrappers/account_details/api.rb, app/api_wrappers/accounts_api.rb, app/controllers/account_details/emails_controller.rb, app/forms/account_details/edit_user_email_form.rb, app/views/account_details/emails/edit.html.haml, app/views/account_details/primary_users/primary_account_details.html.haml, config/locales/en.yml, config/routes.rb, spec/api_wrappers/account_details/change_owner_email_spec.rb, spec/forms/account_details/edit_user_email_form_spec.rb, spec/requests/account_details/emails/edit_spec.rb, spec/requests/account_details/emails/update_spec.rb, spec/requests/account_details/names/update_spec.rb, yarn.lock
https://eaflood.atlassian.net/browse/CAZB-2856
* Added update email page for the account owner
* Feature specs will be provided in CAZB-2640 card
=> [CAZB-2856] Update email page

app/controllers/concerns/chargeability_calculator.rb, app/controllers/payments/payments_controller.rb, spec/requests/payments/payments/local_authority_spec.rb, spec/requests/payments/payments/matrix_spec.rb, spec/requests/vehicles_management/fleets/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3184
=> [CAZB-3184] Fix when making payment whilst upload is processing

app/api_wrappers/accounts_api.rb, app/controllers/vehicles_management/fleets_controller.rb, app/views/vehicles_management/fleets/index.html.haml, config/routes.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/vehicles_management/fleets.feature, spec/api_wrappers/accounts_api/csv_exports_spec.rb, spec/requests/vehicles_management/fleets/export_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3163
Parent: https://eaflood.atlassian.net/browse/CAZB-3059
Implemented an Export CSV link that fetches the csv file location from api and redirects to it
Rspec, cucumber.
API is not yet implemented for this feature
After click:
=> [CAZB-3163] Fleet CSV export button

config/locales/en.yml, features/account_details/primary_user.feature, features/organisations.feature, features/step_definitions/account_details/primary_user_steps.rb
https://eaflood.atlassian.net/browse/CAZB-2823
Updated error message: https://eaflood.atlassian.net/browse/CAZB-2638?focusedCommentId=244288
Update error message when given name is too long
Manually, cucumber
=> [CAZB-2823] Update company name page - length validation error

app/views/direct_debits/debits/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3225
Text change
=> [CAZB-3225] Direct Debits - Content Update

.rubocop.yml, app/api_wrappers/api_exception.rb, app/api_wrappers/base_api.rb, app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/forms/base_form.rb, app/helpers/application_helper.rb, app/helpers/fleets_helper.rb, app/helpers/payments_helper.rb, app/helpers/users_helper.rb, app/services/session_manipulation/base_manipulator.rb, config/application.rb, features/step_definitions/sign_in_steps.rb, features/support/helpers.rb, features/support/mock_debit.rb, features/support/mock_fleet.rb, features/support/mock_payments.rb, features/support/mock_users.rb, features/support/mock_vccs.rb, features/support/sign_in_helper.rb, lib/devise/models/remote_authenticatable.rb, spec/forms/users_management/add_user_form_spec.rb, spec/requests/sign_in_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3273
https://eaflood.atlassian.net/browse/CAZB-3063
=> [CAZB-3273] Change email regexp

app/controllers/payments/payments_controller.rb, features/vehicles_management/uploads.feature, spec/requests/payments/payments/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3184
=> [CAZB-3184] Check upload job status on the CAZ selection page

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/payments/credit_cards_controller.rb, app/controllers/payments/payments_controller.rb, app/services/session_manipulation/add_current_payment.rb
https://eaflood.atlassian.net/browse/CAZB-3061
=> [CAZB-3061] Fix 500 error on Enter Card Details page

.drone2.yml
Builds have been noted to fail after release of aosapps/drone-sonar-plugin 1.1 to Docker Hub (https://hub.docker.com/r/aosapps/drone-sonar-plugin/tags). This PR pins the sonar scan step to the known working v1.0.
See motivation and context
PR pipeline steps run with sonar scan successful.
=> Update .drone2.yml to use fixed sonar image version

app/views/account_details/emails/confirm_email.html.haml, app/views/account_details/emails/edit_email.html.haml, app/views/account_details/names/edit_name.html.haml, app/views/account_details/non_primary_users/non_primary_account_details.html.haml, app/views/account_details/organisation_names/edit_name.html.haml, app/views/account_details/passwords/edit.html.haml, app/views/account_details/primary_users/primary_account_details.html.haml
=> Add id's for the account details flow

app/views/layouts/_footer.html.haml, features/static_pages.feature
https://eaflood.atlassian.net/browse/CAZB-3279
=> [CAZB-3279] Update privacy label

app/controllers/vehicles_management/uploads_controller.rb, app/services/vehicles_management/upload_file.rb, spec/requests/vehicles_management/uploads/processing_spec.rb, spec/services/vehicles_management/upload_file_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3118
Error was being catched at different request (`upload_to_s3`) and was not working correctly.
Switched to catch the error on `processing` request
=> [CAZB-3118] Fixed CSV upload lambda timeout error

app/views/account_details/emails/confirm_email.html.haml
https://eaflood.atlassian.net/browse/CAZB-2669
=> [CAZB-2669] Update label text on the confirm email page

app/controllers/account_details/emails_controller.rb, spec/requests/account_details/emails/edit_email_spec.rb, spec/requests/account_details/emails/update_email_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2639
=> [CAZB-2639] Redirect to the account details when save no changes

app/javascript/styles/application.scss, app/views/account_details/emails/email_sent.html.haml
https://eaflood.atlassian.net/browse/CAZB-2640
Class is added after a click that prevents the link to be clicked again
=> [CAZB-2640] Allow resend email only once

app/views/organisations/organisations/cannot_create.html.haml, app/views/organisations/organisations/fleet_check.html.haml, app/views/organisations/organisations/new.html.haml, config/locales/en.yml, features/account_details/primary_user.feature, features/organisations.feature, features/step_definitions/organisations_steps.rb
https://eaflood.atlassian.net/browse/CAZB-3236
https://eaflood.atlassian.net/browse/CAZB-3237
https://eaflood.atlassian.net/browse/CAZB-3237
=> [CAZB: 3236, 3237, 3238] Update content

app/javascript/packs/export_button_notice.js, app/javascript/styles/application.scss, app/views/account_details/emails/email_sent.html.haml, app/views/vehicles_management/fleets/index.html.haml
=> Update RC selected commits

app/javascript/packs/payment_matrix.js, app/javascript/src/payment_matrix/initSearch.js, app/javascript/src/payment_matrix/submitForm.js, app/views/payments/payments/matrix.html.haml, app/views/payments/payments/matrix/_search.html.haml
https://eaflood.atlassian.net/browse/CAZB-2668
Moved the search panel below the payment matrix.
Had to remove form since forms can't be used inside other forms.
Manually
----
=> [CAZB-2688] Search optimisation - Update matrix search

app/views/account_details/emails/edit_email.html.haml, features/account_details/emails.feature
https://eaflood.atlassian.net/browse/CAZB-2639
Made only content changes.
Too long email validation will be made in another ticket, as per the comment https://eaflood.atlassian.net/browse/CAZB-2639?focusedCommentId=246799
=> [CAZB-2639] Fixed update email address page labels

Dockerfile.test, Gemfile, Gemfile.lock, app/api_wrappers/fleets_api.rb, app/api_wrappers/payment_history_api.rb, app/controllers/application_controller.rb, app/controllers/vehicles_management/fleets_controller.rb, app/models/vehicles_management/fleet.rb, app/services/organisations/verify_account.rb, app/views/passwords/index.html.haml, app/views/vehicles_management/fleets/_pagination.html.haml, app/views/vehicles_management/fleets/index.html.haml, config/i18n-tasks.yml, config/locales/en.yml, spec/api_wrappers/fleets_api/vehicles_spec.rb, spec/helpers/payments_helpers_spec.rb, spec/i18n_spec.rb, spec/models/manage_vehicles/fleet_spec.rb, spec/requests/dashboard_spec.rb, spec/requests/organisations/email_verification_spec.rb, spec/spec_helper.rb
https://eaflood.atlassian.net/browse/CAZB-3257
**98.88% covered**
=> [CAZB-3257] Add 'onlyChargeable' toggle on the Fleet management page

app/api_wrappers/fleets_api.rb
Fix bug 
https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fdl.dropbox.com%2Fs%2Ftqgo5kjbhusjfvz%2Fshot_201015_141447.png
=> Set `only_chargeable` default as false

app/views/devise/sessions/sign_out.html.haml, app/views/organisations/organisations/email_verified.haml, config/locales/en.yml, features/organisations.feature, features/sign_in.feature
https://eaflood.atlassian.net/browse/CAZB-3267
https://eaflood.atlassian.net/browse/CAZB-3268
https://eaflood.atlassian.net/browse/CAZB-3239
https://eaflood.atlassian.net/browse/CAZB-3267:
----
https://eaflood.atlassian.net/browse/CAZB-3268:
----
https://eaflood.atlassian.net/browse/CAZB-3239:
=> [CAZB-3267 3268 3239] Sign in/out pages content changes

app/models/user.rb, app/views/dashboard/_company_payment_history.html.haml, app/views/payment_history/payment_history/company_payment_history.html.haml, app/views/users_management/create_users/new.html.haml, app/views/users_management/edit_users/edit.html.haml, app/views/vehicles_management/fleets/delete.html.haml, app/views/vehicles_management/fleets/submission_method.html.haml, config/locales/en.yml, features/payments.feature, features/step_definitions/dashboard_steps.rb, features/step_definitions/payment_history_steps.rb, features/step_definitions/users_management/manage_users_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/support/mock_users.rb, features/users_management/edit_user.feature, spec/requests/organisations/email_sent_spec.rb, spec/requests/organisations/resend_email_spec.rb, spec/requests/payment_history/company_payment_history_spec.rb, spec/requests/sign_in_spec.rb, spec/requests/users_management/create_users/create_spec.rb, spec/requests/users_management/create_users/new_spec.rb, spec/requests/vehicles_management/fleets/delete_spec.rb, spec/requests/vehicles_management/fleets/submission_method_spec.rb, spec/requests/vehicles_management/fleets/submit_method_spec.rb, spec/support/users_factory.rb
https://eaflood.atlassian.net/browse/CAZB-3287
https://eaflood.atlassian.net/browse/CAZB-3289
https://eaflood.atlassian.net/browse/CAZB-3296
https://eaflood.atlassian.net/browse/CAZB-3299
=> [CAZB: 3287, 3289, 3296, 3299] Update content

app/javascript/src/payment_matrix/initPaginationButton.js, app/javascript/src/payment_matrix/initSearch.js, app/javascript/src/payment_matrix/submitForm.js
https://eaflood.atlassian.net/browse/CAZB-2668?focusedCommentId=246992
Fixed pagination buttons
=> [CAZB-2668] Update matrix search - fix pagination

app/views/dashboard/_help.html.haml, app/views/dashboard/index.html.haml, app/views/layouts/_navbar.haml, app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3379
https://eaflood.atlassian.net/browse/CAZB-3381
Added links leading to Help page
https://eaflood.atlassian.net/browse/CAZB-3379:
---
https://eaflood.atlassian.net/browse/CAZB-3381:
=> [CAZB-3379, 3381] Add links to Help page

app/views/payments/payments/matrix/_details.html.haml, app/views/payments/payments/matrix/_heading.html.haml, app/views/payments/payments/matrix/_no_chargeable_vehicles.html.haml, app/views/payments/payments/review.html.haml, features/payments.feature
https://eaflood.atlassian.net/browse/CAZB-3293
https://eaflood.atlassian.net/browse/CAZB-3294
https://eaflood.atlassian.net/browse/CAZB-3295
https://eaflood.atlassian.net/browse/CAZB-3293:
---
https://eaflood.atlassian.net/browse/CAZB-3294:
---
https://eaflood.atlassian.net/browse/CAZB-3295:
=> [CAZB-3293, 3294, 3295] Content changes

app/controllers/users_management/users_controller.rb, app/views/users_management/users/index.html.haml, app/views/vehicles_management/vehicles/incorrect_details.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml, features/users_management/manage_users.feature, features/vehicles_management/vehicles.feature, spec/requests/users_management/users/index_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3290
https://eaflood.atlassian.net/browse/CAZB-3292
https://eaflood.atlassian.net/browse/CAZB-3298
https://eaflood.atlassian.net/browse/CAZB-3290:
---
https://eaflood.atlassian.net/browse/CAZB-3292:
---
https://eaflood.atlassian.net/browse/CAZB-3298:
=> [CAZB-3290, 3292, 3298] Content changes

spec/models/user_spec.rb, spec/requests/payments/payments/no_chargeable_vehicles_spec.rb, spec/requests/payments/payments/review_spec.rb, spec/requests/sign_in_spec.rb
=> Add missing tests

app/controllers/payments/payments_controller.rb, spec/requests/payments/payments/confirm_payment_method_spec.rb, spec/requests/payments/payments/confirm_review_spec.rb, spec/requests/payments/payments/failure_spec.rb, spec/requests/payments/payments/index_spec.rb, spec/requests/payments/payments/matrix_spec.rb, spec/requests/payments/payments/post_payment_details_spec.rb, spec/requests/payments/payments/review_details_spec.rb, spec/requests/payments/payments/success_spec.rb, spec/support/chargeable_vehicles_factory.rb, spec/support/shared_examples/payment_result_page.rb
=> Add PaymentsController tests

app/views/dashboard/_direct_debit.html.haml, app/views/dashboard/_manage_vehicles.html.haml, app/views/dashboard/index.html.haml, app/views/layouts/_navbar.haml, app/views/vehicles_management/fleets/index.html.haml, features/dashboard/owner_dashboard.feature, features/dashboard/user_dashboard.feature, features/passwords/password_update.feature, features/sign_in.feature, features/step_definitions/debits_steps.rb, features/step_definitions/helper_steps.rb, features/step_definitions/password_reset_steps.rb, features/step_definitions/payments_steps.rb, features/step_definitions/sign_in_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/step_definitions/vehicles_management/uploads_step.rb, features/step_definitions/vehicles_management/vehicles_steps.rb, features/vehicles_management/fleets.feature, features/vehicles_management/uploads.feature, spec/requests/dashboard_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3259
https://eaflood.atlassian.net/browse/CAZB-3260
=> [CAZB-3259, 3260] Content changes

config/locales/en.yml
=> Update RC  - remove duplicate content from previous merge

app/views/direct_debits/debits/index.html.haml, app/views/payments/payments/failure.html.haml, app/views/payments/payments/no_chargeable_vehicles.html.haml, app/views/vehicles_management/uploads/calculating_chargeability.html.haml
https://eaflood.atlassian.net/browse/CAZB-3304
https://eaflood.atlassian.net/browse/CAZB-3311
https://eaflood.atlassian.net/browse/CAZB-3314
=> [CAZB: 3304, 3311, 3314] Update content

app/controllers/account_details/emails_controller.rb, app/forms/account_details/edit_user_email_form.rb, app/views/account_details/emails/edit_email.html.haml, config/initializers/filter_parameter_logging.rb, config/locales/en.yml, features/account_details/emails.feature, features/step_definitions/account_details/emails_steps.rb, spec/forms/account_details/edit_user_email_form_spec.rb, spec/requests/account_details/emails/update_email_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3385
Added confirmation input and validations
Manually, rspec, cucumber
AC6:
---
AC7:
---
AC8:
---
AC9:
---
AC10:
---
AC11:
=> [CAZB-3385] Add confirmation input to edit password page

app/models/payment_history/details.rb, app/views/payment_history/payment_history/payment_history_details.html.haml, spec/models/payment_history/details_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3353
Text change (to `Payment ID`) + method name change (to `.provider_payment_id`)
=> [CAZB-3353] Payment ID content adjustment

app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3097
=> [CAZB-3257] Fix typo

app/views/devise/sessions/new.html.haml, app/views/organisations/organisations/new.html.haml
https://eaflood.atlassian.net/browse/CAZB-3446
https://eaflood.atlassian.net/browse/CAZB-3447
=> [CAZB: 3446, 3447] Add links

app/services/account_details/update_email.rb, app/views/account_details/emails/confirm_email.html.haml, config/locales/en.yml, features/account_details/emails.feature, features/step_definitions/account_details/emails_steps.rb, spec/services/account_details/update_email_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3444
Content changes:
1. Page title changed to `Email address change`
2. Token invalid/expired error message changed to `The link has expired. Sign in and go to Account details to change your email address`. Test cases added
=> [CAZB-3444] Update email page content changes

app/views/payments/payments/matrix/_search.html.haml
https://eaflood.atlassian.net/browse/CAZB-2668
=> [CAZB-2668] Updated Clear Search link text

config/locales/en.yml, features/account_details/emails.feature
https://eaflood.atlassian.net/browse/CAZB-3385
=> [CAZB-3385] Update password format error message

app/views/direct_debits/debits/failure.html.haml
https://eaflood.atlassian.net/browse/CAZB-3314
=> [CAZB-3314] Payment unsuccessful - content updates

app/forms/organisations/company_name_form.rb, features/step_definitions/account_details/primary_user_steps.rb, spec/forms/organisations/company_name_form_spec.rb, spec/requests/account_details/organisation_names/update_name_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3460
Parent: https://eaflood.atlassian.net/browse/CAZB-3443
=> [CAZB-3460] Amend validation on Company name

app/views/payments/payments/matrix/_search.html.haml
https://eaflood.atlassian.net/browse/CAZB-2668
Changed link content from `Reset search ...` to `Clear search ...`
=> [CAZB-2668] Fix payment matrix Clear Search link text

app/controllers/vehicles_management/vehicles_controller.rb, app/views/vehicles_management/vehicles/local_exemptions.html.haml, features/vehicles_management/uploads.feature
=> Redirect user to the calculating page if uploading large fleet

app/controllers/concerns/payment_features.rb, app/controllers/organisations/organisations_controller.rb, app/controllers/vehicles_management/fleets_controller.rb, app/views/organisations/organisations/cannot_create.html.haml, app/views/vehicles_management/fleets/_charge_cannot_be_calculated.html.haml, app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3448
=> [CAZB-3448] Manage vehicles - content update for "A-day"

app/controllers/concerns/disable_payment_features.rb, app/controllers/dashboard_controller.rb, app/views/dashboard/_d_day_notice.html.haml, app/views/dashboard/index.html.haml, features/dashboard/owner_dashboard.feature, features/step_definitions/account_details/emails_steps.rb, features/step_definitions/account_details/non_primary_user_steps.rb, features/step_definitions/account_details/primary_user_steps.rb, features/step_definitions/dashboard_steps.rb, features/step_definitions/debits_steps.rb, features/step_definitions/payment_history_steps.rb, features/step_definitions/sign_in_steps.rb, features/step_definitions/users_management/edit_user_steps.rb, features/step_definitions/users_management/manage_users_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/step_definitions/vehicles_management/uploads_step.rb, features/step_definitions/vehicles_management/vehicles_steps.rb, features/support/sign_in_helper.rb, spec/requests/dashboard_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3440
With mocked db value
=> [CAZB-3440] Dashboard A-Day content update

app/views/static_pages/help.html.haml
Update retrofit scheme URL pointer due to 404 error being returned on prior address
=> [CAZB-3499] Update retrofit scheme URL pointer

app/controllers/users_management/edit_users_controller.rb, app/views/dashboard/_d_day_notice.html.haml, app/views/dashboard/_update_password_notice.html.haml, app/views/shared/_warning.html.haml, app/views/users_management/edit_users/_d_day_notice.html.haml, app/views/users_management/edit_users/edit.html.haml, spec/requests/users_management/edit_users/edit_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3449
=> [CAZB-3449] Edit user page A-Day content updates

app/views/direct_debits/debits/new.html.haml, app/views/payments/payments/select_payment_method.html.haml, features/debits.feature
https://eaflood.atlassian.net/browse/CAZB-3464
https://eaflood.atlassian.net/browse/CAZB-3465
https://eaflood.atlassian.net/browse/CAZB-3464:
----
https://eaflood.atlassian.net/browse/CAZB-3465:
=> [CAZB-3464, 3465] CAZ selection page, payment method page content changes

app/views/payments/payments/review.html.haml
We need to update text for the exception informations.
Jira card: https://eaflood.atlassian.net/browse/CAZB-3484
N/A
Tried to make a payment
=> [CAZB-3484] Change exemption wording on tariff page

app/controllers/payments/payments_controller.rb
https://eaflood.atlassian.net/browse/CAZB-3474
=> [CAZB-3474] CAZ selection page - show all zones for beta tester

app/controllers/account_details/emails_controller.rb, app/forms/account_details/edit_user_email_form.rb, spec/forms/account_details/edit_user_email_form_spec.rb, spec/requests/account_details/emails/update_email_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3385?focusedCommentId=249541
=> [CAZB-3385] Update email page - add current email error

app/views/static_pages/help.html.haml
Update retrofit scheme URL pointer due to 404 error being returned on prior address
=> Update RC with selected commit

app/controllers/application_controller.rb
Extends https://github.com/InformedSolutions/JAQU-CAZ-Fleets-UI/commit/26ae3a91e26012fa9a8e11e066e909639deb678e with no-store pragma being set in controller layer
=> [CAZB-3506] Cover no-store pragma in controllers

app/controllers/application_controller.rb, config/environments/production.rb
Layer no-cache pragmas (from cherry-picked commits) stemming from CAZB-3506 into rc v1.5.0
=> Layer no-cache pragmas from CAZB-3506 into rc v1.5.0

app/views/passwords/edit.html.haml
https://eaflood.atlassian.net/browse/CAZB-3288
=> [CAZB-3288] Update title on the password update page

app/controllers/account_details/emails_controller.rb, app/forms/account_details/edit_user_email_form.rb, app/services/vehicles_management/upload_file.rb, features/account_details/emails.feature, features/step_definitions/account_details/emails_steps.rb, spec/requests/account_details/emails/update_email_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3387
=> [CAZB-3387] Show proper error message when api email validation failed

app/views/account_details/emails/edit_email.html.haml
Jira: https://eaflood.atlassian.net/browse/CAZB-3387
Updated max length on email input.
=> [CAZB-3387] Changes email input max length

app/controllers/concerns/payment_features.rb
https://eaflood.atlassian.net/browse/CAZB-3459
Fixed the content when bath a-day is today.
=> [CAZB-3459] Fix A-Day is today for Bath

app/helpers/payments_helper.rb, app/views/payments/payments/review.html.haml, spec/helpers/payments_helpers_spec.rb
Fixed bug reported in comment: 
https://eaflood.atlassian.net/browse/CAZB-3484
On payment review page.
=> [CAZB-3484] Fix exemption link on payment review page

app/controllers/account_details/emails_controller.rb, app/controllers/organisations/organisations_controller.rb, app/controllers/passwords_controller.rb, app/services/session_manipulation/set_new_user.rb, lib/devise/strategies/remote.rb, spec/services/session_manipulation/set_new_user_spec.rb
We need to strip whitespaces from email fields.
Jira card: https://eaflood.atlassian.net/browse/CAZB-3537
Tried to find all places we use email in form.
Jira card: https://eaflood.atlassian.net/browse/CAZB-3537
Tried to add some spaces before and after email.
=> [CAZB-3537] Stripe email whitespaces

app/controllers/relevant_portal_controller.rb, config/application.rb, spec/requests/relevant_portal_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-3475
=> [CAZB-3475] Fix - VCCS url default value based on env variables

app/controllers/relevant_portal_controller.rb, app/views/layouts/_header.html.haml, features/relevant_portal.feature
Jira card: https://eaflood.atlassian.net/browse/CAZB-3475
What would you like to do page should not have navigation menu.
=> [CAZB-3475] Fix navigation menu for 'what would you like to do' page

app/views/relevant_portal/what_would_you_like_to_do.html.haml, features/relevant_portal.feature
Jira card: 
https://eaflood.atlassian.net/browse/CAZB-3475?focusedCommentId=256936
=> [CAZB-3475] Add error message summary to 'What would you like to do' page

app/controllers/relevant_portal_controller.rb, app/views/layouts/_header.html.haml, app/views/relevant_portal/what_would_you_like_to_do.html.haml, features/relevant_portal.feature
Promote dev to ST for CAZB-3475
=> Promote dev to ST for CAZB-3475

app/views/direct_debits/debits/new.html.haml, features/debits.feature
Jira: https://eaflood.atlassian.net/browse/CAZB-3642
=> [CAZB-3642] Update Direct Debit info copy

app/views/direct_debits/debits/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3643
=> [CAZB-3643] Add text to the Direct Debits page

app/views/relevant_portal/what_would_you_like_to_do.html.haml
https://eaflood.atlassian.net/browse/CAZB-3475?focusedCommentId=258286
Added missing comma to the text.
=> [CAZB-3475] Add missing comma to text on the 'what would you like to do page'

app/views/static_pages/privacy_notice.html.haml, features/static_pages.feature
https://eaflood.atlassian.net/browse/CAZB-3529
=> [CAZB-3529] Content update on the Privacy policy page

app/views/direct_debits/debits/new.html.haml
https://eaflood.atlassian.net/browse/CAZB-3642?focusedCommentId=258853
=> [CAZB-3642] Fix typo in the text

app/views/vehicles_management/uploads/_description.html.haml
https://eaflood.atlassian.net/browse/CAZB-3646
=> [CAZB-3646] Content update on CSV upload pages

app/services/vehicles_management/upload_file.rb
https://eaflood.atlassian.net/browse/CAZB-3637
Allow 200k vehicles to be uploaded
=> [CAZB-3637] Validate number of vehicles to be uploaded

app/views/static_pages/privacy_notice.html.haml, features/static_pages.feature
https://eaflood.atlassian.net/browse/CAZB-3529
=> [CAZB-3632] Content update on Privacy Notice page

app/api_wrappers/fleets_api.rb, app/controllers/concerns/caz_lock.rb, app/controllers/vehicles_management/fleets_controller.rb, app/controllers/vehicles_management/vehicles_controller.rb, app/forms/vehicles_management/search_vrn_form.rb, app/forms/vrn_form.rb, app/models/vehicles_management/fleet.rb, app/views/vehicles_management/fleets/_search.html.haml, app/views/vehicles_management/fleets/index.html.haml, app/views/vehicles_management/fleets/vrn_not_found.html.haml, config/routes.rb, spec/forms/vehicles_management/search_vrn_form_spec.rb, spec/forms/vrn_form_spec.rb, spec/models/manage_vehicles/fleet_spec.rb, spec/requests/payments/payments/submit_search_spec.rb, spec/requests/payments/payments/vrn_not_found_spec.rb, spec/requests/vehicles_management/fleets/index_spec.rb, spec/requests/vehicles_management/fleets/submit_search_spec.rb, spec/requests/vehicles_management/fleets/vrn_not_found_spec.rb, spec/support/fleet_factory.rb
https://eaflood.atlassian.net/browse/CAZB-3648
=> [CAZB-3648] Search feature on the Manage vehicles page

app/views/vehicles_management/fleets/_pagination_button.html.haml
https://eaflood.atlassian.net/browse/CAZB-3096
=> [CAZB-3648] Fix pagination when using vrn search

app/views/vehicles_management/fleets/index.html.haml
=> Add id to remove button on fleets page

.drone2.yml
=> added vars capabilities to use charge settlement

app/views/organisations/organisations/new.html.haml, config/routes.rb, features/organisations.feature
https://eaflood.atlassian.net/browse/CAZB-3744
=> [CAZB-3744] Amend LInk on Create Account page to detail T&Cs

app/controllers/static_pages_controller.rb, app/views/layouts/_footer.html.haml, app/views/layouts/disabled_links/_footer.html.haml, app/views/static_pages/terms_and_conditions.html.haml, features/static_pages.feature
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3745
=> [CAZB-3745] Add T&C link to footer on Accounts

.drone2.yml, app/views/static_pages/terms_and_conditions.html.haml, spec/requests/static_pages_spec.rb
Link to JIRA Card: [CAZB-3743](https://eaflood.atlassian.net/browse/CAZB-3743)
=> [CAZB-3743] Terms and Conditions page

app/controllers/users_management/create_users_controller.rb, config/locales/en.yml, features/users_management/manage_users.feature
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3641
Added missing banner with success message.
=> [CAZB-3641] Fix Confirmation banner missing when adding a user

app/views/static_pages/terms_and_conditions.html.haml
=> [CAZB-3743] Uppercase Privacy Notice link

app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3773
=> [CAZB-3773] Hide manage vehicles search input

app/views/users_management/users/index.html.haml, features/users_management/manage_users.feature
https://eaflood.atlassian.net/browse/CAZB-3768
=> [CAZB-3768] Copy change when reached max of 10 users

app/views/users_management/users/index.html.haml, features/users_management/manage_users.feature
=> DRAFT: [CAZB-3768] Copy change when reached max of 10 users

app/views/vehicles_management/fleets/index.html.haml
=> DRAFT: [CAZB-3773] Hide manage vehicles search input

app/views/static_pages/terms_and_conditions.html.haml, app/views/users_management/users/index.html.haml, app/views/vehicles_management/fleets/index.html.haml, features/users_management/manage_users.feature
=> Update RC with draft

.github/dependabot.yml
=> Set dependabot pull limit. Set scheduling

.drone2.yml, app/controllers/static_pages_controller.rb, app/views/layouts/_footer.html.haml, app/views/layouts/disabled_links/_footer.html.haml, app/views/organisations/organisations/new.html.haml, app/views/static_pages/terms_and_conditions.html.haml, app/views/users_management/users/index.html.haml, app/views/vehicles_management/fleets/index.html.haml, config/routes.rb, features/organisations.feature, features/static_pages.feature, features/users_management/manage_users.feature, spec/requests/static_pages_spec.rb
Promote Accounts v1.6.2 to Staging
=> Promote Accounts v1.6.2 to Staging

app/views/static_pages/terms_and_conditions.html.haml, app/views/users_management/users/index.html.haml, app/views/vehicles_management/fleets/index.html.haml, features/users_management/manage_users.feature
Back-merge release-candidate changes to develop to resync content changes and hiding of vehicle search box
=> Back-merge release-candidate changes to develop

app/controllers/payments/payments_controller.rb, app/views/payments/payments/matrix.html.haml, features/debits.feature, features/payments.feature, features/step_definitions/helper_steps.rb, spec/requests/payments/payments/submit_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3579
=> [CAZB-3579] Update wording for button on the matrix page

app/views/layouts/application.html.haml, app/views/vehicles_management/fleets/remove.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml
https://eaflood.atlassian.net/browse/CAZB-3726
=> [CAZB-3726] Update page title

app/controllers/payments/payments_controller.rb, app/views/payments/payments/matrix.html.haml, features/debits.feature, features/payments.feature, features/step_definitions/helper_steps.rb, spec/requests/payments/payments/submit_spec.rb
=> DRAFT: [CAZB-3579] Update wording for button on the matrix page

app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3755
=> [CAZB-3755] Uncomment search button

app/views/direct_debits/debits/unsuccessful.html.haml, app/views/payments/payments/unsuccessful.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3764
Updated Contact details in payment unsuccessful pages.
=> [CAZB-3764] Payment unsuccessful - contact details update

app/api_wrappers/fleets_api.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-3755
After investigation we've found the bug that some browsers are not sending uppercase VRN from the serach form.
=> [CAZB-3755] Fixed vehicles search pagination

.drone2.yml
Update prod URL pointer in drone file
=> [CAZB-3820] Update prod URL pointer in drone file

app/views/direct_debits/debits/index.html.haml, features/debits.feature, features/step_definitions/debits_steps.rb
=> [CAZB-3718] Fix link to direct debit set up

app/views/vehicles_management/uploads/_description.html.haml
https://eaflood.atlassian.net/browse/CAZB-3829
=> [CAZB-3829] Change text on CSV upload pages

app/views/vehicles_management/fleets/index.html.haml
=> [CAZB-3755] Uncomment search button (#818)

app/controllers/direct_debits/debits_controller.rb, spec/requests/direct_debits/debits/index_spec.rb, spec/requests/direct_debits/debits/set_up_spec.rb, spec/requests/direct_debits/debits/submit_set_up_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3859
* The change allows users to enter the DirectDebit page with feature flag disabled.
=> [CAZB-3859] Allow to enter direct debit path with feature flag disabled

.drone2.yml
=> add safari back

app/controllers/vehicles_management/fleets_controller.rb, spec/requests/vehicles_management/fleets/index_spec.rb
=> [CAZB-3756] Non-alphabetic/numeric characters in Account Search 

app/controllers/direct_debits/debits_controller.rb, spec/requests/direct_debits/debits/create_spec.rb, spec/requests/direct_debits/debits/index_spec.rb, spec/requests/direct_debits/debits/new_spec.rb
=> Merge CAZB-3859 into 1.7.0

app/javascript/src/printLink/styles.scss, app/views/vehicles_management/fleets/index.html.haml
=> [CAZB-3847] Moved results-per-page-select styles to .scss

app/controllers/direct_debits/debits_controller.rb, spec/requests/direct_debits/debits/create_spec.rb, spec/requests/direct_debits/debits/index_spec.rb, spec/requests/direct_debits/debits/new_spec.rb
Promote Accounts v1.6.7 to Staging
=> Promote Accounts v1.6.7 to Staging

app/views/static_pages/help.html.haml, app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3901
=> [CAZB-3901] Add data message, calculation info to business service

app/services/session_manipulation/add_query_details.rb, spec/requests/payments/payments/submit_spec.rb, spec/services/session_manipulation/add_query_details_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3578
=> [CAZB-3578] Fix search reset when using pagination on matrix page

app/views/static_pages/help.html.haml
https://eaflood.atlassian.net/browse/CAZB-3901
=> [CAZB-3901] Update text

app/api_wrappers/debits_api.rb, app/controllers/direct_debits/debits_controller.rb, spec/api_wrappers/debits_api/create_mandate_spec.rb, spec/requests/direct_debits/debits/submit_set_up_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3691
Mandate after creation:
=> [CAZB-3691] Supply information about user creating a DD mandate

app/views/organisations/organisations/verification_failed.html.haml, app/views/static_pages/terms_and_conditions.html.haml, features/organisations.feature
https://eaflood.atlassian.net/browse/CAZB-3751
https://eaflood.atlassian.net/browse/CAZB-3858
=> [CAZB-3751, CAZB-3858] Update content

app/views/static_pages/accessibility_statement.html.haml
https://eaflood.atlassian.net/browse/CAZB-3904
=> [CAZB-3904] Amend content to Accessibility Statement page

app/controllers/vehicles_management/fleets_controller.rb, app/views/vehicles_management/fleets/_search.html.haml, spec/requests/vehicles_management/fleets/submit_search_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3098?focusedCommentId=268132
=> [CAZB-3098] Fix per_page attribute for VRN search in Vehicles Management

app/views/devise/sessions/logout_notice.html.haml, app/views/static_pages/help.html.haml
https://eaflood.atlassian.net/browse/CAZB-3544
https://eaflood.atlassian.net/browse/CAZB-3728
=> [CAZB-3544, CAZB-3728] Update content

app/views/static_pages/help.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3865 
Edited links
=> [CAZB-3865] Help page CAZ links should open in a new window

app/views/vehicles_management/vehicles/incorrect_details.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml
https://eaflood.atlassian.net/browse/CAZB-3143
=> [CAZB-2873, 2874] Update content

app/views/dashboard/_direct_debit.html.haml, app/views/dashboard/_make_payment.html.haml, features/dashboard/owner_dashboard.feature, features/dashboard/user_dashboard.feature
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3888
=> [CAZB-3888] change wording of Direct Debit on Account Home Dashboard

app/views/direct_debits/debits/index.html.haml, features/debits.feature, features/step_definitions/debits_steps.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3890
=> [CAZB-3890] change wording of Direct Debit on Direct Debits Page

app/views/users_management/edit_users/edit.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3892
=> [CAZB-3892] change wording of Direct Debit on Edit user details

app/views/users_management/create_users/add_permissions.html.haml
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3891
=> [CAZB-3891] DirectDebit wording on permissions list

app/views/dashboard/_make_payment.html.haml
https://eaflood.atlassian.net/browse/CAZB-3888
=> [CAZB-3888] Remove doubled dot

app/views/static_pages/privacy_notice.html.haml
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3975
* Added proper section to Privacy Notice page.
N/A
=> [CAZB-3975] Privacy notice amendments

app/controllers/application_controller.rb, app/views/organisations/organisations/verification_failed.html.haml, features/organisations.feature, spec/requests/organisations/email_verification_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3751
=> [CAZB-3751] Rewrite message to remove mention of fleets

app/views/payments/payments/select_payment_method.html.haml
https://eaflood.atlassian.net/browse/CAZB-3989
=> [CAZB-3989] Change order of Select your preferred payment method

app/views/direct_debits/debits/index.html.haml, features/debits.feature
Separate commit for 1.7.5 release
=> [CAZB-3890] change wording of Direct Debit on Direct Debits Page for 1.7.5 release

app/views/dashboard/_d_day_notice.html.haml, features/dashboard/owner_dashboard.feature
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3980
* Updated copy.
N/A
=> [CAZB-3980] Payments feature warning update on Dashboard

app/views/static_pages/privacy_notice.html.haml
=> [CAZB-3975] Change ENLs position in Privacy Notice

app/views/vehicles_management/fleets/vrn_not_found.html.haml
https://eaflood.atlassian.net/browse/CAZB-3747
=> [CAZB-3747] Remove the second bullet text on vehicles not found page

app/views/payments/payments/matrix/_past_week_tab.html.haml, app/views/payments/payments/matrix/_tabs.html.haml, features/payments.feature
https://eaflood.atlassian.net/browse/CAZB-3634
=> [CAZB-3634] Rename tab heading on matrix page

app/views/static_pages/privacy_notice.html.haml
=> [CAZB-3975] Remove unnecessary dot and semicolon from privacy notice

app/views/organisations/organisations/verification_failed.html.haml
In last commit we have a new route which was presented with 1.8.0 version - [LINK](https://github.com/InformedSolutions/JAQU-CAZ-Fleets-UI/commit/1c144ed59bfdcd9a3ff521a81690046377bb2eb8)
So I reverted a new route name for creating a new account to old one.
http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Fleets-UI/1540/1/4
=> Fix failed test

app/views/direct_debits/debits/index.html.haml
[CAZB-4009] Remove clause regarding DD description on bank statements
=> [CAZB-4009] Remove clause regarding DD description

app/views/direct_debits/debits/index.html.haml
[CAZB-4009] Remove clause regarding DD description on bank statements
=> [CAZB-4009] Remove clause regarding DD description (#906)

app/controllers/application_controller.rb, app/views/direct_debits/debits/set_up.html.haml, app/views/organisations/organisations/verification_failed.html.haml, app/views/payments/payments/matrix/_past_week_tab.html.haml, app/views/payments/payments/matrix/_tabs.html.haml, app/views/payments/payments/select_payment_method.html.haml, app/views/static_pages/help.html.haml, app/views/vehicles_management/vehicles/incorrect_details.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml, features/debits.feature, features/organisations.feature, features/payments.feature, package.json, spec/requests/organisations/email_verification_spec.rb, yarn.lock
Update release candidate/v1.8.0 with latest materials
=> Update release candidate/v1.8.0 with latest materials

app/views/static_pages/terms_and_conditions.html.haml
Add terms and conditions missing commit
=> [CAZB-3858] Terms and conditions

app/views/users_management/remove_users/remove.haml
https://eaflood.atlassian.net/browse/CAZB-3644
=> [CAZB-3644] Remove extra spaces

app/views/static_pages/help.html.haml, app/views/vehicles_management/fleets/index.html.haml, app/views/vehicles_management/vehicles/local_exemptions.html.haml
=> [CAZB-4011, 4012, 4017] Content update

additional_urls.yaml, app/api_wrappers/payments_api.rb, app/models/vehicles_management/vehicle_details.rb, features/debits.feature, features/payments.feature, features/step_definitions/payments_steps.rb, spec/api_wrappers/payments_api/payment_status_spec.rb, spec/fixtures/responses/caz_list.json, spec/fixtures/responses/caz_list_active.json, spec/fixtures/responses/debits/active_mandates.json, spec/fixtures/responses/debits/inactive_mandates.json, spec/fixtures/responses/debits/mandates.json, spec/fixtures/responses/no_account_mandates.json, spec/fixtures/responses/payment_history/payments.json, spec/helpers/payments_helpers_spec.rb, spec/models/clean_air_zones_spec.rb, spec/models/direct_debits/mandate_spec.rb, spec/models/manage_vehicles/vehicle_details_spec.rb, spec/models/payment_history/payment_spec.rb, spec/models/payments/status_spec.rb, spec/requests/payments/credit_cards/result_spec.rb
=> [CAZB-3388] Remove references to Leeds

app/views/layouts/application.html.haml, features/relevant_portal.feature, features/sign_in.feature
Jira card: https://eaflood.atlassian.net/browse/CAZB-4111
Used existing variable to hide Beta banner from the page. 
Sing in: 
What would you like to do page:
=> [CAZB-4111] Remove Beta banner on the What do you want to do? Page

app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-3885
Added download attribute to export link. 
It is supported in the majority of browsers: https://caniuse.com/download
Tested in Safari on mac and worked as expected. 
N/A
=> [CAZB-3885] Fix CSV Result Download Opening in new tab - Safari

app/controllers/vehicles_management/fleets_controller.rb, app/javascript/src/printLink/styles.scss, app/javascript/styles/application.scss, app/views/vehicles_management/fleets/_pagination.html.haml, app/views/vehicles_management/fleets/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-4116
Do not render pagination div when vehicles is less than 10.
Move scss class to proper file.
Fixed typo.
Same fix will be implemented for [CS UI](https://eaflood.atlassian.net/browse/CAZB-4088)
BEFORE:
AFTER:
=> [CAZB-4116] Do not render empty div block if vehicles less than 10

app/views/dashboard/_company_payment_history.html.haml, app/views/dashboard/index.html.haml, app/views/payment_history/payment_history/company_payment_history.html.haml, app/views/users_management/create_users/new.html.haml, app/views/users_management/users/index.html.haml, app/views/vehicles_management/fleets/choose_method.html.haml, app/views/vehicles_management/fleets/remove.html.haml, app/views/vehicles_management/uploads/index.html.haml, features/dashboard/owner_dashboard.feature, features/dashboard/user_dashboard.feature, features/payment_history.feature, features/payments.feature, features/sign_in.feature, features/step_definitions/account_details/emails_steps.rb, features/support/mock_users.rb, features/support/sign_in_helper.rb, features/users_management/manage_users.feature, features/vehicles_management/uploads.feature
https://eaflood.atlassian.net/browse/CAZB-4174
=> [CAZB-4174] Marks an account name as trusted safe for page titles

app/models/payment_history/payment.rb, app/views/payment_history/payment_history/company_payment_history.html.haml, app/views/payment_history/payment_history/user_payment_history.html.haml, features/payment_history.feature, spec/fixtures/responses/payment_history/payments.json, spec/models/payment_history/payment_spec.rb
Jira Card: 
https://eaflood.atlassian.net/browse/CAZB-4136
=> [CAZB-4136] update payment history to include refunds/chargebacks

app/views/dashboard/index.html.haml, app/views/users_management/create_users/new.html.haml, app/views/users_management/users/index.html.haml, app/views/vehicles_management/fleets/choose_method.html.haml, app/views/vehicles_management/fleets/remove.html.haml, app/views/vehicles_management/uploads/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-4174
https://apidock.com/rails/ActionView/Helpers/OutputSafetyHelper/raw
=> [CAZB-4174] Do not escape tags an account name for page titles

app/api_wrappers/payment_history_api.rb, app/controllers/payment_history/payment_history_controller.rb, app/helpers/time_zone_helper.rb, app/models/payment_history/details.rb, app/models/payment_history/payment_modification.rb, app/views/payment_history/payment_history/_payment_modifications.html.haml, app/views/payment_history/payment_history/payment_history_details.html.haml, features/payment_history.feature, spec/api_wrappers/payment_history_api/payment_details_spec.rb, spec/fixtures/responses/payment_history/payment_details.json, spec/models/payment_history/payment_modification_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4133
List of payments: 
Payment with refunds
Payment without refunds
=> [CAZB-4133] Update payment history details to include refunds/chargebacks

app/views/static_pages/privacy_notice.html.haml
* Link to JIRA: https://eaflood.atlassian.net/browse/CAZB-4144
=> [CAZB-4144] Privacy Notice update

app/api_wrappers/debits_api.rb, app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/helpers/application_helper.rb, app/models/direct_debits/debit.rb, features/dashboard/owner_dashboard.feature, features/step_definitions/dashboard_steps.rb, spec/models/direct_debits/debit_spec.rb, spec/requests/dashboard_controller_spec.rb, spec/support/users_factory.rb
https://eaflood.atlassian.net/browse/CAZB-4178
=> [CAZB-4178] Prevent filtering of active CAZs for beta group

app/models/payment_history/details.rb, spec/fixtures/responses/payment_history/payment_details.json, spec/models/payment_history/details_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3873
=> [CAZB-3873] Sort refunds/chargebacks alphabetically by vrn

.drone2.yml
[CAZB-4110] Update drone file for new Account Pay domain
=> [CAZB-4110] Update drone file for new Account Pay domain

app/views/static_pages/terms_and_conditions.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4218
=> [CAZB-4218] Update contact hours in support

app/views/static_pages/help.html.haml
=> [CAZB-4210] add tax class to help page

app/api_wrappers/accounts_api/accounts.rb, app/controllers/account_details/account_cancellations_controller.rb, app/forms/account_details/cancellation_confirmation_form.rb, app/views/account_details/account_cancellations/account_closing_notice.html.haml, app/views/account_details/primary_users/primary_account_details.html.haml, config/routes.rb, features/account_details/account_cancellation.feature, features/step_definitions/account_details/account_cancellation_steps.rb, features/step_definitions/account_details/primary_user_steps.rb, spec/forms/account_details/cancellation_confirmation_form_spec.rb, spec/forms/vehicles_management/confirmation_form_spec.rb, spec/requests/account_details/account_cancellations/account_closing_notice_spec.rb, spec/requests/account_details/account_cancellations/confirm_account_closing_notice_spec.rb, spec/requests/account_details/account_cancellations/submit_account_cancellation_spec.rb
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3734
* Added page with closing account notice
=> [CAZB-3734] Closing account notice page

app/controllers/account_details/account_cancellations_controller.rb, app/views/account_details/account_cancellations/account_closed.html.haml, features/account_details/account_cancellation.feature
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3736
* Added proper text to Account Closed page
=> [CAZB-3736] Account closed page

app/models/payment_history/details.rb, spec/fixtures/responses/payment_history/payment_details.json, spec/models/payment_history/details_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4259
=> [CAZB-4259] Ensure Payt history details ordered by number plate

app/models/payment_history/details.rb, app/models/payment_history/details_payment.rb, spec/models/payment_history/details_payment_spec.rb, spec/models/payment_history/details_spec.rb
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4273
=> [CAZB-4273] Date format fix

app/api_wrappers/compliance_checker_api.rb, app/controllers/payments/payments_controller.rb, app/models/clean_air_zone.rb, app/views/payments/payments/in_progress.html.haml, features/payments.feature, features/step_definitions/vehicles_management/fleets_steps.rb, features/support/mock_vccs.rb, spec/models/clean_air_zones_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4267
=> [CAZB-4267] User in "loop" when making payment when only one caz is available

app/views/payment_history/payment_history/payment_history_details.html.haml, features/payment_history.feature
https://eaflood.atlassian.net/browse/CAZB-4004
=> [CAZB-4004] Replace `Charge back` to `Chargeback`

app/controllers/dashboard_controller.rb, app/views/dashboard/index.html.haml, features/dashboard/user_dashboard.feature, features/step_definitions/account_details/emails_steps.rb, features/step_definitions/account_details/primary_user_steps.rb, features/step_definitions/dashboard_steps.rb, features/step_definitions/helper_steps.rb, features/step_definitions/payment_history_steps.rb, features/step_definitions/sign_in_steps.rb, features/step_definitions/users_management/manage_users_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/step_definitions/vehicles_management/uploads_step.rb, features/support/mock_debit.rb, spec/requests/dashboard_controller_spec.rb, spec/support/payment_history/mocked_responses.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4252
Updated Accesibility of Payments History panel on the Dashboard.
=> [CAZB-4252] Hide Payment History tile on dashboard when there are no payments

app/javascript/styles/application.scss, app/views/payment_history/payment_history/_payment_modifications.html.haml, app/views/payment_history/payment_history/payment_history_details.html.haml
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4291
* Adjusted alignment with width described in %
=> [CAZB-4291] Payment history alignment

app/models/payment_history/details_payment.rb
QA comment: https://eaflood.atlassian.net/browse/CAZB-4259?focusedCommentId=282447
=> [CAZB-4259]  Ensure Payt history details dates are ordered

app/controllers/payments/payments_controller.rb, app/models/clean_air_zone.rb, spec/models/clean_air_zones_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4267
=> [CAZB-4267] User in "loop" when making payment

app/views/account_details/account_cancellations/account_closed.html.haml
Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3736
=> [CAZB-3736] Removed back button

app/views/static_pages/privacy_notice.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4387
=> [CAZB-4387] Combine and update Privacy Notice

app/controllers/dashboard_controller.rb, app/views/dashboard/index.html.haml
https://eaflood.atlassian.net/browse/CAZB-4178
=> [CAZB-4178] Don't hide DD button for beta testers

app/views/dashboard/index.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4231
Fix when second user permission to view history but only Admin has made the payments.
=> [CAZB-4231] Update dashboard to make payment history dynamic - fix

app/views/static_pages/accessibility_statement.html.haml
Jira card: https://eaflood.atlassian.net/browse/CAZB-4389
=> [CAZB-4389] Update Accessibility Statement 

app/views/account_details/account_cancellations/account_closing_notice.html.haml
=> [CAZB-3734] Removed download payment history reference

app/forms/account_details/account_cancellation_form.rb, app/views/account_details/account_cancellations/account_cancellation.html.haml
=> [CAZB-3735] Fixed account closure error form

app/views/account_details/account_cancellations/account_closing_notice.html.haml
https://eaflood.atlassian.net/browse/CAZB-3734
=> [CAZB-3734] Added missing error message

app/helpers/payments_helper.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4260
=> [CAZB-4260] Payment Review incorrect ordering

additional_urls.yaml, app/helpers/payments_helper.rb, app/models/clean_air_zone.rb, app/models/vehicles_management/vehicle_details.rb, app/views/payments/payments/success.html.haml
* JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4091
* Removed integration of `additional_urls.yml` file
N/A
=> [CAZB-4091] Remove additional_urls integration

app/controllers/payments/payments_controller.rb
https://eaflood.atlassian.net/browse/CAZB-4267
=> [CAZB-4267] Show `Pay for another CAZ` link for beta users

app/controllers/static_pages_controller.rb, app/controllers/vehicles_management/fleets_controller.rb, app/models/clean_air_zone.rb, features/static_pages.feature, features/vehicles_management/fleets.feature, spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb, spec/fixtures/responses/caz_list.json, spec/models/clean_air_zones_spec.rb
IMPORTANT!: Don't merge before PaymentsApi is done: https://eaflood.atlassian.net/browse/CAZB-4334
Jira Cards: 
- https://eaflood.atlassian.net/browse/CAZB-4329
- https://eaflood.atlassian.net/browse/CAZB-4327
- https://eaflood.atlassian.net/browse/CAZB-4328
Tested with mocked response:
=> [CAZB-4329] Apply new rules for dynamic Tariff configuration settings to show/hide Clean Air Zones

app/controllers/static_pages_controller.rb, app/models/clean_air_zone.rb, app/views/static_pages/privacy_notice.html.haml, features/static_pages.feature, features/step_definitions/static_pages_steps.rb, spec/requests/static_pages_controller_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4336
=> [CAZB-4336] Dynamic tariff configuration for Privcay Policy page

app/views/static_pages/help.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4295
Added new section to help page.
=> [CAZB-4295] Add refund text to Help page

app/controllers/dashboard_controller.rb, app/models/direct_debits/debit.rb, app/views/dashboard/_direct_debit.html.haml, app/views/dashboard/_help.html.haml, features/dashboard/owner_dashboard.feature, features/dashboard/user_dashboard.feature, features/payment_history.feature, features/step_definitions/dashboard_steps.rb, features/step_definitions/password_reset_steps.rb, features/step_definitions/payment_history_steps.rb, features/step_definitions/payments_steps.rb, features/step_definitions/users_management/edit_user_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/step_definitions/vehicles_management/vehicles_steps.rb, spec/fixtures/responses/debits/all_active_mandates.json, spec/fixtures/responses/debits/all_inactive_mandates.json, spec/requests/dashboard_controller_spec.rb, spec/support/mocked_responses.rb
https://eaflood.atlassian.net/browse/CAZB-4451
* Content changes for Direct Debit and Help
=> [CAZB-4451] Content changes for direct debits

app/models/clean_air_zone.rb, app/views/static_pages/help.html.haml, features/static_pages.feature, spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb, spec/fixtures/responses/caz_list.json, spec/models/clean_air_zones_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4476
* Added column with Direct Debit dynamic data on Help page
*
=> [CAZB-4476] DirectDebit update on Help page

app/views/dashboard/index.html.haml
* https://eaflood.atlassian.net/browse/CAZB-4451
* Changed tiles ordering
=> [CAZB-4451] Fixed tiles ordering

app/views/static_pages/privacy_notice.html.haml
=> Updated privacy notice with CCC section

app/views/vehicles_management/fleets/index.html.haml, features/vehicles_management/fleets.feature
https://eaflood.atlassian.net/browse/CAZB-4484
=> [CAZB-4484] Change content on manage vehicles page

app/controllers/vehicles_management/fleets_controller.rb, spec/requests/vehicles_management/fleets/submit_search_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4530
=> [CAZB-4530] Missing content on manage vehicles page after search

app/api_wrappers/accounts_api/users.rb, app/controllers/dashboard_controller.rb, app/controllers/vehicles_management/fleets_controller.rb, app/helpers/fleets_helper.rb, app/models/user.rb, app/services/vehicles_management/dynamic_cazes/add_another_caz.rb, app/services/vehicles_management/dynamic_cazes/base.rb, app/services/vehicles_management/dynamic_cazes/remove_selected_caz.rb, app/services/vehicles_management/dynamic_cazes/select_caz.rb, app/services/vehicles_management/dynamic_cazes/selected_cazes.rb, app/views/vehicles_management/fleets/_dynamic_table.html.haml, app/views/vehicles_management/fleets/_static_table.html.haml, app/views/vehicles_management/fleets/index.html.haml, config/routes.rb, features/step_definitions/vehicles_management/fleets_steps.rb, spec/api_wrappers/accounts_api/users/user_spec.rb, spec/fixtures/responses/caz_list_active.json, spec/fixtures/responses/caz_list_more_than_3.json, spec/fixtures/responses/users_management/user.json, spec/requests/vehicles_management/fleets/add_another_zone_spec.rb, spec/requests/vehicles_management/fleets/index_spec.rb, spec/requests/vehicles_management/fleets/remove_selected_zone_spec.rb, spec/requests/vehicles_management/fleets/select_zone_spec.rb, spec/services/vehicles_management/dynamic_cazes/add_another_caz_spec.rb, spec/services/vehicles_management/dynamic_cazes/remove_selected_caz_spec.rb, spec/services/vehicles_management/dynamic_cazes/select_caz_spec.rb, spec/services/vehicles_management/dynamic_cazes/selected_cazes_spec.rb, spec/support/mocked_responses.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4375
Updated Manage Fleet view when there is more than 3 active CAZes.
=> [CAZB-4375] Update the manage vehicles page to allow a user to check multiple zones

app/javascript/styles/application.scss, app/views/vehicles_management/fleets/_dynamic_table.html.haml, app/views/vehicles_management/fleets/_static_table.html.haml, features/step_definitions/helper_steps.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/support/mock_vccs.rb, features/vehicles_management/fleets.feature
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4375 + QA review
Fixed columns with 
Added feature test for adding new columns
=> [CAZB-4375] Update the manage vehicles page to allow a user to check multiple zones 

app/views/dashboard/_direct_debit.html.haml
=> [CAZB-4451] Word change

app/views/static_pages/help.html.haml
https://eaflood.atlassian.net/browse/CAZB-4295
=> [CAZB-4295] Update refunds link text on help page

app/controllers/dashboard_controller.rb, app/controllers/vehicles_management/fleets_controller.rb, app/helpers/fleets_helper.rb, app/models/clean_air_zone.rb, app/services/vehicles_management/dynamic_cazes/add_another_caz.rb, app/services/vehicles_management/dynamic_cazes/base.rb, app/services/vehicles_management/dynamic_cazes/remove_selected_caz.rb, app/services/vehicles_management/dynamic_cazes/select_caz.rb, app/services/vehicles_management/dynamic_cazes/selected_cazes.rb, app/views/vehicles_management/fleets/_dynamic_table.html.haml, spec/fixtures/responses/users_management/user_with_empty_selected_cazes.json, spec/requests/vehicles_management/fleets/add_another_zone_spec.rb, spec/requests/vehicles_management/fleets/index_spec.rb, spec/requests/vehicles_management/fleets/remove_selected_zone_spec.rb, spec/requests/vehicles_management/fleets/select_zone_spec.rb, spec/services/vehicles_management/dynamic_cazes/add_another_caz_spec.rb, spec/services/vehicles_management/dynamic_cazes/remove_selected_caz_spec.rb, spec/services/vehicles_management/dynamic_cazes/select_caz_spec.rb, spec/services/vehicles_management/dynamic_cazes/selected_cazes_spec.rb, spec/support/users_management/mocked_responses.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3990
=> [CAZB-3990] Fix - Allow to choose the same CAZ multiple times in VehiclesManagement view

app/controllers/vehicles_management/fleets_controller.rb
https://eaflood.atlassian.net/browse/CAZB-3990?focusedCommentId=290230
=> [CAZB-3990] Fix search by vrn

app/controllers/vehicles_management/fleets_controller.rb
=> Updated RC with draft

app/views/payments/payments/matrix/_table.html.haml
=> [CAZB-4575] Update date format in label

app/views/payment_history/payment_history/_payment_modifications.html.haml, app/views/payment_history/payment_history/payment_history.html.haml, app/views/payment_history/payment_history/payment_history_details.html.haml
=> [CAZB-4620] [CAZB-4621] Update payment history headers

app/views/static_pages/help.html.haml, yarn.lock
https://eaflood.atlassian.net/browse/CAZB-4639
=> [CAZB-4639] Add additional content to data message in Help page

app/api_wrappers/payment_history_api.rb, app/controllers/payment_history/payment_history_controller.rb, app/services/payment_history/initiate_payment_history_export.rb, app/views/payment_history/payment_history/payment_history.html.haml, config/routes.rb, features/payment_history/payment_history_download.feature, features/step_definitions/payment_history_steps.rb, features/support/mock_payments.rb, spec/api_wrappers/payment_history_api/payment_history_export_spec.rb, spec/requests/payment_history/initiate_payment_history_download_spec.rb, spec/services/payment_history/initiate_payment_history_export_spec.rb
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4501
=> [CAZB-4501] Download button for CSV payment history

app/api_wrappers/accounts_api/payment_history.rb, app/api_wrappers/payment_history_api.rb, app/services/payment_history/initiate_payment_history_export.rb, features/support/mock_payments.rb, spec/api_wrappers/accounts_api/payment_history/payment_history_export_spec.rb, spec/services/payment_history/initiate_payment_history_export_spec.rb
=> [CAZB-4501] Payment history export api call fix

app/views/static_pages/help.html.haml
https://eaflood.atlassian.net/browse/CAZB-4639
=> [CAZB-4639] Update additional content to data message in Help page

app/views/account_details/account_cancellations/account_closing_notice.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4458
=> [CAZB-4458] Accounts closure content update to include csv download

app/views/account_details/account_cancellations/account_closing_notice.html.haml
Last commit was not deployed so i need to re-run it.
http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Fleets-UI/1984
=> [CAZB-4458] Fix failed deploy

app/api_wrappers/accounts_api/payment_history.rb, app/controllers/payment_history/payment_history_controller.rb, app/models/aws_signed_url.rb, app/models/payment_history/export_status.rb, app/views/payment_history/payment_history/payment_history_link_expired.html.haml, config/routes.rb, features/payment_history/payment_history_download.feature, features/step_definitions/payment_history_steps.rb, features/support/mock_payments.rb, spec/api_wrappers/accounts_api/payment_history/payment_history_export_status_spec.rb, spec/fixtures/responses/payment_history/export_status.json, spec/models/aws_signed_url_spec.rb, spec/models/payment_history/export_status_spec.rb, spec/requests/payment_history/handle_payment_history_download_attempt_spec.rb, spec/requests/payment_history/payment_history_link_expired_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4500
=> [CAZB-4500] Handle CSV payment history download attempt

app/forms/vrn_form.rb, spec/forms/vrn_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4213
=> [CAZB-4213] Validate VRN with leading 0's on manage vehicles page

app/controllers/payment_history/payment_history_controller.rb, config/routes.rb, spec/api_wrappers/accounts_api/payment_history/payment_history_export_spec.rb, spec/models/payment_history/export_status_spec.rb, spec/services/payment_history/back_link_history_spec.rb
=> [CAZB-4500] Rename path url for payment history export

app/views/static_pages/privacy_notice.html.haml, features/static_pages.feature
https://eaflood.atlassian.net/browse/CAZB-4714
=> [CAZB-4713] Use operator name on privacy policy page

app/api_wrappers/accounts_api/payment_history.rb, app/controllers/payment_history/payment_history_controller.rb, app/forms/vrn_form.rb, config/routes.rb, spec/api_wrappers/accounts_api/payment_history/payment_history_export_spec.rb, spec/forms/vrn_form_spec.rb, spec/models/payment_history/export_status_spec.rb, spec/services/payment_history/back_link_history_spec.rb
=> Draft release candidate/v2.3.0

app/views/devise/sessions/new.html.haml
When signed out user wanted to access page which requires authentication he was redirected to Sign In page with empty `There is a problem` box.
=> [CAZB-4465] Do not display error problem when errors are missing

config/environments/production.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4656
Tested by setting hosts on development environment
=> [CAZB-4656] Add whitelist known `HOST` values from ENV

app/views/relevant_portal/what_would_you_like_to_do.html.haml, config/routes.rb
https://eaflood.atlassian.net/browse/CAZB-4635
=> [CAZB-4635] Update HTML on 'What would you like to do' page

app/views/layouts/application.html.haml, app/views/layouts/disabled_links/application.html.haml
https://eaflood.atlassian.net/browse/CAZB-4636
=> [CAZB-4636] Update all tab titles to include 'GOV.UK.'

app/views/payment_history/payment_history/payment_history.html.haml, features/payment_history/payment_history_download.feature
https://eaflood.atlassian.net/browse/CAZB-4454
=> [CAZB-4454] Amend the button content

app/views/devise/sessions/new.html.haml, app/views/payment_history/payment_history/payment_history.html.haml, app/views/static_pages/privacy_notice.html.haml, features/payment_history/payment_history_download.feature, features/static_pages.feature
Update draft release candidate 2.3.0
=> Update draft release candidate 2.3.0

app/views/payment_history/payment_history/payment_history_downloading.html.haml, features/payment_history/payment_history_download.feature
[CAZB-4455] Update content on payment history download page
Updates content on the payments CSV download page.
Updated feature file accounts for revised title being presented.
=> [CAZB-4455] Update content on payment history download page

config/environments/production.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-4696
Before:
After:
=> [CAZB-4696] Fix Username enumeration through header manipulation

Gemfile.lock, app/views/vehicles_management/vehicles/incorrect_details.html.haml, yarn.lock
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4202
=> [CAZB-4202] Incorrect details page - change text about contact

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/payment_history/payment_history_controller.rb, app/exceptions/referer_xss_exception.rb, app/services/security/referer_xss_handler.rb, app/views/layouts/application.html.haml, app/views/layouts/disabled_links/application.html.haml, app/views/payment_history/payment_history/payment_history.html.haml, app/views/payment_history/payment_history/payment_history_downloading.html.haml, app/views/relevant_portal/what_would_you_like_to_do.html.haml, app/views/vehicles_management/vehicles/incorrect_details.html.haml, config/environments/production.rb, config/routes.rb, features/payment_history/payment_history_download.feature, spec/services/security/referer_xss_handler_spec.rb, yarn.lock
=> Promote develop to r-c/v2.4.0

app/views/payment_history/payment_history/payment_history_link_no_access.html.haml
Jira card https://eaflood.atlassian.net/browse/CAZB-4747
=> [CAZB-4747]  Error screen for unauthorised users of a Payment History Download attempt fix typo

.drone2.yml, yarn.lock
https://www.npmjs.com/advisories/1693
=> Exclude Advisory from yarn audit until it is fixed

app/controllers/application_controller.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4656
=> [CAZB-4656] Fix exception handling to render Service Unavailable

app/services/security/host_header_validator.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4648
=> [CAZB-4656] Add Host header check if was modified

app/views/payment_history/payment_history/payment_history.html.haml, features/payment_history/payment_history_download.feature
Jira Card:  https://eaflood.atlassian.net/browse/CAZB-4839
=> [CAZB-4839] Remove Payments History download button

app/javascript/src/hmrcFrontendAssets.js, app/javascript/styles/hmrc-frontend.scss, app/views/layouts/_navbar.haml
=> [CAZB-4099] Fix css style for 'Account details' button

app/controllers/application_controller.rb, app/services/security/host_header_validator.rb, spec/services/security/host_header_validator_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4857
Updated the host validator to handle multiple allowed hosts defined in ENV
=> [CAZB-4857] Update Host header vulnerability protection to support multiple alternative host names

app/views/vehicles_management/vehicles/not_found.html.haml
[CAZB-4878] Minor typography correction
=> [CAZB-4878] Minor typography correction

app/views/layouts/_navbar.haml, app/views/layouts/disabled_links/_navbar.haml
=> [CAZB-4099] Enable navbar menu when javascript is disabled

app/views/static_pages/privacy_notice.html.haml, yarn.lock
https://eaflood.atlassian.net/browse/CAZB-4834
=> [CAZB-4834] Privacy notice amendments

app/views/payments/payments/index.html.haml
Update to Clean Air Zone selection page
Visual checks performed with screen capture below
=> [CAZB-4885] Update content on CAZ selection page

app/views/account_details/account_cancellations/account_closing_notice.html.haml, app/views/payment_history/payment_history/payment_history.html.haml, features/payment_history/payment_history_download.feature
* https://eaflood.atlassian.net/browse/CAZB-4868
* https://eaflood.atlassian.net/browse/CAZB-4869
=> [CAZB-4868] Restore payment history download link

app/views/account_details/account_cancellations/account_closing_notice.html.haml, app/views/payment_history/payment_history/payment_history.html.haml, features/payment_history/payment_history_download.feature
[CAZB-4868] Restore payment history download link (#1104)
=> [CAZB-4868] Restore payment history download link (#1104)

.drone2.yml
[CAZB-4917] Fix Account Pay survey link
=> [CAZB-4917] Fix Account Pay survey link

app/controllers/application_controller.rb, app/exceptions/invalid_host_exception.rb, app/services/security/host_header_validator.rb, config/application.rb, spec/services/security/host_header_validator_spec.rb
=> Release/v2.3.4 into Pre-prod

.drone2.yml, .iyarc, README.md, app/controllers/payments/payments_controller.rb, app/views/payments/payments/review.html.haml, features/payments.feature, features/step_definitions/vehicles_management/fleets_steps.rb, spec/requests/payments/payments/confirm_review_spec.rb, spec/requests/payments/payments/review_spec.rb, spec/requests/payments/payments/select_payment_method_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4934
=> [CAZB-4934] Disable DD payment selection based on CAZ specific flags

app/controllers/payments/payments_controller.rb, app/models/payments/constants.rb, spec/requests/payments/payments/review_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4934?focusedCommentId=300794
=> [CAZB-4934] Enable DD payment selection if user is beta tester

.drone2.yml, .iyarc, README.md, app/controllers/payments/payments_controller.rb, app/models/payments/constants.rb, app/views/account_details/account_cancellations/account_closing_notice.html.haml, app/views/payment_history/payment_history/payment_history.html.haml, app/views/payments/payments/review.html.haml, app/views/static_pages/privacy_notice.html.haml, features/payment_history/payment_history_download.feature, features/payments.feature, features/step_definitions/vehicles_management/fleets_steps.rb, spec/requests/payments/payments/confirm_review_spec.rb, spec/requests/payments/payments/review_spec.rb, spec/requests/payments/payments/select_payment_method_spec.rb
Draw up develop changes to 2.4.0
=> Draw up develop changes to 2.4.0

.drone2.yml, .iyarc, README.md, app/controllers/payments/payments_controller.rb, app/models/payments/constants.rb, app/views/payments/payments/review.html.haml, features/payments.feature, features/step_definitions/vehicles_management/fleets_steps.rb, spec/requests/payments/payments/confirm_review_spec.rb, spec/requests/payments/payments/review_spec.rb, spec/requests/payments/payments/select_payment_method_spec.rb
Update release candidate/v2.4.0
=> Update release candidate/v2.4.0

app/views/payments/payments/index.html.haml, app/views/relevant_portal/what_would_you_like_to_do.html.haml, app/views/static_pages/help.html.haml
Promote Account 2.3.7 to Staging
=> Promote Account 2.3.7 to Staging

app/views/relevant_portal/what_would_you_like_to_do.html.haml
[CAZB-4953] Update error positioning on triage page (#1116)
=> [CAZB-4953] Update error positioning on triage page (#1116)

app/models/payment_history/payment.rb, app/views/payment_history/payment_history/payment_history.html.haml, spec/fixtures/responses/payment_history/payments.json, spec/models/payment_history/payment_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4383
=> [CAZB-4383] Adjust total Amount paid display

app/models/payment_history/details.rb, app/views/payment_history/payment_history/payment_history_details.html.haml, features/payment_history/payment_history.feature, spec/fixtures/responses/payment_history/payment_details.json
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4287
=> [CAZB-4287] Include failed payments on payment details page

app/models/payment_history/export_status.rb, spec/fixtures/responses/payment_history/export_status_progress.json, spec/models/payment_history/export_status_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4838
Found during QA of https://eaflood.atlassian.net/browse/CAZB-4266 server error when trying to download file of not finished export.
=> [CAZB-4838] Fix Link active method to check if process finished

app/views/organisations/organisations/email_verified.haml
* JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4924
* Created new account
* Enter the confirmation URL
* No error box is displayed
=> [CAZB-4924] Do not display error box when there are no errors

app/views/organisations/organisations/email_verified.haml
[CAZB-4924] Do not display error box when there are no errors (#1128)
=> [CAZB-4924] Do not display error box when there are no errors (#1128)

app/views/static_pages/help.html.haml
[NON-JIRA] Update help page to read Zone live
=> [NON-JIRA] Update help page to read Zone live

.iyarc, app/controllers/account_details/passwords_controller.rb, app/views/devise/sessions/new.html.haml, features/account_details/passwords.feature, features/step_definitions/account_details/primary_user_steps.rb, features/step_definitions/password_update_steps.rb, spec/api_wrappers/accounts_api/auth/update_password_spec.rb, spec/requests/account_details/passwords/update_spec.rb, yarn.lock
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4907
=> [CAZB-4907] Log user out on multiple unsuccessful password updates

app/controllers/payments/payments_controller.rb, spec/requests/payments/payments/review_details_spec.rb
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4697
=> [CAZB-4697] NoMethodError when signing in on review-details action

.iyarc, app/models/payment_history/details.rb, app/models/payment_history/export_status.rb, app/views/payment_history/payment_history/payment_history_details.html.haml, features/payment_history/payment_history.feature, spec/fixtures/responses/payment_history/export_status_progress.json, spec/fixtures/responses/payment_history/payment_details.json, spec/models/payment_history/export_status_spec.rb
=> Promote r-c/v2.5.0 to ST

package.json, yarn.lock
=> bump css-what and css select

app/views/layouts/_cookie_control.html.erb, app/views/layouts/_gtm_script.html.erb, app/views/layouts/application.html.haml, config/initializers/content_security_policy.rb
=> [CAZB-4896] Update "unsafe-inline" CSP policy to use nonces

app/controllers/sessions_controller.rb, config/i18n-tasks.yml, config/initializers/devise.rb, config/initializers/session_store.rb, features/sign_in.feature, features/step_definitions/sign_in_steps.rb
* https://eaflood.atlassian.net/browse/CAZB-4664
=> [CAZB-4664] Change user timeout mechanism

app/controllers/vehicles_management/vehicles_controller.rb, app/views/vehicles_management/vehicles/local_exemptions.html.haml
https://eaflood.atlassian.net/browse/CAZB-5013
=> [CAZB-5013] Add js back button to local exemptions page

package.json, yarn.lock
Revert unnecessary changes. We should wait a new version of 'rails/webpacker` 
https://github.com/InformedSolutions/JAQU-CAZ-Fleets-UI/pull/1138
=> Revert [CAZSM-242] Bump css-what and css select

Gemfile, Gemfile.lock, README.md, app/api_wrappers/base_api.rb, config/application.rb, features/step_definitions/sign_in_steps.rb
https://eaflood.atlassian.net/browse/CAZB-4191
Add ruby lib to fix loading gem in production mode.
https://www.rubydoc.info/gems/addressable/Addressable/URI
=> [CAZB-4191] Update Base API to handle well non-ascii URIs

.drone2.yml, Gemfile, Gemfile.lock, README.md, app/api_wrappers/base_api.rb, config/application.rb, features/step_definitions/sign_in_steps.rb, package.json, yarn.lock
=> Update RC v2.5.0

.drone2.yml
Update drone file with new st domain
=> Update drone file with new st domain

app/controllers/users_management/edit_users_controller.rb, app/forms/users_management/add_user_form.rb, config/locales/en.yml, spec/forms/users_management/add_user_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4906
=> [CAZB-4906] Validate user names against blacklisted characters

app/controllers/relevant_portal_controller.rb
https://eaflood.atlassian.net/browse/CAZB-4906
=> [CAZB-4374] Disable session cookies on `what would you like to do` page

app/assets/stylesheets/no-javascript.css, app/javascript/styles/application.scss, app/views/layouts/_navbar.haml, app/views/layouts/application.html.haml, app/views/layouts/disabled_links/_navbar.haml, app/views/shared/_js_back_link.html.haml, app/views/vehicles_management/fleets/index.html.haml, config/initializers/content_security_policy.rb
https://eaflood.atlassian.net/browse/CAZB-4788
=> [CAZB-4788] Fix console warnings

config/initializers/content_security_policy.rb
=> [CAZB-4788] Fix console warning

app/controllers/vehicles_management/fleets_controller.rb, app/helpers/application_helper.rb, app/helpers/fleets_helper.rb, app/views/vehicles_management/fleets/_dynamic_table.html.haml, app/views/vehicles_management/fleets/_edit_vehicle_list_tab.html.haml, app/views/vehicles_management/fleets/_tabs.html.haml, app/views/vehicles_management/fleets/_view_charges_tab.html.haml, app/views/vehicles_management/fleets/edit.html.haml, app/views/vehicles_management/fleets/reload_dynamic_table.js.haml, config/routes.rb, features/vehicles_management/fleets.feature, spec/requests/vehicles_management/fleets/add_another_zone_spec.rb, spec/requests/vehicles_management/fleets/remove_selected_zone_spec.rb, spec/requests/vehicles_management/fleets/select_zone_spec.rb, spec/requests/vehicles_management/fleets/submit_search_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4689
=> [CAZB-4689] Amendments to Manage vehicles screen - Tabs

app/views/direct_debits/debits/index.html.haml, app/views/vehicles_management/fleets/remove.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml
=> Text changes

app/assets/stylesheets/application.css, app/assets/stylesheets/no-javascript.css, app/javascript/packs/exportButtonNotice.js, app/views/layouts/application.html.haml, app/views/vehicles_management/fleets/_dynamic_table.html.haml, app/views/vehicles_management/fleets/_view_charges_tab.html.haml
=> Fix console errors

Gemfile.lock, app/views/direct_debits/debits/unsuccessful.html.haml, app/views/payments/payments/matrix/_details.html.haml, app/views/payments/payments/matrix/_heading.html.haml, app/views/payments/payments/unsuccessful.html.haml, app/views/static_pages/support.html.haml, features/payments.feature
Text changes: 
https://eaflood.atlassian.net/browse/CAZB-5056 
https://eaflood.atlassian.net/browse/CAZB-5057
https://eaflood.atlassian.net/browse/CAZB-5058
https://eaflood.atlassian.net/browse/CAZB-5059
=> [CAZB-5056] Text updates for next 7 days

app/views/vehicles_management/fleets/_dynamic_table.html.haml, app/views/vehicles_management/fleets/_static_table.html.haml, features/vehicles_management/fleets.feature
Fixes after comment: https://eaflood.atlassian.net/browse/CAZB-4689
=> [CAZB-4689] Update manage fleet view - Remove link

.drone2.yml, ci-cd-resources/pa11y/.pa11yci.conf.js
=> Fix accessibility tests authentication

.drone2.yml
Update drone file with new sit domain
=> Update drone file with new sit domain

app/javascript/src/backLink.js
=> [CAZB-4896] Fix back button

app/views/direct_debits/debits/unsuccessful.html.haml, app/views/payments/payments/matrix/_details.html.haml, app/views/payments/payments/matrix/_heading.html.haml, app/views/payments/payments/unsuccessful.html.haml, app/views/static_pages/support.html.haml
Update text after changes in cards: 
https://eaflood.atlassian.net/browse/CAZB-5056
https://eaflood.atlassian.net/browse/CAZB-5057
https://eaflood.atlassian.net/browse/CAZB-5058
https://eaflood.atlassian.net/browse/CAZB-5059
=> [CAZB-5056] Text updates in time value

.drone2.yml
Update drone file with new pp domain
=> Update drone file with new pp domain

app/helpers/fleets_helper.rb, app/javascript/packs/vehicles_management/cazDynamicSelect.js, app/views/vehicles_management/fleets/_view_charges_tab.html.haml, app/views/vehicles_management/fleets/reload_dynamic_table.js.haml
=> [CAZB-4689] Fix inline JS for select boxes

app/controllers/vehicles_management/fleets_controller.rb, app/forms/users_management/edit_fleet_form.rb, app/views/vehicles_management/fleets/_edit_vehicle_list_tab.html.haml, app/views/vehicles_management/fleets/edit.html.haml, app/views/vehicles_management/uploads/index.html.haml, app/views/vehicles_management/vehicles/enter_details.html.haml, config/locales/en.yml, config/routes.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/vehicles_management/fleets.feature, spec/forms/users_management/edit_fleet_form_spec.rb, spec/requests/vehicles_management/fleets/submit_edit_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4688
=> [CAZB-4688] Create 'Edit vehicle list' tab

app/javascript/packs/paymentMatrix.js, app/javascript/src/paymentMatrix/initPaginationButtons.js, app/views/payments/payments/matrix.html.haml, app/views/payments/payments/matrix/_pagination_button.html.haml
=> [CAZB-4689] Fix inline JS on payment matrix page

app/views/static_pages/support.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-5042
=> [CAZB-5042] Amend Exemption links on the Support Page

.drone2.yml
[CAZB-4710] Lower domain switch
=> [CAZB-4710] Lower domain switch

app/views/layouts/_navbar.haml, config/initializers/devise.rb, spec/requests/sessions/sign_out_spec.rb
* https://eaflood.atlassian.net/browse/CAZB-4882
=> [CAZB-4882] Fix for sign-out with JS disabled

app/views/static_pages/support.html.haml
=> [CAZB-5042] Amend Exemption links on the Support Page (#1184)

app/controllers/vehicles_management/remove_vehicles_controller.rb, app/helpers/remove_vehicles_helper.rb, app/javascript/src/paymentMatrix/emptyMatrixContinuePrevention.js, app/javascript/src/removeVehicles/emptyMatrixContinuePrevention.js, app/views/vehicles_management/remove_vehicles/confirm_remove_vehicle.html.haml, app/views/vehicles_management/remove_vehicles/confirm_remove_vehicles.html.haml, app/views/vehicles_management/remove_vehicles/remove_vehicles.html.haml, config/routes.rb, spec/spec_helper.rb
=> [CAZB-4549] Add remove multiple vehicles page

app/controllers/vehicles_management/remove_vehicles_controller.rb
=> [CAZB-4637] Add confirm to remove vehicle page

app/controllers/application_controller.rb, spec/helpers/remove_vehicles_helper_spec.rb
* https://eaflood.atlassian.net/browse/CAZB-5100
=> [CAZB-5100] Return 403 error on invalid host exception

app/models/vehicles_management/paginated_fleet.rb, app/services/security/host_header_validator.rb, features/step_definitions/vehicles_management/fleets_steps.rb, features/step_definitions/vehicles_management/remove_vehicles_steps.rb, features/support/mock_fleet.rb, features/support/vehicles_management/remove_vehicles.rb, features/vehicles_management/fleets.feature, features/vehicles_management/remove_vehicles.feature, spec/fixtures/responses/vehicles_management/one_vehicle.json
=> [CAZB-4637] Add feature tests

app/views/vehicles_management/fleets/_edit_vehicle_list_tab.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4688
=> [CAZB-4688] Add missing fieldset legend

app/controllers/application_controller.rb, app/views/layouts/_navbar.haml, config/initializers/devise.rb, spec/helpers/remove_vehicles_helper_spec.rb, spec/requests/sessions/sign_out_spec.rb
=> Draft release candidate/v2.5.0

app/controllers/vehicles_management/remove_vehicles_controller.rb, app/controllers/vehicles_management/vehicles_controller.rb, features/vehicles_management/remove_vehicles.feature
=> [CAZB-4637] Refactoring

app/views/vehicles_management/fleets/_edit_vehicle_list_tab.html.haml
=> [CAZB-4688] Hide Fieldset legend

app/views/vehicles_management/fleets/_edit_vehicle_list_tab.html.haml
Change after QA https://eaflood.atlassian.net/browse/CAZB-4548
=> [CAZB-4548] Fix Remove Your Vehicles label text

.github/dependabot.yml
To get rid of unnecessary PR's for test and development libs.
For example, in package.json we have `devDependencies` block
```
"eslint": "^7.29.0",
"eslint-config-airbnb-base": "^14.2.1",
"eslint-plugin-import": "^2.23.4",
"improved-yarn-audit": "^2.3.3",
"pa11y": "^6.0.1",
"stylelint": "^13.13.1",
"stylelint-config-gds": "^0.1.0",
"webpack-dev-server": "^3.11.2"
```
=> Create new PR's only for production mode libs

app/controllers/application_controller.rb, app/controllers/vehicles_management/vehicles_controller.rb, spec/requests/dashboard_controller_spec.rb, spec/requests/security/assign_back_button_spec.rb, spec/requests/security/validate_host_headers_spec.rb, spec/spec_helper.rb
Added more security tests and remove `nocov`
=> Add test for `validate_host_headers` method

app/views/vehicles_management/fleets/_edit_vehicle_list_tab.html.haml
https://eaflood.atlassian.net/browse/CAZB-4548
=> [CAZB-4548] Remove multiplied error messages

app/views/vehicles_management/fleets/_edit_vehicle_list_tab.html.haml
=> [CAZB-4548] Remove multiplied error messages (#1210)

app/controllers/static_pages_controller.rb, app/views/layouts/_footer.html.haml, app/views/layouts/disabled_links/_footer.html.haml, app/views/relevant_portal/what_would_you_like_to_do.html.haml, app/views/static_pages/relevant_portal_cookies.html.haml, config/routes.rb, features/relevant_portal.feature, features/static_pages.feature, spec/requests/static_pages_controller_spec.rb
* https://eaflood.atlassian.net/browse/CAZB-5135
=> [CAZB-5135] Content changes on cookie statement

app/controllers/vehicles_management/vehicles_controller.rb, app/views/users_management/_d_day_notice.html.haml, app/views/vehicles_management/fleets/_charge_cannot_be_calculated.html.haml, app/views/vehicles_management/fleets/_view_charges_tab.html.haml, app/views/vehicles_management/vehicles/incorrect_details.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml, config/routes.rb, spec/requests/vehicles_management/vehicles/confirm_incorrect_details_spec.rb, spec/requests/vehicles_management/vehicles/confirm_not_found_spec.rb
* https://eaflood.atlassian.net/browse/CAZB-5086
* https://eaflood.atlassian.net/browse/CAZB-5091
* https://eaflood.atlassian.net/browse/CAZB-5095
=> [CAZB-5086] DVLA associated content changes

config/locales/en.yml, features/vehicles_management/fleets.feature, spec/forms/users_management/edit_fleet_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4548
=> [CAZB-4548] Fix error message - edit fleet page

Gemfile.lock, app/controllers/vehicles_management/fleets_controller.rb, app/views/vehicles_management/fleets/_view_charges_tab.html.haml, features/vehicles_management/fleets.feature
Jira Card: 
https://eaflood.atlassian.net/browse/CAZB-4638
=> [CAZB-4638] Fix empty search error

app/controllers/vehicles_management/fleets_controller.rb, app/views/vehicles_management/fleets/_view_charges_tab.html.haml, features/vehicles_management/fleets.feature
* [CAZB-4638] Fix empty search error
* fix security error
=> [CAZB-4638] Fix empty search error (#1219)

.env.example, app/views/vehicles_management/fleets/_tabs.html.haml, spec/requests/payment_history/payment_history_download_spec.rb
=> Add id's on manage vehicles page

app/views/vehicles_management/vehicles/incorrect_details.html.haml
* https://eaflood.atlassian.net/browse/CAZB-5095
=> [CAZB-5095] Added missing refund paragraph on incorrect details page

app/views/payments/payments/matrix/_heading.html.haml, app/views/static_pages/support.html.haml, app/views/vehicles_management/vehicles/incorrect_details.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml
* https://eaflood.atlassian.net/browse/CAZB-5127
* https://eaflood.atlassian.net/browse/CAZB-5128
=> [CAZB-5127] Update wording in PCN warnings

app/views/payments/payments/matrix/_heading.html.haml, app/views/static_pages/support.html.haml, app/views/vehicles_management/vehicles/incorrect_details.html.haml, app/views/vehicles_management/vehicles/not_found.html.haml
=> Draft release candidate/v2.5.1

.drone2.yml
Update drone file with new uat domain
=> Update drone file with new uat domain
